== Einführung

////
Dieser Text wird nicht automatisch generiert sondern ist 
direkt editiert.
////


////
Einführung in die eigentlichen Doku 
////
Willkommen in der offiziellen technischen Husst Dokumentation.
Sie erläutert das Husst Datenmodell, seine Elemente und Abhängigkeiten.
Die konkrete Plattform zur Abbildung der Daten (z. B. SQLite, XML) kann flexibel gewählt werden, 
zur Definition des Standards wird XSD genutzt. 

Die Dokumentation gliedert sich in:

* <<Datenversorgung>>
* <<Ergebnisdaten>> und  
* <<Glossar>>
 
In jedem Datenschema wird zunächst das Hauptelement (Rootelement) und seine Beziehungen zu anderen Husst-Elementen dargestellt. 
Fachbegriffe sind im Glossar aufgeführt.

////
Einführung in die Husst 
////
Das folgende Diagramm zeigt exemplarisch, wie die Husst Datenstrukturen im ÖPNV-Vertrieb eingesetzt werden können.

image::Husst-Datenfluss_002.svg[opts="inline", width=800, style="max-width:100%", link={imagesdir}/Husst-Datenfluss_002.svg, alt="Husst - ÖPNV-Vertrieb/Datenversorgung → Vekauf → Ergebnisdaten "] 
