<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:husstDV="http://husst.de/Versorgungsdaten/3_7_0"
           xmlns:api="http://husst.de/Appinfo/3_7_0"
           targetNamespace="http://husst.de/Versorgungsdaten/3_7_0"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="../../../HUSST_DvBasis_3_7_0.xsd"/>

  <xs:annotation>

     <xs:documentation>
		HUSST Versorgungsdaten - Schemata: Tarif, Angebot (verwendet Basisversorgungsdaten)
		Version: 3.7.0
		
		Mehr Informationen:
		- https://husst.de/
		- https://github.com/HUSST-de/HUSST
		
		Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
    </xs:documentation>

    <xs:appinfo>
      <api:schema name="Tarif"/>
      <api:schema name="Angebot"/>
      <api:schema name="Test"/>
<!--       <api:noDocu/> -->
    </xs:appinfo>
  </xs:annotation>


	<!-- Root-Element -->
	<xs:element name="OePVTarifDB" type="husstDV:OePVTarifDB_Type"/>
	
	<xs:element name="Husst-String" type="xs:string"/>
	<xs:element name="Husst-2" type="husstDV:Husst-2_Type"/>
	
	<xs:element name="Husst-3" type="husstDV:Husst-3_Type"/>
	<xs:element name="Husst-5" type="xs:string"/>

	<xs:element name="Husst-Complex" type="husstDV:Husst-Complex_Type"/>


	<!-- Root-Struktur -->
  <xs:complexType name="OePVTarifDB_Type">
    <xs:annotation>
      <xs:documentation>
		Das
		ist
		das
		Haus      
		Enthält die vollständige Tarif- und Angebotsdatenbank für den öffentlichen Personennahverkehr (ÖPNV) gemäß HUSST-Standard.
		Diese Struktur bildet die zentrale Wurzel für alle tarifrelevanten Definitionen, Relationen, Sorten und Preisstufen.
      </xs:documentation>
      <xs:appinfo>
        <api:schema name="Tarif"/>
        <api:schema name="Angebot"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:choice maxOccurs="unbounded">
      <xs:element ref="husstDV:Husst-String"/>
      <xs:element ref="husstDV:Husst-Complex"/>
      <xs:element ref="husstDV:Husst-2"/>
      <xs:element ref="husstDV:Husst-3"/>
      <xs:element ref="husstDV:Husst-5"/>
      <xs:element ref="husstDV:Zeitraeume"/>
     </xs:choice>
    </xs:complexType>


  <xs:complexType name="Husst-Complex_Type">
    <xs:annotation>
      <xs:documentation>
        Bediengebiete erlauben die Definition von Sichten
        auf Auswahlelemente (Tarifrelevante Punkte, Haltestellen, etc.).
        Damit ist die Möglichkeit zur Filterung von Start/Zielauswahlen
        in verschiedenen Umfeldern möglich.
      </xs:documentation>
      <xs:appinfo>
        <api:since>3.0</api:since>
        <api:primekey>
          <api:field name="ID_Bediengebiet"/>
          <api:field name="ID_Zeitraum"/>
        </api:primekey>
        <api:schema name="Angebot"/>
        <api:fieldexample>
          <api:field name="ID_Ortspunkttyp">1</api:field>
          <api:field name="Bezeichnung">Haltestelle</api:field>
          An einer Haltestelle können Fahrgäste in ein ÖPNV-Fahrzeug (Bus, Zug, ..) einsteigen oder daraus aussteigen.
        </api:fieldexample>
        <api:example>
          z.B. PT30M - 30 Minuten
        </api:example>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Deaktiviert" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ID_Zeitraum" type="husstDV:INT4" maxOccurs="1" minOccurs="1"/>
      <xs:element name="ID_Tarifgebiet" type="husstDV:INT4" minOccurs="0" maxOccurs="1"/>
      <xs:element name="Husst-2" type="husstDV:Husst-2_Type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ID_Bediengebiet" type="husstDV:INT4" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>Eindeutige ID des Bediengebiets.</xs:documentation>
          <xs:appinfo>
	        <api:example>
	          z.B. 19.00 für 19% MwSt
	        </api:example>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ID_Enum" type="husstDV:ID_Enum_Type"/>
      <xs:element name="Bezeichnung" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Bezeichnung des Bediengebiets z.B. Automaten oder Kassen.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DynAttribut" type="husstDV:DynAttribut_Subtype" maxOccurs="unbounded" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            Optionaler Erweiterungsmechanismus für zusätzliche, projektspezifische Eigenschaften.
            Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <!-- test für Default-Texte -->
      <xs:element name="DynAttribut" type="husstDV:DynAttribut_Subtype" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="ID_EnumHUSST_Type">
    <xs:annotation>
      <xs:documentation>ID_EnumHUSST_Type: Die HUSST definiert ID_Enum kleiner 1000</xs:documentation>
      <xs:appinfo>
        <api:schema name="Tarif"/>
        <api:example>
          z.B. PT60M - 60 Minuten
        </api:example>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="husstDV:INT4">
      <xs:enumeration value="1">
        <xs:annotation>
          <xs:documentation>Standard Enum für den allgemeinen Verkauf((Verkauf))</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="1">
        <xs:annotation>
          <xs:documentation>1. Klasse</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="2">
        <xs:annotation>
          <xs:documentation>2. Klasse</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ID_Enum_Type">
    <xs:annotation>
      <xs:documentation>
        ID_Enum_Type: ID_Enum ist entweder husst-spezifisch oder projektspezifisch definiert.
      </xs:documentation>
      <xs:appinfo>
        <api:schema name="Tarif"/>
        <api:example>
          z.B. PT30M - 30 Minuten
        </api:example>
      </xs:appinfo>
    </xs:annotation>
    <xs:union memberTypes="husstDV:ID_EnumHUSST_Type husstDV:ID_Projektspezifisch_Type"/>
  </xs:simpleType>

	<xs:simpleType name="Husst-2_Type" >
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
  

	<xs:simpleType name="Husst-3_Type" >
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="Husst-4_Type" >
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
</xs:schema>
