

=== Ergebnis Rootelement

[[Schichtenliste_Type]]
==== Schichten

Rootelement der Ergebnisdaten. Umfasst die Liste aller Schichten  und die Informationen, mit welcher HUSST-Version das xml erstellt wurde. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Version|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<VersionStruktur_Type,VersionStruktur>>
| |Schicht|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Schicht_Type,Schicht>>
|=======================
  ★  Pflichtelemente



Verwendet in: ohne Verwendung



=== Ergebnis Elemente


[[Any_Type]]
==== Any_Type

Der Datentyp für Felder, die keinen festen Typen haben. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |StringData|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |BinaryData|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] base64Binary
|=======================


Verwendet in:
 <<Kontrolldaten_Type,Kontrolldaten>>, <<Transaktionsdaten_Type,Transaktionsdaten>>

[[Ausgabeabschnitt_Type]]
==== Ausgabeabschnitt_Type

Definiert einen Papierabschnitt mit seiner Startnummer und der Anzahl seiner Barcodeabschnitte oder Abschnittzähler. Die Startnummer ist immer die kleinste Nummer des gelesenen Abschnittes, egal in welche Richtung die Nummerierung der Rolle geht. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |StartNr|
Startnummer des Abschnittzählers, z.B. Barcode oder anfängliche Rollennummer.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Anzahl|
Anzahl der Abschnittzähler, z.B. Barcodes

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Beleg_Type,Beleg>>, <<Datensatz_Type,Datensatz>>

[[Barbezahlung_Type]]
==== Barbezahlung_Type

Typ um eine Bargeldtransaktion mit Zahlund und Rückgeld abzubilden. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Einnahme|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Rueckgabe|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Bargeldbilanz_Type]]
==== Bargeldbilanz_Type

Für jede vorkommende Währung werden hier die Bilanzen über den Dienst, der bei Automaten gleiche mit der Schicht ist, aufgeführt. Die zugehörigen Bargeld-Einnahmen finden sich in der Kassenliste. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Anfangsbestand|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Zufuehrungen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Entnahmen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Fehleinnahmen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Kassenentnahmen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|★ |Endbestand|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Dienstende_Type,Dienstende>>

[[Beleg_Type]]
==== Beleg_Type

Enthält Informationen über den ausgegebenen Beleg 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |BelegNr|
Laufende Aufdrucknummer auf einem Papierdokument oder gespeicherte Folgenummer 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Abschnitt|
Zugehörige, unveränderliche Dokumentmerkmale. (Abschnittzähler oder rückseitiger Barcode)

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Ausgabeabschnitt_Type,Ausgabeabschnitt>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Dienstende_Type,Dienstende>>, <<EBEErfassung_Type,EBEErfassung>>, <<Geldbehaelterliste_Type,Geldbehaelterliste>>, <<Produkt_Type,Produkt>>, <<Restgeldbeleg_Type,Restgeldbeleg>>, <<Schichtabschluss_Type,Schichtabschluss>>, <<Warenkorb_Type,Warenkorb>>, <<Zahlung_Type,Zahlung>>

[[Belegkasse_Type]]
==== Belegkasse_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Betrag|
Hier kann der Gesamtbetrag der vereinnahmten Belege eingetragen werden 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Gutschrift|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifprodukt_Type,Tarifprodukt>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================


Verwendet in:
 <<Belegkassenliste_Type,Belegkassenliste>>

[[Belegkassenliste_Type]]
==== Belegkassenliste_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |BelegKasse|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Belegkasse_Type,Belegkasse>>
|=======================


Verwendet in:
 <<Dienstende_Type,Dienstende>>, <<Schichtsummen_Type,Schichtsummen>>

[[Betrag_Type]]
==== Betrag_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Waehrung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Waehrung_Type,Waehrung>>
| |Betrag|
Betrag in kleinsten Währungseinheiten (z.B. Euro-Cent) 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|=======================


Verwendet in:
 <<Barbezahlung_Type,Barbezahlung>>, <<Bargeldbilanz_Type,Bargeldbilanz>>, <<Belegkasse_Type,Belegkasse>>, <<EBEVorgang_Type,EBEVorgang>>, <<Geldbehaelter_Type,Geldbehaelter>>, <<Kasse_Type,Kasse>>, <<Preis_Type,Preis>>, <<Stuecke_Type,Stuecke>>, <<Wertbehaelter_Type,Wertbehaelter>>, <<Zahlung_Type,Zahlung>>

[[BezahlArt_Type]]
==== BezahlArt_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|=======================


Verwendet in:
 <<KKOfflineBezahlung_Type,KKOfflineBezahlung>>, <<Kasse_Type,Kasse>>, <<ZVTBezahlung_Type,ZVTBezahlung>>, <<Zahlung_Type,Zahlung>>

[[Datensatz_Type]]
==== Datensatz_Type

Der Datensatztyp ist der Hauptdatenträger der Ergebnisdaten. Er enthält einen der unten genannten Datentypen zusammen mit einem Zeitpunkt und einer pro Schicht eindeutigen Datensatznummer. Jede Schicht enthält 2 bis n Datensätze (Ereignisse). Für eine ordentliche Schicht sollten mindestens die Datensätze Schichtbeginn und Schichtabschluss enthalten sein. Allerdings können diese Datensätze auch auf mehrere xml-Dateien aufgeteilt werden. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Schichtbeginn|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Schichtbeginn_Type,Schichtbeginn>>
|★ |Schichtabschluss|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Schichtabschluss_Type,Schichtabschluss>>
|★ |Pruefbeginn|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Pruefbeginn_Type,Pruefbeginn>>
|★ |Pruefabschluss|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Pruefabschluss_Type,Pruefabschluss>>
|★ |Komponentenliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Komponentenliste_Type,Komponentenliste>>
|★ |Meldung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Meldung_Type,Meldung>>
|★ |Ausgabeabschnitt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Ausgabeabschnitt_Type,Ausgabeabschnitt>>
|★ |Transaktionsdaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsdaten_Type,Transaktionsdaten>>
|★ |Fahrtverlauf|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Fahrtverlauf_Type,Fahrtverlauf>>
|★ |Dienstbeginn|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Dienstbeginn_Type,Dienstbeginn>>
|★ |Dienstende|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Dienstende_Type,Dienstende>>
|★ |Kontrolldaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Kontrolldaten_Type,Kontrolldaten>>
|★ |Geldbehaelterliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Geldbehaelterliste_Type,Geldbehaelterliste>>
|★ |Warenkorb|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Warenkorb_Type,Warenkorb>>
|★ |EBEErfassung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<EBEErfassung_Type,EBEErfassung>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Schicht_Type,Schicht>>

[[Dienstbeginn_Type]]
==== Dienstbeginn_Type

Der Dienst Identifiziert den Verkäufer - oder verallgemeinert die Vertriebsstelle. Der Dienstbeginn kann gleichzeitig auf mehrere Vertriebsstellen bezogen sein. Hiermit besteht beispielsweise die Möglichkeit geichzeitig auf den Verkäufer und die Verkaufsstelle zu beziehen. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Vertriebsstelle|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Vertriebsstelle_Type,Vertriebsstelle>>
| |DienstPlanNr|
Die laufende Bezeichnung des Dienstplans des Gerätebedieners. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Dienstende_Type]]
==== Dienstende_Type

Das Dienstende beendet einen begonnenen Dienst. Zur Kontrolle beinhaltet der Datensatz die Summe aller Geldbeträge, aufgeteilt nach Bezahlart, aufgelistet. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Vertriebsstelle|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Vertriebsstelle_Type,Vertriebsstelle>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
|★ |Kassenliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Kassenliste_Type,Kassenliste>>
|★ |Belegkassenliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Belegkassenliste_Type,Belegkassenliste>>
| |Bargeldbilanz|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Bargeldbilanz_Type,Bargeldbilanz>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[DynAttribut_Subtype]]
==== DynAttribut_Subtype

Der Subtyp DynAttribut_Subtype dient der Definition von dynamischen Attributen als mögliche Erweiterung für die Xml-Darstellung der Daten. Der Subtyp wird nicht 1:1 für eine Abbildung auf ein relationales Datenbankmodell verwendet. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Name|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Wert|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Ausgabeabschnitt_Type,Ausgabeabschnitt>>, <<Beleg_Type,Beleg>>, <<Belegkasse_Type,Belegkasse>>, <<Dienstbeginn_Type,Dienstbeginn>>, <<Dienstende_Type,Dienstende>>, <<EBEErfassung_Type,EBEErfassung>>, <<EBEMerkmale_Type,EBEMerkmale>>, <<Fahrtverlauf_Type,Fahrtverlauf>>, <<Geldbehaelterliste_Type,Geldbehaelterliste>>, <<Kontrolldaten_Type,Kontrolldaten>>, <<Kundendaten_Type,Kundendaten>>, <<ProdFahrschein_Type,ProdFahrschein>>, <<Pruefabschluss_Type,Pruefabschluss>>, <<Pruefbeginn_Type,Pruefbeginn>>, <<Schichtabschluss_Type,Schichtabschluss>>, <<Schichtbeginn_Type,Schichtbeginn>>, <<Teilrelation_Type,Teilrelation>>, <<Transaktion_Type,Transaktion>>, <<Transaktionsdaten_Type,Transaktionsdaten>>, <<Transaktionsort_Type,Transaktionsort>>, <<Vertriebsstelle_Type,Vertriebsstelle>>

[[EBEErfassung_Type]]
==== EBEErfassung_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |BezugsNr|
Eine eindeutige ID dieses EBE-Vorgangs, es könnte bei Verkaufsgeräten die UID sein, bei Nacherfassung muss die ID vom Bediener versorgt werden. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |EBEVorgang|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<EBEVorgang_Type,EBEVorgang>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
|★ |Merkmale|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<EBEMerkmale_Type,EBEMerkmale>>
| |Kundendaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Kundendaten_Type,Kundendaten>>
|★ |Verfolgung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Verfolgung_Type,Verfolgung>>
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[EBEMerkmale_Type]]
==== EBEMerkmale_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Ort|
Eine Erfassung des Vorgangsorts. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |VorfallsOrtNotiz|
Eine textuelle Beschreibung des Vorfallsorts. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |KomfortKlasse|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Fahrausweisart|
Wenn ein Fahrausweis vorgezeigt wurde, welcher Art 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |FahrausweisNr|
Die Nummer (laufende Nummer) des Fahrausweises 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |FahrausweisEingezogen|
Wird auf true gesetzt, wenn der Fahrausweis eingezogen wurde. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
| |FahrausweisAbholung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] date
| |Bearbeitungsstelle|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |EinstiegsHaltestelle|
Die IBNR

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |EinstiegNotiz|
Eine textuelle Beschreibung zum Einstieg 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ZielHaltestelle|
Die IBNR

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |ZielNotiz|
Eine textuelle Beschreibung zum Fahrtziel bzw. Ausstieg 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Codierung|
Eine Codierung zur Angabe des Grunds zum EBE-Fall 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Codierung_Type,Codierung>>
| |Sitzplatz|
Ein Hinweis, wo der EBE-Fall angetroffen wurde 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Verhalten|
Bemerkungen zu Verhalten des EBE-Falls. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Polizei|
Wenn Polizei hinzugezogen wurde, von welchem Revier. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Polizei_Type,Polizei>>
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Linie|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Kurs|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Verbundkennung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<EBEErfassung_Type,EBEErfassung>>

[[EBEVorgang_Type]]
==== EBEVorgang_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Typ|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<VorgangsTyp_Type,VorgangsTyp>>
|★ |Beanstandung|
Entspricht der vorgegebenen Codierung z.B. der Bahn, in der Regel eine zweistellige Ziffer. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Begruendung|
Der Grund der Beanstandung (zB. nicht lesbar, vermutlich verfälscht, Tarif ungültig, ohne Kundenkarte etc.) 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Forderung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |Referenzbetrag|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<EBEErfassung_Type,EBEErfassung>>

[[EinsatzTyp_Type]]
==== EinsatzTyp_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Name|
Der Name ist ein beliebiger, sprechender Name des Einsatztyps (z.B. Vorverkauf, Bereich Hamburg Mitte). 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================


Verwendet in: ohne Verwendung

[[Fahrtverlauf_Type]]
==== Fahrtverlauf_Type

Diese Datensätze beinhalten, abweichend von anderen Datensätzen, Information aus betrieblichen VDV452 Daten.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Betrieb|
REC_FRT.BETRIEB aus VDV bei Mandantensystemen, sonst 0. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |FahrzeugNr|
Nach VDV FAHRZEUG.FZG_NR 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |FahrzeugUnr|
Nummer des Unternehmens, dem das Fahrzeug gehört. FAHRZEUG.ABK_UNTERNEHMEN 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |FahrerNr|
Nch VDV: PERSONAL.FAHRER_NR

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |FahrerUnr|
Nach VDV: PERSONAL.ABK_UNTERNEHMEN -> TEILNEHMER.UNTERNEHMEN 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |FahrtID|
Fahrtnummer der Fahrt laut VDV REC_FRT.FRT_ID 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Fahrt|
Optionale Kennung der Fahrt als Text.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |LinieID|
Nach VDV: Aus der Tabelle REC_LID.LI_NR 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Linie|
Optionale Linieninformation als Text. Optional REC_LID.LIDNAME oder REC_LID.LI_KUERZEL

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Richtung|
Nach VDV: REC_LID.LI_RI_NR 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |FahrplanLage|
Fahrplanlage in Sekunden, negative Werte für Verfrühung. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |OrtTyp|
Nach VDV: REC_ORT.ONR_TYP_NR

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |OrtNr|
Haltepunktnummer nach VDV: REC_ORT.ORT_NR 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |HpEntfernung|
Entfernung zum Haltepunkt in Metern, 0 = Haltepunkt, positiv: vor Haltepunkt 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |TuerOffen|
false: Alle Türen sind am HP geschlossen. true: mindestens eine Türe ist offen. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
| |HaltepunktDurch|
false: Fahrzeug hat am Haltepunkt gehalten. true: der Haltepunkt wurde durchfahren. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
| |Haltezeit|
Haltezeit am Haltepunkt in Sekunden. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |HaltestelleBedarf|
Gibt an, ob die Haltestelle eine reguläre oder eine Bedarfshaltestelle ist. false= reguläre Haltestelle, true = Bedarfshaltestelle 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
| |TachoStand|
Tachostand in Metern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Koordinate|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<KoordWgs84_Type,KoordWgs84>>
| |ZaehldatenListe|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zaehldatenliste_Type,Zaehldatenliste>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Geldbehaelter_Type]]
==== Geldbehaelter_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Stueck|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Stuecke_Type,Stuecke>>
| |Wert|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================


Verwendet in:
 <<Geldbehaelterliste_Type,Geldbehaelterliste>>

[[Geldbehaelterliste_Type]]
==== Geldbehaelterliste_Type

notiert die Geldwerte oder sonstige Werte (Gutscheine, Stornierungsbelege, ...) bezogen auf einen Vorgangszeitpunkt
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Vorgang|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<GeldBehaeltervorgang_Type,GeldBehaeltervorgang>>
| |Geldbehaelter|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Geldbehaelter_Type,Geldbehaelter>>
| |Wertbehaelter|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Wertbehaelter_Type,Wertbehaelter>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Geraet_Type]]
==== Geraet_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Name|
Der Name ist ein beliebiger, sprechender Name des Gerätes. (z.B. Busdrucker-1234). 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Id|
Eindeutige Kennung eines Bestandteils der Gerätehardware (z.B. die MAC der Netzwerkhardware.) Welche Kennung das ist, muss von der Gerätesoftware entschieden werden. Das Element ist optional. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================


Verwendet in:
 <<Schichtbeginn_Type,Schichtbeginn>>

[[Gutscheinbezahlung_Type]]
==== Gutscheinbezahlung_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |GutschId|
Eindeutige Kennung des Gutscheintyps

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifprodukt_Type,Tarifprodukt>>
| |Nr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[KAReferenz_Type]]
==== KAReferenz_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |SamNummer|
SAM_ID.samNummer 24 Bit (Beispiel 0x654321), eine, im gesamten Geltungsbereich der Kernapplikation eindeutige SAM-Kartennummer 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT3,INT3>>
|★ |SamSequenznummer|
samSequenznummer 32 Bit (Beispiel 0x789ABCDE), eindeutige, fortlaufende Nummer die von einer SAM-Karte generiert wird. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Kontrolldaten_Type,Kontrolldaten>>, <<Transaktion_Type,Transaktion>>, <<Transaktionsdaten_Type,Transaktionsdaten>>, <<Zahlung_Type,Zahlung>>

[[KKOfflineBezahlung_Type]]
==== KKOfflineBezahlung_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Kartenherausgeber|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<BezahlArt_Type,BezahlArt>>
|★ |KartenNr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Pruefkennung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |GueltigBis|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] gYearMonth
|★ |Unterschrift|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Kasse_Type]]
==== Kasse_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Betrag|
Kassenstand in kleinster Waehrungseinheit (z.B. Cent, Rappen, etc.) 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|★ |Zahlart|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<BezahlArt_Type,BezahlArt>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Kassenliste_Type,Kassenliste>>

[[Kassenliste_Type]]
==== Kassenliste_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Kasse|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Kasse_Type,Kasse>>
|=======================


Verwendet in:
 <<Dienstende_Type,Dienstende>>, <<Schichtsummen_Type,Schichtsummen>>

[[Komponente_Type]]
==== Komponente_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Name|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Version|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Variante|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |SerienNr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |PhysPosition|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |ErstellZeitPunkt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |Hersteller|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Komponente|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Komponente_Type,Komponente>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Komponente_Type,Komponente>>, <<Komponentenliste_Type,Komponentenliste>>

[[Komponentenliste_Type]]
==== Komponentenliste_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Vorgang|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<KomponentenVorgang_Type,KomponentenVorgang>>
| |Komponente|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Komponente_Type,Komponente>>
|=======================


Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Kontrolldaten_Type]]
==== Kontrolldaten_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Typ|
Kontrollmeldungen beliebiger Art z. B. Chipkartenkontrolle für KA-Berechtigung, DB-Online-Ticket, BOB-Ticket, DF-Fahrschein, ...

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Kontrolldaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Any_Type,Any>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[KundenTyp_Type]]
==== KundenTyp_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|=======================


Verwendet in:
 <<Mitnahme_Type,Mitnahme>>

[[Kundendaten_Type]]
==== Kundendaten_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Fahrgast|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Person_Type,Person>>
| |Erzieher|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Person_Type,Person>>
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<EBEErfassung_Type,EBEErfassung>>

[[Lastschrift_Type]]
==== Lastschrift_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |BLZ-BIC|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Konto-IBAN|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |KartenfolgeNr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Kartenart|
1=ec-Karte Magnetstreifen

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |GueltigBis|
Gültigendejahr der Karte

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] gYearMonth
|★ |Unterschrift|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Meldung_Type]]
==== Meldung_Type

Dieser Datensatz dient der Aufnahme von Textmeldungen beliebiger Art. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Nr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |MeldModTyp|
Typ des meldunggenerierenden Moduls

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Komponente|
Komponentenbezeichnung

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |PhysPosition|
Eine unterscheidende, physikalische Position, wenn mehrere gleiche Komponenten Meldungen emmitieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Text|
Meldungstext, Entwicklertext. Dieser Text wird in der Regel vor der Anzeige ersetzt. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Attribut|
Kommagetrennte Attribute die für eine Meldungstextgenerierung benötigt werden: Format('User "%s" was sleeping between %s and %s',[Attribute]) So dass auch bei sprachvarianten Anzeigen dynamische Inhalte ausgegeben werden können. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Mitnahme_Type]]
==== Mitnahme_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Fahrgasttyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<KundenTyp_Type,KundenTyp>>
|★ |Anzahl|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<ProdFahrschein_Type,ProdFahrschein>>

[[OrtsTyp_Type]]
==== OrtsTyp_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|=======================


Verwendet in:
 <<Standort_Type,Standort>>, <<Vertriebsstelle_Type,Vertriebsstelle>>

[[Ortspunkt_Type]]
==== Ortspunkt_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |ID_Ortspunkt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================


Verwendet in:
 <<Transaktionsort_Type,Transaktionsort>>

[[Person_Type]]
==== Person_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Vorname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Nachname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Namenszuatz|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |StrasseHausNr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Postleitzahl|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Laenderkennzeichen|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Wohnort|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Staat|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Geschlecht|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] 
| |TelefonNr|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Geburtsdatum|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |Staatsangehoerigkeit|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Legitimtation|
Beschreibung der legitimation, Ausweis, EC-Karte, etc. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |LegitimationNr|
Ausweisnummer

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |LegitimationsDatum|
Ausstellungsdateum der Legitimation 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |LegimitationsLand|
Ausstellungsland der Legitimation 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |LegitimationBild|
Auf der Legitimation war ein Lichtbild, das Lichtbild wurde dem EBE-Fall zugeordnet 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================


Verwendet in:
 <<Kundendaten_Type,Kundendaten>>

[[Polizei_Type]]
==== Polizei_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Dienstnummer|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Vorname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Nachname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Dienststelle|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<EBEMerkmale_Type,EBEMerkmale>>

[[Preis_Type]]
==== Preis_Type

Wenn keine Preisspalte angegeben ist, wird von der Standardspalte "1" ausgegangen. Ansonsten muss die Nummer der zugehörigen Preisspalte der Datenversorgung angegeben. Die Kennung kann optional die Kennung der Preisspalte enthalten. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Betrag|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
| |ID_Mwst|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |MwstSatz|
Wert zwischen 0 und 100 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<FLOAT1,FLOAT1>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Produkt_Type,Produkt>>

[[ProdFahrschein_Type]]
==== ProdFahrschein_Type

Beschreibt die räumliche und zeitliche Gültigkeit des verkauften Produkts. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ZeitVon|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |ZeitBis|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |Von|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |Nach|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |Via|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |ID_Relation|
Bezug auf die ID_Relation der Versorgungsdaten - die Datenversion ist identisch mit der in dem Tarifprodukt hinterlegten Datenversion 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Komfortklasse|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Rabattklasse|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Mitnahme|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Mitnahme_Type,Mitnahme>>
| |Teilrelation|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Teilrelation_Type,Teilrelation>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Produkt_Type,Produkt>>

[[Produkt_Type]]
==== Produkt_Type

Eine Datenstruktur, die die tariflichen Merkmale des verkauften Produkts beschreibt. Bei der Anwendung von Teilrelationen zur Aufteilung von Fremd- und Eigenleistungen wird wie folgt vorgegangen: Das verkaufte Produkt wird als Hauptprodukt mit der Id und ExtId 'anonym' eingetragen. Es gibt einen gemeinsamen Preis, einen gemeinsamen Beleg, un N Teilprodukte. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Anzahl|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Tarifprodukt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifprodukt_Type,Tarifprodukt>>
| |Preis|
Preisinformation zum Produkt, kannauch leer sein 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Preis_Type,Preis>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
| |Fahrschein|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ProdFahrschein_Type,ProdFahrschein>>
| |Teilprodukt|
Unterprodukte, die mitverkauftwurden (Teilstrecken,City-Cards,...) 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Produkt_Type,Produkt>>
| |AnzahlTeile|
Hier werden bei Mehrfahrtenkarten die Anzahl der einzelnen Abschnitte bzw. Anteile notiert. Wenn nicht angegeben ist, ist die Anzahl entweder unbekannt oder als Vorgabe 1. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |RestTeile|
Hier können, je nach Kontext 1.) die Anzahl der derzeitig auf der elektronischen Mehrfahrtenkarte befindlichen "Streifen" oder 2.) die Anzahl der derzeit auf der elektronischen Debitkarte befindlichen Wertanteile notiert werden. Die Betrachtung stellt den Zustand VOR der Aktion dar. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Produkt_Type,Produkt>>, <<Transaktion_Type,Transaktion>>

[[Pruefabschluss_Type]]
==== Pruefabschluss_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Ausstieg|
Ausstiegshaltestelle

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================


Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Pruefbeginn_Type]]
==== Pruefbeginn_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Kleidung|
Die vom Prüfer getragene Kleidung 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Pruefkleidung_Type,Pruefkleidung>>
| |Pruefart|
Die Art der Prüfung

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Pruefart_Type,Pruefart>>
| |Pruefer|
Beteiligte Prüfer (Nummer) 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Linie|
Liniennummer

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Verkehrsmittel|
Verkehrsmittel

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<TransportserviceArt_Type,TransportserviceArt>>
| |Einstieg|
Einstiegshaltestelle

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |Richtung|
Eine Richtungsangabe

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
| |AnzahlFahrgaeste|
Eine Abschätzung der Anzahl der Fahrgäste bei Einstieg 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================


Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Rechnungsstellung_Type]]
==== Rechnungsstellung_Type

Dieses Element trägt nähere Angaben zum nachfolgenden Rechnungsstellungs- oder verfolgungsprozess.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |RechnungsRef|
In der Regel eine Rechnungsnummer oder eine generierte Referenz auf eine zu erstellende Rechnung. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |KundenRef|
Eine Referenz auf den Kunden zur Rechnungsstellung, in der Regel eine Kundennummer 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Vorgangszeitpunkt|
Der zum Verkaufszeitpunkt zugehörige Zeitstempel.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |VorgangsRef|
Ein optionaler Bezug auf den dazugehörigen Verkaufsvorgang.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Restgeldbeleg_Type]]
==== Restgeldbeleg_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Ausgabevertriebsstelle|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Vertriebsstelle_Type,Vertriebsstelle>>
| |Kennung|
Eine eindeutige Kennung zur Identifikation des Restgeldbelegs.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
| |Ausstelldatum|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Schicht_Type]]
==== Schicht_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Datensatz|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Datensatz_Type,Datensatz>>
|=======================


Verwendet in:
 <<Schichtenliste_Type,Schichtenliste>>

[[Schichtabschluss_Type]]
==== Schichtabschluss_Type

Der Datensatz zum Schichtabschluss. Es ist der letzte Datensatz einer Schicht. Hier wird angegeben, wie der Schichtabschluss ausgelöst wurde. Hintergrund hierbei ist die Möglichkeit im personalbedienten Verkauf unterscheiden zu können, ob eine Schicht explizit durch den Nutzer eines Verkaufsgerätes (manuell) oder implizit durch das Gerät selbst (automatisch) durchgeführt wurde. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Ausloeser|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Ausloeser_Type,Ausloeser>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Schichtbeginn_Type]]
==== Schichtbeginn_Type

Der Datensatz zum Schichtbeginn. Der Schichtbeginn beinhaltet die Identifikation des Verkaufgerätes und definiert den genauen Zeitpunkt, wann das Verkaufsgerät die Verkaufsbereitschaft erreicht hat. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |SchichtNr|
Diese Schichtnummer enstpricht der den Anwendern bekannte Schichtnummer. In der Regel wird nach dieser Nummer ausgewertet und die Nummer wird auf Belege aufgedruckt. Die Schichtnummer ist mindestens für jede Schicht-UUID eindeutig. Die Schichtnummer sollte inkrementierend aufsteigen und nie '0' sein. Achtung: Schichtnummer vs. Dienstnummer: Innerhalb einer Schicht können mehrere Dienste auch gleichzeitig ablaufen. Kein Dienst überlappt zeitlich eine Schichtgrenze. Dienste sind in der Regel Personen-(Konten) oder Geräte-(Konten) zugeordnet. Schichten sind nur ein Behälter für Dienste. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Geraet|
Dieser Datensatz kennzeichnet das technische Gerät, das die Datensätze dieser Schicht erzeugt. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Geraet_Type,Geraet>>
|★ |Betriebsart|
Dieses Feld unterscheidet die Datensätze dieser Schicht in Echt- und sonstigen Betrieb. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betriebsart_Type,Betriebsart>>
| |Standort|
Dieses Feld bezeichnet den Standort zum Schichtbeginn. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Standort_Type,Standort>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Schichtsummen_Type]]
==== Schichtsummen_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Kassenliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Kassenliste_Type,Kassenliste>>
| |BelegKassenliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Belegkassenliste_Type,Belegkassenliste>>
|=======================


Verwendet in: ohne Verwendung

[[Standort_Type]]
==== Standort_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Typ|
Mit dem Typ wird die Ausprägung des jeweilgen Standorts unterschieden. Die Standorte eines Typs und eines Mandanten sind fortlaufend durchnumeriert. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<OrtsTyp_Type,OrtsTyp>>
| |Name|
Der Name ist ein beliebiger, sprechender Name des Standorts. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Schichtbeginn_Type,Schichtbeginn>>

[[Stuecke_Type]]
==== Stuecke_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Anzahl|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |StueckWert|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Geldbehaelter_Type,Geldbehaelter>>

[[Tarifprodukt_Type]]
==== Tarifprodukt_Type

Eine Datenstruktur, die die tariflichen Merkmale des verkauften Produkts beschreibt. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Tarifgebiet|
Enthält die ID des Tarifgebiets aus der zugrundeliegenden Tarifdatenbank (Versorgungsdaten). 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_Sorte|
Enthält die in den Versorgungsdaten festgelegte ID der Sorte. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExternSorte|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |ID_Preisstufe|
Enthält die ID der Preisstufe des verkauften Produkts. Die Preisstufe ist nur zusammen mit dem Tarifgebiet gültig. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExternPreisstufe|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ID_Preis|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExternPreis|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ID_Preisspalte|
Enthält die ID der Preisspalte des verkauften Produkts. Die Preisspalte ist nur zusammen mit der Preisstufe und dem Tarifgebiet gültig. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Belegkasse_Type,Belegkasse>>, <<Gutscheinbezahlung_Type,Gutscheinbezahlung>>, <<Produkt_Type,Produkt>>

[[Tarifpunkt_Type]]
==== Tarifpunkt_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |ID_Tarifpunkt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |ID_Tarifgebiet|
Enthält die Nummer des Tarifgebiets aus der zugrundeliegenden Tarifdatenbank (Versorgungsdaten). 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Teilrelation_Type,Teilrelation>>, <<Transaktionsort_Type,Transaktionsort>>

[[Teilrelation_Type]]
==== Teilrelation_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |SortOrder|
Die Sortierungsreihenfolge wird benötigt, um die Richtung der Durchfahrt zu erhalten. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |ID_Preisstufe|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExternPreisstufe|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |ID_Tarifgebiet|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Start|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifpunkt_Type,Tarifpunkt>>
| |Ziel|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifpunkt_Type,Tarifpunkt>>
| |ReferenzExternRelation|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ID_Preisquelle|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<ProdFahrschein_Type,ProdFahrschein>>

[[Transaktion_Type]]
==== Transaktion_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Produkt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Produkt_Type,Produkt>>
| |KundenNr|
Über die KundenNr kann bei personalisierter Nutzung / Kauf der Bezug zu einem im Backend hinterlegten Kundendatensatz hergestellt werden. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |BezugsNr|
Die BezugsNr findet unterschiedlich Verwendung und ist zwischen den Austauschpartnern der Schnittstelle zu vereinbaren. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Vorgangszeitpunkt|
Vorgangsnummer und Vorgangszeitpunkt identifizieren einzeln oder gemeinsam einen Vorgang. Im Speziellen werden diese beiden Werte bei der Erstattung eines Gutscheins genutzt, dann entspricht der Vorgangszeitpunkt dem Zeitpunkt der Ausgabe des eingelösten Gutscheins. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Transaktionsliste_Type,Transaktionsliste>>

[[Transaktionsdaten_Type]]
==== Transaktionsdaten_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Transaktionsart|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsart_Type,Transaktionsart>>
|★ |Transaktionsdaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Any_Type,Any>>
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[Transaktionsliste_Type]]
==== Transaktionsliste_Type

Auflistung aller einzelner Transaktionen in einem Warenkorb. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Transaktion|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktion_Type,Transaktion>>
|=======================


Verwendet in:
 <<Warenkorb_Type,Warenkorb>>

[[Transaktionsort_Type]]
==== Transaktionsort_Type

Zur Angabe an welchem Ort eine Transaktion erstellt wurde. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Ortspunkt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Ortspunkt_Type,Ortspunkt>>
| |Tarifpunkt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Tarifpunkt_Type,Tarifpunkt>>
| |ID_Relcode|
Ein Relationscode umfasst mehrere Tarifpunkte. Die ID_Relcode referenziert somit den Relationscode des Tarifs.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================


Verwendet in:
 <<EBEMerkmale_Type,EBEMerkmale>>, <<ProdFahrschein_Type,ProdFahrschein>>, <<Pruefabschluss_Type,Pruefabschluss>>, <<Pruefbeginn_Type,Pruefbeginn>>, <<Warenkorb_Type,Warenkorb>>

[[TransportserviceArt_Type]]
==== TransportserviceArt_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|=======================


Verwendet in:
 <<Pruefbeginn_Type,Pruefbeginn>>

[[Ueberweisung_Type]]
==== Ueberweisung_Type

Zur Angabe der Informationen für eine Bezahlung per Überweisung. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |BLZ-BIC|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Konto-IBAN|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Verfolgung_Type]]
==== Verfolgung_Type

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Typ|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<VerfolgungsTyp_Type,VerfolgungsTyp>>
| |Bemerkung|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<EBEErfassung_Type,EBEErfassung>>

[[VersionStruktur_Type]]
==== VersionStruktur_Type

Hier müssen Hinweise zur Version des Schemas angegeben werden. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |VersionMajor|
Diese Versionsnummer muss sich immer bei Inkompatibilitäten zur Vorgängerversion ändern. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |VersionMinor|
Diese Versionsnummer zählt kompatible Anpassungen. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |VersionPatch|
Diese Versionsnummer zählt abwärtskompatible Bugfixes. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Aenderungsdatum|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] date
|★ |Aenderungsautor|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Schichtenliste_Type,Schichtenliste>>

[[Vertriebsstelle_Type]]
==== Vertriebsstelle_Type

Der Datensatz zur Identifikation der Vertriebsstelle. Wird im Dienst verwendet um den angemeldeten Verkäufer, das VErkaufsgerät oder ähnliches zu identifizieren.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Typ|
Der Typ qualifiziert die beiden Elemente 'Mandant' und 'Nr'. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<OrtsTyp_Type,OrtsTyp>>
|★ |Mandant|
Der Mandant qualifiziert eindeutig die Zugehörigkeit der 'Nr'. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
|★ |Nr|
Hier wird, je nach Typ der Vertriebsstelle, die Personalnummer, die Vertriebsstellennummer, die Gerätenummer etc. hinterlegt. Die Nummer ist nur in Beziehung zu Mandant und dem Typ eindeutig. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |DynAttribut|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Dienstbeginn_Type,Dienstbeginn>>, <<Dienstende_Type,Dienstende>>, <<Restgeldbeleg_Type,Restgeldbeleg>>

[[Warenkorb_Type]]
==== Warenkorb_Type

Trägt die Informationen zu einem einzelnen Verkaufsvorgang.  Die einzelnen verkauften Produkte befinden sich in der Transaktionslist.  Zahlungsvorgänge und zugehörigen Belege werden in den jeweiligen Listen geführt. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |ReferenzExtern|
Definiert optional einen Identifier, um den Warenkorb eindeutig zu referenzieren. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Transaktionsort|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsort_Type,Transaktionsort>>
|★ |Transaktionliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Transaktionsliste_Type,Transaktionsliste>>
| |Zahlungsliste|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zahlungsliste_Type,Zahlungsliste>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Datensatz_Type,Datensatz>>

[[WebShopBezahlung_Type]]
==== WebShopBezahlung_Type

Zahlungstyp für die Details einer Onlinezahlungen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |TerminalId|
Eindeutige Terminal-ID bei Verwendung eines gesonderten Kartenzahlungsterminals.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |TransaktionsNr|
Vom Zahlungsdienstleister vergebene, eindeutige Transaktionsnummer der durchgeführten Zahlungstransaktion.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |Zeitpunkt|
Zeitpunkt, zu dem die Zahlungstransaktion beim Zahlungsdienstleister registriert wurde.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Wertbehaelter_Type]]
==== Wertbehaelter_Type

Hiermit werden Wertbehälter erfasst, z.B. Safebags. Die Nummer enstpricht der Nummer des Wertbehälters, die Wertanzahl der Anzahl der werthaltigen Anteile, z.B. die Anzahl der Belege. Es werden 2 Behälter unterschieden: 1. Behälter mit Bargeld -> dann muss der Betrag ausgefüllt sein (früher Wert), 2. Behälter mit werthaltigen Belegen -> dann muss die Wertanzahl ausgefüllt sein. 3. Eine Mischform ist auch möglich. 
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |WertAnzahl|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] int
| |Betrag|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|=======================


Verwendet in:
 <<Geldbehaelterliste_Type,Geldbehaelterliste>>

[[ZVTBezahlung_Type]]
==== ZVTBezahlung_Type

Zahlungstyp für die Details Kartenzahlungen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Kartenherausgeber|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<BezahlArt_Type,BezahlArt>>
|★ |TerminalId|
Eindeutige Terminal-ID bei Verwendung eines gesonderten Kartenzahlungsterminals.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |TransaktionsNr|
Vom Zahlungsdienstleister vergebene, eindeutige Transaktionsnummer der durchgeführten Zahlungstransaktion.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Zeitpunkt|
Zeitpunkt, zu dem die Zahlungstransaktion beim Zahlungsdienstleister registriert wurde.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] dateTime
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlung_Type,Zahlung>>

[[Zaehldaten_Type]]
==== Zaehldaten_Type

Datensatz zur Aufnahme von Zählungen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Einsteiger|
Anzahl der zugestiegenen Personen. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Aussteiger|
Anzahl der ausgestiegenen Personen. 

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Fehler|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|=======================


Verwendet in:
 <<Zaehldatenliste_Type,Zaehldatenliste>>

[[Zaehldatenliste_Type]]
==== Zaehldatenliste_Type

Die Liste aller aufgenommenen Zähldaten.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Zaehldaten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zaehldaten_Type,Zaehldaten>>
|=======================


Verwendet in:
 <<Fahrtverlauf_Type,Fahrtverlauf>>

[[Zahlung_Type]]
==== Zahlung_Type

Grundtyp einer Zahlung. Beinhaltet den Betrag und die Zahlart,  mit genaueren Informarionen, je nach Zahlart.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Betrag|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Betrag_Type,Betrag>>
|★ |Zahlart|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<BezahlArt_Type,BezahlArt>>
| |Beleg|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Beleg_Type,Beleg>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<Zahlungsliste_Type,Zahlungsliste>>

[[Zahlungsliste_Type]]
==== Zahlungsliste_Type

Beinhaltet alle einzelnen Zahlungen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Zahlung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zahlung_Type,Zahlung>>
|=======================


Verwendet in:
 <<Warenkorb_Type,Warenkorb>>

=== technische Enumerationen 


[[AusgabeabschnittTypHUSST_Type]]

==== AusgabeabschnittTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[AusloeserHUSST_Type]]

==== Ausloeser
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[BelegTypHUSST_Type]]

==== BelegTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[BelegkasseTypHUSST_Type]]

==== BelegkasseTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[BetriebsartHUSST_Type]]

==== Betriebsart
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[BezahlArtKa_Type]]

==== BezahlArtKa
Die BezahlArt kommt aus der VDV-KA. Die KA-Werte kommen aus dem EN1545: PaymentMeansCode 

Verwendet in: ohne Verwendung


[[GeldBehaeltervorgangHUSST_Type]]

==== GeldBehaeltervorgang
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[GeldbehaelterTypHUSST_Type]]

==== GeldbehaelterTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[KasseTypHUSST_Type]]

==== KasseTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[KomponentenKlasseHUSST_Type]]

==== KomponentenKlasse
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[KomponentenVorgangHUSST_Type]]

==== KomponentenVorgang
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[KundenTypKa_Type]]

==== KundenTypKa
Der Kundentyp kommt aus der VDV-KA. Die KA-Werte kommen aus dem EN1545: ProfileCodeIOP 

Verwendet in: ohne Verwendung


[[MeldungsklasseHUSST_Type]]

==== Meldungsklasse
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[OrtsTypKa_Type]]

==== OrtsTypKa
Der OrtsTyp kommt aus der VDV-KA. Die KA-Werte kommen aus dem EN1545: LocationTypeCode 

Verwendet in: ohne Verwendung


[[PreisverrechnungHUSST_Type]]

==== Preisverrechnung
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[PruefartHUSST_Type]]

==== Pruefart
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[PruefkleidungHUSST_Type]]

==== Pruefkleidung
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[TransaktionTypHUSST_Type]]

==== TransaktionTyp
Sonderfälle: • Gutscheine werden verkauft • Gutscheine werden erstattet • EBE-Einzahlung – der Kunde „kauft“ aus seiner EBE-Schuld mit der „BezugsNr“ einen Anteil, es liegt ein ktTransTyp „husst.Verkauf“ vor. Es gibt einen Preis, es wird ein Beleg gedruckt. • Die Ausgabe eines Wertes auf eine Karte (Debitkarte) entspricht dem Verkauf eines Gutscheins. Der Unterschied zum Gutschein ist, dass dieser Gutschein in Tranchen eingelöst werden kann. Es muss auf alle Fälle die „BezugsNr“ (sprich Kartennummer) und je nach Anwendung die Kundennummer beim Verkauf notiert werden. • Die Einlösung eines Wertes entspricht der teilweisen oder vollständigen Erstattung eines Gutscheins mit den gleichen Registrierungen, es können jedoch auch nur Teilwerte „erstattet“ werden. (ktTransTyp = husst.Erstattung) • Der Verkauf einer elektronischen Mehrfahrtenkarte entspricht dem Verkauf einer Mehrfahrtenkarte auf Papier mit dem einzigen Unterschied, dass die BezugsNr (sprich Kartennummer) und je nach Anwendung die Kundennummer registriert wird. In dem Feld „AnzahlTeile“ kann die Menge der Mehrfahrten, die jedoch schon über die Sorte festgelegt sein sollten, zusätzlich notiert werden. • Das Entwerten eines oder mehrerer „Streifen“ einer elektronischen Mehrfahrtenkarte kann mittels „Registrierung“ erfasst werden. Wieder unterscheidet die Tarifprodukt den Kontext, es gibt keinen Preis, nur eventuell einen Beleg, aber eine „BezugsNr“. In dem Feld „AnzahlTeile“ müssen die Menge der entwerteten „Streifen“ notiert werden. 

Verwendet in: ohne Verwendung


[[TransaktionsartHUSST_Type]]

==== Transaktionsart
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[TransportserviceArtKa_Type]]

==== TransportserviceArtKa
Die TransportserviceArt kommt aus der VDV-KA. Die KA-Werte kommen aus dem EN1545: TransportTypeCode 

Verwendet in: ohne Verwendung


[[VerfolgungsTypHUSST_Type]]

==== VerfolgungsTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[VorgangsTypHUSST_Type]]

==== VorgangsTyp
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung



=== technische Datentypen 


[[Betriebszeit_Type]]

==== Betriebszeit
Betriebszeiten dürfen über 24:00 Uhr hinausgehen 

Verwendet in: ohne Verwendung


[[Char]]

==== Char
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[Codierung_Type]]

==== Codierung
Die Codierung entspricht der DB-Codierung 

Verwendet in:
 <<EBEMerkmale_Type,EBEMerkmale>>


[[DateCompact]]

==== DateCompact
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[DateTimeCompact]]

==== DateTimeCompact
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[FLOAT1]]

==== FLOAT1
englische Notation beachten, z. B. 19 Euro = 19.00 Euro 

Verwendet in:
 <<Preis_Type,Preis>>


[[INT1]]

==== INT1
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[INT2]]

==== INT2
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[INT3]]

==== INT3
IMPORTANT: _todo: Doku_

Verwendet in:
 <<KAReferenz_Type,KAReferenz>>


[[INT4]]

==== INT4
IMPORTANT: _todo: Doku_

Verwendet in:
 <<Fahrtverlauf_Type,Fahrtverlauf>>, <<KAReferenz_Type,KAReferenz>>, <<Preis_Type,Preis>>, <<ProdFahrschein_Type,ProdFahrschein>>, <<Tarifprodukt_Type,Tarifprodukt>>, <<Teilrelation_Type,Teilrelation>>, <<Zaehldaten_Type,Zaehldaten>>


[[INT8]]

==== INT8
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung


[[KoordWgs84_Type]]

==== KoordWgs84
IMPORTANT: _todo: Doku_

Verwendet in:
 <<Fahrtverlauf_Type,Fahrtverlauf>>


[[ProjektspezifischAnstattKa_Type]]

==== ProjektspezifischAnstattKa
Definiert einen Typ, der anstatt eines Wertes aus der KA-Enumeration genutzt werden kann. Die KA-Enumerationen definieren Werte zwischen 1 und 255 (INT1). Wenn Buchstaben vorkommen, ist es ein Projektspezifischer Wert. 

Verwendet in: ohne Verwendung


[[Projektspezifisch_Type]]

==== Projektspezifisch
Erlaubt alle Werte, die nicht mit "husst." beginnen.

Verwendet in: ohne Verwendung


[[Waehrung_Type]]

==== Waehrung
Währungscode nach ISO 4217.

Verwendet in:
 <<Betrag_Type,Betrag>>


[[blobString]]

==== blobString
IMPORTANT: _todo: Doku_

Verwendet in: ohne Verwendung



=== Ergebnis Definitionsstand

HUSST Ergebnisdaten Version: 3.7.0 Mehr Informationen: - https://husst.de/ - https://github.com/HUSST-de/HUSST Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/) 