
===  Elemente


[[Bearbeitung_Type]]
==== Bearbeitung

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Bearbeitungsdatum|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Lieferant|
[red]#_todo: Doku_#


Datentyp: string
| |Kommentar|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[DefBundesland_Type]]
==== DefBundeslaender


Definiert einen Gliedstaat (in Deutschland: Bundesland).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Bundesland|

Eindeutige ID des Bundeslands.


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
| |Iso|

Für Deutschland: die letzten zwei Stellen des ISO 3166-2 Codes für Gliedstaaten. DE-BW Baden-Württemberg also: BW DE-BY Bayern also: BY DE-BE Berlin also: BE DE-BB Brandenburg also: BB DE-HB Bremen also: HB DE-HH Hamburg also: HH DE-HE Hessen also: HE DE-MV Mecklenburg-Vorpommern also: MV DE-NI Niedersachsen also: NI DE-NW Nordrhein-Westfalen also: NW DE-RP Rheinland-Pfalz also: RP DE-SL Saarland also: SL DE-SN Sachsen also: SN DE-ST Sachsen-Anhalt also: ST DE-SH Schleswig-Holstein also: SH DE-TH Thüringen also: TH


Datentyp: string
| |Bezeichnung|
Name des Bundeslandes

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|

Dynamische Attribute des Bundeslands.


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[DefWaehrung_Type]]
==== DefWaehrungen

Definiert die Währungen, die in den Versorgungsdaten vorkommen (können). Siehe auch ID_Waehrung_Type bzw. ID_WaehrungHUSST_Type
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Waehrung|

Eindeutige ID der Währung.


Datentyp: <<ID_Waehrung_Type,ID_Waehrung>>
| |Bezeichnung|

ISO-Kurzbezeichnung der Währung, z.B. EUR, USD, CHF,...


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|

Dynamische Attribute der Währung.


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[Feiertage_Type]]
==== Feiertage

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Feiertag|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Bundesland|
[red]#_todo: Doku_#


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
|★ |Datum|
[red]#_todo: Doku_#


Datentyp: <<DateCompact,DateCompact>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[Interpretationen_Type]]
==== Interpretationen


Interpretationen definiert, wie die Daten zu interpretieren sind. Dazu werden Parameter mit einem Schluessel und einem Wert eingetragen.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |Interpretationsschluessel|
[red]#_todo: Doku_#


Datentyp: <<Interpretationsschluessel_Type,Interpretationsschluessel>>
| |Wert|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[Kalender_Type]]
==== Kalender


Beschreibt einen Kalender mit den jeweils zugeordneten Tagesarten.

Ein Betriebstag entspricht einem Kalendertag, kann jedoch einen vom Kalenderdatum abweichenden Tagesanfang und ein abweichendes Tagesende haben. Diese Zeitpunkte werden nicht explizit im Kalender festgelegt.

Benötigt das System eine Tagesart (ID_Tagesart), wird diese vorrangig aus den Einträgen des Kalenders ermittelt. Existiert für einen Kalendertag kein Eintrag, kann das System anhand von Tagesartmerkmalelementen eine Standard-Tagesart bestimmen z.B. aus dem Wochentag oder allgemein berechenbaren Feiertagen.

Siehe auch:

* Tagesmerkmale_Type

* Tagesmerkmalelemente_Type

* Tagesartmerkmalelemente_Type

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstag|

Datum des Betriebstages


Datentyp: <<DateCompact,DateCompact>>
|★ |ID_Betriebstagesart|

Kennung der Tagesart, die für diesen Betriebstag gilt.


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Optionale externe Referenz, um den Kalendereintrag über einen nicht-numerischen Schlüssel eindeutig zu identifizieren.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[TagesartMerkmalElemente_Type]]
==== TagesartMerkmalElemente


Verknüpft eine Betriebstagesart mit einer Menge von TagesmerkmalElementen. Dadurch wird beschrieben, welche Merkmalsausprägungen für diese Tagesart gelten.

Diese Zuordnung hat in der Regel rein beschreibenden Charakter. Eine funktionale Bedeutung ist nur für Elemente des Tagesmerkmals "husstDefaultermittlung" definiert (siehe Typ Tagesmerkmale_Type).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_TagesartMerkmalElement|

Kennung des Tagesartmerkmalelements


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstagesart|

Kennung der Betriebstagesart, zu der das Merkmalselement gehört.


Datentyp: <<INT4,INT4>>
|★ |ID_TagesmerkmalElement|

Kennung des zugeordneten Tagesmerkmalelements.


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Optionale externe Referenz, um das Element über einen beliebigen, ggf. nicht-numerischen Schlüssel eindeutig zu identifizieren.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[Tagesarten_Type]]
==== Tagesarten


Beschreibt die logische Tagesart eines Kalendertages für das vorliegende System.

Jedem Kalendertag ist genau eine Tagesart zugeordnet. Die Tagesart charakterisiert den Tag in funktionaler Hinsicht, z.B. als Werktag, Feiertag oder spezieller Betriebstag.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstagesart|

Kennung der Tagesart.


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Informationen, welche Bedeutung diese Kennung hat.


Datentyp: string
| |ReferenzExtern|

Optionale externe Referenz zur Identifikation der Tagesart über einen nicht-numerischen Schlüssel.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[TagesmerkmalElemente_Type]]
==== TagesmerkmalElemente


Beschreibt ein einzelnes Element innerhalb eines Tagesmerkmals. Jedes Tagesmerkmal kann eine Liste unterschiedlicher Elemente besitzen, die jeweils einen bestimmten Wert oder eine Ausprägung des Merkmals darstellen. Siehe auch Definition des Typs Tagesmerkmale_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_TagesmerkmalElement|

Kennung des Tagesmerkmalelements


Datentyp: <<INT4,INT4>>
|★ |ID_Tagesmerkmal|

Verweis auf das Tagesmerkmal, zu dem dieses Element gehört.


Datentyp: <<INT4,INT4>>
|★ |Bezeichnung|

Eindeutiger Bezeichner des Tagesartmerkmalelements.


Datentyp: <<String250,String250>>
| |ReferenzExtern|

Optionale externe Referenz, um das Element über einen beliebigen, ggf. nicht-numerischen Schlüssel eindeutig zu identifizieren.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[Tagesmerkmale_Type]]
==== Tagesmerkmale


Ein Tagesmerkmal muss so gestaltet sein, dass an jedem Betriebstag (Kalendertag aber ggf. abweichende Start-/Ende Uhrzeit) aus der Liste der Mermalelemente genau ein Element gültig ist.

Für eine Tagesart können mehrere Elemente aus einer Liste eines Tagesmerkmales definiert sein.

Beispiele: Tagesmerkmal:"Wochentag=("Mo","Di","Mi","Do","Fr","Sa","So") Tagesmerkmal:"Ferien"=("Ja","Nein")

Die Husst Schnittstelle definiert ein Default-Tagesmerkmal mit dem vorgegebenen Bezeichner "husstDefaultermittlung"=("Mo","Di","Mi","Do","Fr","Sa","So","Mo/Feiertag","Di/Feiertag","Mi/Feiertag","Do/Feiertag","Fr/Feiertag","Sa/Feiertag","So/Feiertag") Mit diesem Tagesmerkmal können Tagesarten ausgezeichnet werden, die dann gelten sollen, wenn kein Kalendereintrag gefunden wird. Das Vertriebssystem ermittelt dann aufgrund des Wochentages und der allgemein berechenbaren Feiertage (Einige sind natürlich nicht eindeutig ermittelbar) das husstDefault-Tagesmerkmal und sucht eine Tagesart, für die dieses Merkmal gesetzt ist. Maximal vierzehn Tagesarten können darüber unterschieden werden und keine zwei Tagesarten dürfen eines der Merkmale gemeinsam haben).

Das Tagesmerkmal "husstDefaultermittlung" muss nicht definiert werden. Wenn eine Datenmenge das Merkmal definiert, darf es nur mit der hier definierten Intension verwendet werden.

Alle anderen Tagesartmerkmal haben lediglich deklarativen Charakter. Eine vorgegebene Behandlung oder Auswertung ist über den HUSST-Standard nicht definiert.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tagesmerkmal|
Kennung des Tagesmerkmals

Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Frei wählbarer Name des Tagesmerkmals. Bezeichnungen mit dem Präfix "husst" sind reserviert. Die Bezeichnung "husstDefaultermittlung" besitzt eine festgelegte Bedeutung (siehe Beschreibung des Typs Tagesmerkmale_Type).


Datentyp: string
| |ReferenzExtern|

Optionale externe Referenz, um das Merkmal über einen beliebigen, ggf. nicht-numerischen Schlüssel eindeutig zu identifizieren.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>

[[Unternehmen_Type]]
==== Unternehmen

Unternehmen definieren organisatorische Einheiten, die in dem Vertriebssystem eine Rolle übernehmen. Wenn sie die Rolle eines Mandanten im System übernehmen, kann dies über ihre Mandant Eigenschaft angezeigt werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Unternehmen|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |BezeichnungKurz|
[red]#_todo: Doku_#


Datentyp: string
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |Mandant|

True, wenn das Unternehmen als Mandant im System geführt wird.


Datentyp: boolean
| |ReferenzExtern|

Dient als Referenz um Unternehmen über eine nicht numerische Referenz ggf. auch bezogen auf Drittsysteme identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[Updateinfo_Type]]
==== Updateinfo


Dokumentation von Updatevorgängen über der zunächst generierten Datenmenge

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Updatetime|

Zeitpunkt des Updatevorgangs


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Filename|

Filename des Updatescripts oder Bezeichnung des Updatevorgangs


Datentyp: string
| |Purpose|

Hinweis zum Zweck des Updatevorgangs


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[VersionInhalt_Type]]
==== VersionInhalt


Enthält die Versionsinformationen einer kompletten HUSST-Datenlieferung. Dient als Metainformation, um Lieferungen eindeutig zu identifizieren und voneinander abzugrenzen. Über die Registrierung von DatenversionInhalt können Verkaufs- oder Versorgungsdaten einer konkreten Datenlieferung zugeordnet werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |DatenversionInhalt|

Eindeutige Kennung der Datenversion für die gesamte Lieferung. Darf innerhalb einer Datenlieferung nur einmal vorkommen.


Datentyp: string
| |Testdaten|

Kennzeichnung, ob es sich bei der Lieferung um Testdaten handelt (true/false).


Datentyp: boolean
|★ |Erstellungsdatum|

Datum und Uhrzeit, zu dem die Datenlieferung erzeugt wurde.


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Lieferant|

Name oder Kennung des Lieferanten, der die Daten bereitstellt.


Datentyp: string
| |Kommentar|

Freitextfeld für zusätzliche Hinweise oder Bemerkungen zur Datenlieferung.


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[VersionStruktur_Type]]
==== VersionStruktur

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |VersionMajor|

Hauptversionsnummer (Major). Erhöht sich bei nicht abwärtskompatiblen Änderungen zur vorherigen Version.


Datentyp: <<INT4,INT4>>
|★ |VersionMinor|

Nebenversion (Minor). Erhöht sich bei abwärtskompatiblen Erweiterungen oder funktionalen Anpassungen.


Datentyp: <<INT4,INT4>>
|★ |VersionPatch|

Patch-Level. Erhöht sich bei abwärtskompatiblen Fehlerkorrekturen (Bugfixes).


Datentyp: <<INT4,INT4>>
| |Status|

Aktueller Entwicklungs- oder Veröffentlichungsstatus der Version. Mögliche Werte siehe VersionStatus_Type.


Datentyp: <<VersionStatus_Type,VersionStatus>>
| |Aenderungsdatum|

Datum der letzten Änderung dieser Version im Format JJJJ-MM-TT.


Datentyp: <<DateCompact,DateCompact>>
| |Aenderungsautor|

Name oder Organisation des Autors, der die letzte Änderung vorgenommen hat.


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[Zeitraeume_Type]]
==== Zeitraeume


Beschreibt einen Gültigkeitszeitraum, in welchem eine bestimmte Datenmenge verwendet werden darf.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
| |ZeitraumVon|

Startdatum und -uhrzeit des Zeitraums (einschließlich).


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |ZeitraumBis|

Enddatum und -uhrzeit des Zeitraums (einschließlich).


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |DatenversionZeitraum|

Eindeutiger Schlüssel für die Datenmenge, die in dem Zeitraum enthalten ist, bezogen auf die DatenversionInhalt des Elements VersionInhalt.


Datentyp: string
|★ |HauptZeitraumNr|

Kennzeichnet den Hauptzeitraum, zu dem dieser Zeitraum gehört. Alle Zeiträume mit gleicher Hauptzeitraumnummer bilden einen gemeinsamen Datenraum, in dem alle Referenzen (ID_xx) die gleiche Bedeutung haben.


Datentyp: <<INT4,INT4>>
|★ |SubZeitraumNr|

Laufende Nummerierung der Subzeiträume innerhalb eines Hauptzeitraums, beginnend bei 1.


Datentyp: <<INT4,INT4>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

[[Zeitraumoptionen_Type]]
==== Zeitraumoptionen


ordnet einem Zeitraum zusätzliche Optionen zu

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |Option|
Schlüsselstring der Option

Datentyp: <<String250,String250>>
| |Wert|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<OePVTarifDB_Type,OePVTarifDB>>, <<husstPersonal_Type,husstPersonal>>

=== technische Enumerationen 


[[DynAttributTyp_Type]]

==== DynAttributTyp

Die Werte eines dynamischen Attributes werden als String gespeichert. Der DynAttributTyp gibt an, wie der Wert zu interpretieren ist.


Verwendet in:
 <<DynAttributDef_Type,DynAttributDef>>


[[ID_BundeslandHUSST_Type]]

==== ID_Bundesland

Die HUSST definiert ID_Bundesland kleiner 1000. Aktuell definiert die HUSST ID_Bundesland für die deutschen Bundesländern analog der "Liste deutscher Bundesländer" wie sie für den Amtlicher Regionalschlüssel (ARS) bzw. dem darin enthaltenen Amtlichen Gemeindeschlüssel (AGS) definiert sind.

Quelle: 02Bundeslaender_mit_Hauptstaedten.xslx - Statistisches Bundesamt (Destatis), 2023 https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/Standardtabellen/02_BundeslaenderVorjahr.html

Dieser 2-stellige Länderschlüssel wird u.a. auch in der DHID/Global-ID (=Landeskennzeichen(LK)) verwendet und damit im deutschlandweiten zentralen Haltestellenverzeichnis (zHV)

* siehe auch VDV-Schrift 432: https://www.vdv.de/downloads/3855/432SDS/forced.


Verwendet in: ohne Verwendung


[[ID_WaehrungHUSST_Type]]

==== ID_Waehrung

Die HUSST definiert Waehrungs-ID kleiner 1000. Als ID-Währung ist der dreistellige Zifferncode nach ISO 4217 zu verwenden. Außer für den EUR. Hier ist in der HUSST die 999 definiert (ISO Standard wäre 978).


Verwendet in: ohne Verwendung


[[InterpretationsschluesselHUSST_Type]]

==== Interpretationsschluessel

Die HUSST definiert Interpretationsschluessel die mit 'husst.' beginnen.


Verwendet in: ohne Verwendung


[[VersionStatus_Type]]

==== VersionStatus

Gibt den aktuellen Status einer Version an.


Verwendet in:
 <<VersionStruktur_Type,VersionStruktur>>



=== technische Datentypen 


[[Char]]

==== Char

Der Datentyp char speichert ein einzelnes Zeichen.


Verwendet in: ohne Verwendung


[[DateCompact]]

==== DateCompact

Datum nach dem ISO 8601 Standard. Der gültige Bereich ist eingeschränkt:

* 1990-01-01 - 2117-12-31


Verwendet in:
 <<Feiertage_Type,Feiertage>>, <<Kalender_Type,Kalender>>, <<VersionStruktur_Type,VersionStruktur>>


[[DateTimeCompact]]

==== DateTimeCompact

Datum und Urzeit nach dem ISO 8601 Standard. Der gültige Bereich ist eingeschränkt:

* 1990-01-01T00:00:00Z - 2117-12-31T23:59:58Z


Verwendet in:
 <<Bearbeitung_Type,Bearbeitung>>, <<PersonalIdentobjekte_Type,PersonalIdentobjekte>>, <<Personal_Type,Personal>>, <<Tarifgebiete_Type,Tarifgebiete>>, <<Updateinfo_Type,Updateinfo>>, <<VersionInhalt_Type,VersionInhalt>>, <<Zeitraeume_Type,Zeitraeume>>


[[DauerMinuten]]

==== DauerMinuten

Definiert eine Dauer. Bei der Interpretation wird auf ganze Minuten geachtet. Sekunden-Angaben werden ignoriert.


Verwendet in:
 <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>


[[FLOAT1]]

==== FLOAT1

Dezimalwert zwischen 0 und 100 in englischer Notation (Punkt als Dezimaltrennzeichen).


Verwendet in:
 <<Mwst_Type,Mwst>>


[[ID_ProjektspezifischBitfeld_Type]]

==== ID_ProjektspezifischBitfeld

Frei definierbare IDs für Def-Elemente auf Bitfeld Basis beginnend mit 1024. Im frei definierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/blob/master/Version%203/README.md


Verwendet in: ohne Verwendung


[[ID_Projektspezifisch_Type]]

==== ID_Projektspezifisch

Frei definierbare IDs für Def-Elemente beginnend mit 1000. Im frei definierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/blob/master/Version%203/README.md


Verwendet in: ohne Verwendung


[[INT1]]

==== INT1

Entspricht einer Ganzzahl mit dem Wertebereich von einem Byte (0 - 255).


Verwendet in:
 <<Preise_Type,Preise>>, <<Preisstufen_Type,Preisstufen>>


[[INT2]]

==== INT2

Entspricht einer Ganzzahl mit dem Wertebereich von zwei Bytes (0 - 65535).


Verwendet in:
 <<Preise_Type,Preise>>, <<Sorten_Type,Sorten>>


[[INT4]]

==== INT4

Entspricht einer Ganzzahl mit dem Wertebereich von vier Bytes (0 - 4294967295).


Verwendet in: 91 Elementen


[[INT8]]

==== INT8

Entspricht einer Ganzzahl mit dem Wertebereich von acht Bytes (0 - 18446744073709551615).


Verwendet in: ohne Verwendung


[[InterpretationsschluesselProjektspezifisch_Type]]

==== InterpretationsschluesselProjektspezifisch

Für projektspezifische Zwecke oder zum Test können eigene Namen für Interpretationsschluessel verwendet werden.

Namensregeln: Eigene Namen .. .. dürfen nicht mit 'husst.' beginnen, .. dürfen nicht mit einer Zahl beginnen, .. müssen mindestens ein Zeichen [a-ZöäüÖÄÜß\-0-9] je Wort enthalten .. müssen mit einem Wort beginnen, .. dürfen mehrere Wörter mit '.' oder '-' trennen, .. dürfen nicht mit einem Punkt enden.


Verwendet in: ohne Verwendung


[[KoordWgs84_Type]]

==== KoordWgs84

Koordinate im WGS 84-Referenzsystem als Fließkommazahl (Dezimalgrad). Dieser Wert kann zur Angabe von Breiten- oder Längengraden genutzt werden.


Verwendet in:
 <<Ortspunkte_Type,Ortspunkte>>


[[Lang_Type]]

==== Lang

Stellt zwei buchstabige Sprachcodes gemäß ISO 639-1:2002 dar.


Verwendet in:
 <<DynAttributWert_Type,DynAttributWert>>, <<Sprachtexte_Type,Sprachtexte>>


[[String250]]

==== String250

Der Datentyp String250 enthält eine Zeichenfolge mit maximal 250 Zeichen.


Verwendet in:
 <<TagesmerkmalElemente_Type,TagesmerkmalElemente>>, <<Zeitraumoptionen_Type,Zeitraumoptionen>>


[[UhrzeitMinuten]]

==== UhrzeitMinuten

Definiert den Zeitpunkt eines Tages. Bei der Interpretation wird auf ganze Minuten geachtet. Sekunden-Angaben werden ignoriert.


Verwendet in:
 <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>


[[blobString]]

==== blobString

Der Datentyp blobString ist eine Zeichenkette, die nur aus den ASCII Zeichen zwischen U+0020 (Leerzeichen) und U+00FE (þ) sowie dem Eurozeichen (U+20AC) und dem Gedankenstrich (U+2013) bestehen darf.


Verwendet in:
 <<DynAttributWert_Type,DynAttributWert>>, <<RaeumlicheGueltigkeit_Type,RaeumlicheGueltigkeit>>, <<Sorten_Type,Sorten>>



===  Definitionsstand


HUSST Versorgungsdaten - Schema: Basis Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
