
=== Basis Elemente


[[Bearbeitung_Type]]
==== Bearbeitung

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |Bearbeitungsdatum|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Lieferant|
[red]#_todo: Doku_#


Datentyp: string
| |Kommentar|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente

[[DefBundesland_Type]]
==== DefBundeslaender


Definiert einen Gliedstaat (in Deutschland: Bundesland).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Bundesland|
[red]#_todo: Doku_#


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
| |Iso|

Für Deutschland: die letzten zwei Stellen des ISO 3166-2 Codes für Gliedstaaten. DE-BW Baden-Württemberg also: BW DE-BY Bayern also: BY DE-BE Berlin also: BE DE-BB Brandenburg also: BB DE-HB Bremen also: HB DE-HH Hamburg also: HH DE-HE Hessen also: HE DE-MV Mecklenburg-Vorpommern also: MV DE-NI Niedersachsen also: NI DE-NW Nordrhein-Westfalen also: NW DE-RP Rheinland-Pfalz also: RP DE-SL Saarland also: SL DE-SN Sachsen also: SN DE-ST Sachsen-Anhalt also: ST DE-SH Schleswig-Holstein also: SH DE-TH Thüringen also: TH


Datentyp: string
| |Bezeichnung|
Name des Bundeslandes

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefWaehrung_Type]]
==== DefWaehrungen

Definiert die Währungen, die in den Versorgungsdaten vorkommen (können). Siehe auch ID_Waehrung_Type bzw. ID_WaehrungHUSST_Type
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Waehrung|
[red]#_todo: Doku_#


Datentyp: <<ID_Waehrung_Type,ID_Waehrung>>
| |Bezeichnung|

ISO-Kurzbezeichnung z.B. EUR, USD, CHF,...


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Feiertage_Type]]
==== Feiertage

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Feiertag|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Bundesland|
[red]#_todo: Doku_#


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
|★ |Datum|
[red]#_todo: Doku_#


Datentyp: <<DateCompact,DateCompact>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Interpretationen_Type]]
==== Interpretationen


Interpretationen definiert, wie die Daten zu interpretieren sind. Dazu werden Parameter mit einem Schluessel und einem Wert eingetragen.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |Interpretationsschluessel|
[red]#_todo: Doku_#


Datentyp: <<Interpretationsschluessel_Type,Interpretationsschluessel>>
| |Wert|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Kalender_Type]]
==== Kalender


Kalender mit zugeordneten Tagesarten. Ein Betriebstag ist ein Kalendertag, kann aber abweichende Tagesanfang und -ende haben. Tagesanfang und -ende werden nicht explizit im Kalender definiert.

Benötigt das System für eine Funktionalität eine ID_Tagesart, dann ermittelt es diese aus dem Kalender. Ist für einen konkreten Kalendertag kein Eintrag im Kalender vorhanden, kann das System über geeignete Tagesartmerkmalelemente eine Default Tagesart aufgrund des Wochentages und allgemein berechenbarer Feiertage ermittelt werden.

Siehe auch Tagesmerkmale_Type, Tagesmerkmalelemente_Type und Tagsartmerkmalelemente_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstag|
Datum des Betriebstages

Datentyp: <<DateCompact,DateCompact>>
|★ |ID_Betriebstagesart|

Tagesart des Betriebstages


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[TagesartMerkmalElemente_Type]]
==== TagesartMerkmalElemente


TagesartMerkmalElemente vernknüpfen eine Tagesart mit einer Menge von Tagesmerkmal-Elementen.

Damit beschreibt die Datenmenge lediglich formal die Intension der Tagesart. Lediglich für die Elemente des Tagesmerkmals "husstDefaultermittlung" ist eine funktionale Bedeutung definiert (siehe Tagesmerkmale_Type).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_TagesartMerkmalElement|

Kennung des Tagesartmerkmalelements


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstagesart|

Kennung der ID_Betriebstagesart


Datentyp: <<INT4,INT4>>
|★ |ID_TagesmerkmalElement|

Kennung des Tagesmerkmalelements


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Tagesarten_Type]]
==== Tagesarten


Eine Tagesart beschreibt den logischen Charakter eines Tages soweit der für das vorliegende System benötigt wird. Einem Kalendertag ist genau eine Tagesart zugeordnet.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Betriebstagesart|
Kennung der Tagesart

Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Informationen, welche Bedeutung diese Kennung hat.


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[TagesmerkmalElemente_Type]]
==== TagesmerkmalElemente


Jedes Tagesmerkmal definiert eine Liste mit unterschiedlichen Tagesmerkmal Elementen. Siehe auch Tagesmerkmale_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_TagesmerkmalElement|

Kennung des Tagesmerkmalelements


Datentyp: <<INT4,INT4>>
|★ |ID_Tagesmerkmal|
Kennung des Tagesmerkmals

Datentyp: <<INT4,INT4>>
|★ |Bezeichnung|
Eindeutiger Bezeichner des Tagesartmerkmalelements

Datentyp: <<String250,String250>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Tagesmerkmale_Type]]
==== Tagesmerkmale


Ein Tagesmerkmal muss so gestaltet sein, dass an jedem Betriebstag (Kalendertag aber ggf. abweichende Start-/Ende Uhrzeit) aus der Liste der Mermalelemente genau ein Element gültig ist.

Für eine Tagesart können mehrere Elemente aus einer Liste eines Tagesmerkmales definiert sein.

Beispiele: Tagesmerkmal:"Wochentag=("Mo","Di","Mi","Do","Fr","Sa","So") Tagesmerkmal:"Ferien"=("Ja","Nein")

Die Husst Schnittstelle definiert ein Default-Tagesmerkmal mit dem vorgegebenen Bezeichner "husstDefaultermittlung"=("Mo","Di","Mi","Do","Fr","Sa","So","Mo/Feiertag","Di/Feiertag","Mi/Feiertag","Do/Feiertag","Fr/Feiertag","Sa/Feiertag","So/Feiertag") Mit diesem Tagesmerkmal können Tagesarten ausgezeichnet werden, die dann gelten sollen, wenn kein Kalendereintrag gefunden wird. Das Vertriebssystem ermittelt dann aufgrund des Wochentages und der allgemein berechenbaren Feiertage (Einige sind natürlich nicht eindeutig ermittelbar) das husstDefault-Tagesmerkmal und sucht eine Tagesart, für die dieses Merkmal gesetzt ist. Maximal vierzehn Tagesarten können darüber unterschieden werden und keine zwei Tagesarten dürfen eines der Merkmale gemeinsam haben).

Das Tagesmerkmal "husstDefaultermittlung" muss nicht definiert werden. Wenn eine Datenmenge das Merkmal definiert, darf es nur mit der hier definierten Intension verwendet werden.

Alle anderen Tagesartmerkmal haben lediglich deklarativen Charakter. Eine vorgegebene Behandlung oder Auswertung ist über den HUSST-Standard nicht definiert.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tagesmerkmal|
Kennung des Tagesmerkmals

Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Bezeichnungen mit dem Prefix "husst" sind reserviert.

Die Bezeichnung "husstDefaultermittlung" hat eine definiert Bedeutung (Siehe Tagesmerkmale_Type). Ansonsten kann die Bezeichnung frei vergeben werden.


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Unternehmen_Type]]
==== Unternehmen

Unternehmen definieren organisatorische Einheiten, die in dem Vertriebssystem eine Rolle übernehmen. Wenn sie die Rolle eines Mandanten im System übernehmen, kann dies über ihre Mandant Eigenschaft angezeigt werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Unternehmen|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |BezeichnungKurz|
[red]#_todo: Doku_#


Datentyp: string
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |Mandant|

True, wenn das Unternehmen als Mandant im System geführt wird.


Datentyp: boolean
| |ReferenzExtern|

Dient als Referenz um Unternehmen über eine nicht numerische Referenz ggf. auch bezogen auf Drittsysteme identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Updateinfo_Type]]
==== Updateinfo


Dokumentation von Updatevorgängen über der zunächst generierten Datenmenge

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Updatetime|

Zeitpunkt des Updatevorgangs


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Filename|

Filename des Updatescripts oder Bezeichnung des Updatevorgangs


Datentyp: string
| |Purpose|

Hinweis zum Zweck des Updatevorgangs


Datentyp: string
|=======================
  ★  Pflichtelemente

[[VersionInhalt_Type]]
==== VersionInhalt

Eine Datenlieferung enthält einen Datensatz VersionInhalt. Dieser definiert, welche Datenversion die komplette Husstlieferung besitzt. Dieses ist eine Metainformation um diese Lieferung einfach von anderen zu unterscheiden. Über die Registrierung Der DatenversionInhalt können Verkaufsdaten ihrer exakten Versorgungsdatenlieferung zugewordnet werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |DatenversionInhalt|

Eindeutige Versionskennung für die gesamte Datenlieferung. In der gesamten Datenlieferung darf dieses Element nur einmal vorkommen.


Datentyp: string
| |Testdaten|
[red]#_todo: Doku_#


Datentyp: boolean
|★ |Erstellungsdatum|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |Lieferant|
[red]#_todo: Doku_#


Datentyp: string
| |Kommentar|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente

[[VersionStruktur_Type]]
==== VersionStruktur

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |VersionMajor|
VersionMajor muss sich immer bei Inkompatibilitäten zur Vorgängerversion ändern.

Datentyp: <<INT4,INT4>>
|★ |VersionMinor|
VersionMinor zählt kompatible Anpassungen.

Datentyp: <<INT4,INT4>>
|★ |VersionPatch|
VersionPatch zählt abwärtskompatible Bugfixes.

Datentyp: <<INT4,INT4>>
| |Status|
[red]#_todo: Doku_#


Datentyp: <<VersionStatus_Type,VersionStatus>>
| |Aenderungsdatum|
[red]#_todo: Doku_#


Datentyp: <<DateCompact,DateCompact>>
| |Aenderungsautor|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Zeitraeume_Type]]
==== Zeitraeume


Gültigkeitszeitraum

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
| |ZeitraumVon|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |ZeitraumBis|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
|★ |DatenversionZeitraum|

Eindeutiger Schlüssel für die Datenmenge, die in dem Zeitraum enthalten ist, bezogen auf die DatenversionInhalt des Elements VersionInhalt.


Datentyp: string
|★ |HauptZeitraumNr|

Alle Zeiträume mit dem gleichen Hauptzeitraum bilden einen gemeinsamen Datenraum, in dem alle Refrenzen ID_xx die gleiche Bedeutung haben und auflösbar sind. Sind zu einem Zeitpunkt mehrere Zeiträume mit unterschiedlichen Hauptzeitraumnummern gültig, hat der mit der höheren Hauptzeitraumnummer Vorrang.


Datentyp: <<INT4,INT4>>
|★ |SubZeitraumNr|

Die Subzeitraumnummer ist innerhalb einer Hauptzeitraumnummer ununterbrochen, aufsteigend nummeriert, beginnend mit 1. Bei gleichzeitiger Gültigkeit mehrere Subzeiträume hat die höhere SubZeitraumNr Vorrang vor der kleineren.


Datentyp: <<INT4,INT4>>
|=======================
  ★  Pflichtelemente

[[Zeitraumoptionen_Type]]
==== Zeitraumoptionen


ordnet einem Zeitraum zusätzliche Optionen zu

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |Option|
Schlüsselstring der Option

Datentyp: <<String250,String250>>
| |Wert|
[red]#_todo: Doku_#


Datentyp: string
|=======================
  ★  Pflichtelemente

=== Basis Enumerationen 


[[ID_BundeslandHUSST_Type]]

[[ID_Bundesland_Type]]

==== ID_Bundesland

Die HUSST definiert ID_Bundesland kleiner 1000. Aktuell definiert die HUSST ID_Bundesland für die deutschen Bundesländern analog der "Liste deutscher Bundesländer" wie sie für den Amtlicher Regionalschlüssel (ARS)  bzw. dem darin enthaltenen Amtlichen Gemeindeschlüssel (AGS) definiert sind. 

Quelle: 02Bundeslaender_mit_Hauptstaedten.xslx - Statistisches Bundesamt (Destatis), 2023 https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/Standardtabellen/02_BundeslaenderVorjahr.html

Dieser 2-stellige Länderschlüssel wird u.a. auch in der DHID/Global-ID (=Landeskennzeichen(LK))  verwendet und damit im deutschlandweiten zentralen Haltestellenverzeichnis (zHV)

* siehe auch VDV-Schrift 432: https://www.vdv.de/downloads/3855/432SDS/forced. 

Die ID_Bundesland ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
unbekannt
|1|
Schleswig-Holstein (SH)
|2|
Hamburg (HH)
|3|
Niedersachsen (NI)
|4|
Bremen (HB)
|5|
Nordrhein-Westfalen (NW)
|6|
Hessen (HE)
|7|
Rheinland-Pfalz (RP)
|8|
Baden-Württemberg (BW)
|9|
Bayern (BY)
|10|
Saarland (SL)
|11|
Berlin (BE)
|12|
Brandenburg (BB)
|13|
Mecklenburg-Vorpommern (MV)
|14|
Sachsen (SN)
|15|
Sachsen-Anhalt (ST)
|16|
Thüringen (TH)
|=======================


Verwendet in:

* <<DefBundesland_Type,DefBundesland>>
* <<Feiertage_Type,Feiertage>>
* <<Ortspunkte_Type,Ortspunkte>>
* <<Tarifrelevantepunkte_Type,Tarifrelevantepunkte>>


[[ID_WaehrungHUSST_Type]]

[[ID_Waehrung_Type]]

==== ID_Waehrung

Die HUSST definiert Waehrungs-ID kleiner 1000 Als ID-Währung ist der dreistellige Zifferncode nach ISO 4217 zu verwenden. Außer für den EUR. Hier ist in der HUSST die 999 definiert (ISO Standard wäre 978). 

Die ID_Waehrung ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|999|
EUR
|280|
DEM
|784|
AED
|971|
AFN
|008|
ALL
|051|
AMD
|532|
ANG
|973|
AOA
|032|
ARS
|036|
AUD
|533|
AWG
|944|
AZN
|977|
BAM
|052|
BBD
|050|
BDT
|975|
BGN
|048|
BHD
|108|
BIF
|060|
BMD
|096|
BND
|068|
BOB
|984|
BOV
|986|
BRL
|044|
BSD
|064|
BTN
|072|
BWP
|933|
BYN
|084|
BZD
|124|
CAD
|976|
CDF
|947|
CHE
|756|
CHF
|948|
CHW
|990|
CLF
|152|
CLP
|156|
CNY
|170|
COP
|970|
COU
|188|
CRC
|931|
CUC
|192|
CUP
|132|
CVE
|203|
CZK
|262|
DJF
|208|
DKK
|214|
DOP
|012|
DZD
|818|
EGP
|232|
ERN
|230|
ETB
|242|
FJD
|238|
FKP
|826|
GBP
|981|
GEL
|936|
GHS
|292|
GIP
|270|
GMD
|324|
GNF
|320|
GTQ
|328|
GYD
|344|
HKD
|340|
HNL
|332|
HTG
|348|
HUF
|360|
IDR
|376|
ILS
|356|
INR
|368|
IQD
|364|
IRR
|352|
ISK
|388|
JMD
|400|
JOD
|392|
JPY
|404|
KES
|417|
KGS
|116|
KHR
|174|
KMF
|408|
KPW
|410|
KRW
|414|
KWD
|136|
KYD
|398|
KZT
|418|
LAK
|422|
LBP
|144|
LKR
|430|
LRD
|426|
LSL
|434|
LYD
|504|
MAD
|498|
MDL
|969|
MGA
|807|
MKD
|104|
MMK
|496|
MNT
|446|
MOP
|929|
MRU
|480|
MUR
|462|
MVR
|454|
MWK
|484|
MXN
|979|
MXV
|458|
MYR
|943|
MZN
|516|
NAD
|566|
NGN
|558|
NIO
|578|
NOK
|524|
NPR
|554|
NZD
|512|
OMR
|590|
PAB
|604|
PEN
|598|
PGK
|608|
PHP
|586|
PKR
|985|
PLN
|600|
PYG
|634|
QAR
|946|
RON
|941|
RSD
|643|
RUB
|646|
RWF
|682|
SAR
|090|
SBD
|690|
SCR
|938|
SDG
|752|
SEK
|702|
SGD
|654|
SHP
|925|
SLE
|706|
SOS
|968|
SRD
|728|
SSP
|930|
STN
|222|
SVC
|760|
SYP
|748|
SZL
|764|
THB
|972|
TJS
|934|
TMT
|788|
TND
|776|
TOP
|949|
TRY
|780|
TTD
|901|
TWD
|834|
TZS
|980|
UAH
|800|
UGX
|840|
USD
|997|
USN
|940|
UYI
|858|
UYU
|927|
UYW
|860|
UZS
|926|
VED
|928|
VES
|704|
VND
|548|
VUV
|882|
WST
|950|
XAF
|961|
XAG
|959|
XAU
|955|
XBA
|956|
XBB
|957|
XBC
|958|
XBD
|951|
XCD
|960|
XDR
|952|
XOF
|964|
XPD
|953|
XPF
|962|
XPT
|994|
XSU
|963|
XTS
|965|
XUA
|886|
YER
|710|
ZAR
|967|
ZMW
|932|
ZWL
|=======================


Verwendet in:

* <<DefWaehrung_Type,DefWaehrung>>
* <<Preisspalten_Type,Preisspalten>>


[[InterpretationsschluesselHUSST_Type]]

[[Interpretationsschluessel_Type]]

==== Interpretationsschluessel

Die HUSST definiert Interpretationsschluessel die mit 'husst.' beginnen. 
Die Interpretationsschluessel sind entweder von der HUSST vordefiniert oder eine im Projekt vereinbarter string.
[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|husst.Relationen.Matrixtyp|

Definiert, wie die Relationenmatrix zu interpretieren ist. mögliche Matrixtypen sind "Vollmatrix" : Jede Verbindung ist in jeder erlaubten Richtung in der Relationenmatrix hinterlegt. "Halbmatrix" : Zu jeder möglichen Verbindung ist nur die Variante ID_RelcodeStart größer gleich ID_RelcodeZiel hinterlegt, die umgekehrte Richtung ist dazu identisch. "erweitert Halbmatrix" : Die Relationen werden im Regelfall mit ID_RelcodeStart größer gleich ID_RelcodeZiel definiert, es kann aber auch die Rückrichtung definiert sein, dann muss das Flag GegenrichtungLiegtVor auf true gesetzt werden.

|husst.Relationen.Suchstrategie|

Definiert, wie die Ermittlung einer Verkaufsverbindung erfolgen soll. Ist der Schlüssel nicht definiert, wird über ID_RelcodeStart und ID_RelcodeZiel in den Relationen nach einer oder mehreren Verbindungen gesucht. mögliche Suchstrategien sind "NbHstSuche + RCSuche" : Suchstrategie für die Relationsermittlung: Nachbarhaltestellensuche zusätzlich zur Relationscodesuche.

|husst.Teilrelationen.Matrixpreisbildung|

Definiert, wie die Preisbildung aus den Teilrelationen erfolgen soll. Ist der Schlüssel nicht definiert, wird der Preis anhand der ID_Preisstufe der ersten Teilrelation ermittelt. mögliche Matrixpreisbildungen sind "Anstoß_CH" : Wenn nur eine Teilrelation exisitiert, dann wie beim Standardfall. Sonst: Preisstufenattribute werden von der Preisstufe der ersten Teilrelation verwendet. Der Preis wird nach einer eigenen CH-Logik aus den weiteren Teilrelationen berechnet.

|=======================


Verwendet in:

* <<Interpretationen_Type,Interpretationen>>


[[VersionStatus_Type]]


==== VersionStatus
IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|Release|
[red]#_todo: Doku_#

|work in progress|
[red]#_todo: Doku_#

|stabil|
[red]#_todo: Doku_#

|in Arbeit|
[red]#_todo: Doku_#

|=======================


Verwendet in:

* <<VersionStruktur_Type,VersionStruktur>>



=== Basis Datentypen 


[[DauerMinuten]]


==== DauerMinuten

Definiert eine Dauer. Bei der Interpretation wird auf ganze Minuten geachtet. Sekunden-Angaben werden ignoriert. In der Datenbankabbildung wird ein Integer für eine Anzahl an Minuten empfohlen.


Verwendet in:

* <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>


[[ID_ProjektspezifischBitfeld_Type]]


==== ID_ProjektspezifischBitfeld

Frei definierbare IDs für Def-Elemente auf Bitfeld Basis beginnen mit 1024

[[ID_Projektspezifisch_Type]]


==== ID_Projektspezifisch

Frei definierbare IDs für Def-Elemente beginnen mit 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0


Verwendet in:

* <<DefBundesland_Type,DefBundesland>>
* <<DefWaehrung_Type,DefWaehrung>>
* <<Feiertage_Type,Feiertage>>
* <<Ortspunkte_Type,Ortspunkte>>
* <<Preisspalten_Type,Preisspalten>>
* <<Tarifrelevantepunkte_Type,Tarifrelevantepunkte>>


[[InterpretationsschluesselProjektspezifisch_Type]]


==== InterpretationsschluesselProjektspezifisch

Für projektspezifische Zwecke oder zum Test können eigene Namen für Interpretationsschluessel verwendet werden.

Namensregeln: Eigene Namen .. .. dürfen nicht mit 'husst.' beginnen, .. dürfen nicht mit einer Zahl beginnen, .. müssen mindestens ein Zeichen [a-ZöäüÖÄÜß\-0-9] je Wort enthalten .. müssen mit einem Wort beginnen, .. dürfen mehrere Wörter mit '.' oder '-' trennen, .. dürfen nicht mit einem Punkt enden.


Verwendet in:

* <<Interpretationen_Type,Interpretationen>>


[[KoordWgs84_Type]]


==== KoordWgs84
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Ortspunkte_Type,Ortspunkte>>


[[UhrzeitMinuten]]


==== UhrzeitMinuten

Definiert den Zeitpunkt eines Tages. Bei der Interpretation wird auf ganze Minuten geachtet. Sekunden-Angaben werden ignoriert. In der Datenbankabbildung wird ein Integer für eine Anzahl an Minuten nach 0 Uhr empfohlen.


Verwendet in:

* <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>



=== technische Enumerationen 


[[DynAttributTyp_Type]]

==== DynAttributTyp

Die Werte eines dynamischen Attributes werden als String abgelegt. Wie dieser zu verstehen ist, wird durch den DynAttributTyp definiert.


Verwendet in:

* <<DynAttributDef_Type,DynAttributDef>>



=== technische Datentypen 


[[Char]]

==== Char
IMPORTANT: [red]#_todo: Doku_#

[[DateCompact]]

==== DateCompact
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Feiertage_Type,Feiertage>>
* <<Kalender_Type,Kalender>>
* <<VersionStruktur_Type,VersionStruktur>>


[[DateTimeCompact]]

==== DateTimeCompact
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Bearbeitung_Type,Bearbeitung>>
* <<PersonalIdentobjekte_Type,PersonalIdentobjekte>>
* <<Personal_Type,Personal>>
* <<Tarifgebiete_Type,Tarifgebiete>>
* <<Updateinfo_Type,Updateinfo>>
* <<VersionInhalt_Type,VersionInhalt>>
* <<Zeitraeume_Type,Zeitraeume>>


[[FLOAT1]]

==== FLOAT1

englische Notation beachten, z. B. 19 Euro = 19.00 Euro


Verwendet in:

* <<Mwst_Type,Mwst>>


[[INT1]]

==== INT1
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Preise_Type,Preise>>
* <<Preisstufen_Type,Preisstufen>>


[[INT2]]

==== INT2
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Preise_Type,Preise>>
* <<Sorten_Type,Sorten>>


[[INT4]]

==== INT4
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<Bediengebiete_Type,Bediengebiete>>
* <<DefBundesland_Type,DefBundesland>>
* <<DefErmittlungseinheit_Type,DefErmittlungseinheit>>
* <<DefFahrgasttyp_Type,DefFahrgasttyp>>
* <<DefIdentobjekttyp_Type,DefIdentobjekttyp>>
* <<DefKomfortklasse_Type,DefKomfortklasse>>
* <<DefNachbarhaltestellenbeziehung_Type,DefNachbarhaltestellenbeziehung>>
* <<DefOTPTyp_Type,DefOTPTyp>>
* <<DefOrtspunkttyp_Type,DefOrtspunkttyp>>
* <<DefPasswortHashtyp_Type,DefPasswortHashtyp>>
* <<DefPreisfindung_Type,DefPreisfindung>>
* <<DefPreisquelle_Type,DefPreisquelle>>
* <<DefPreisspaltentyp_Type,DefPreisspaltentyp>>
* <<DefRabattklasse_Type,DefRabattklasse>>
* <<DefReisetyp_Type,DefReisetyp>>
* <<DefRelationenberechnungsregelung_Type,DefRelationenberechnungsregelung>>
* <<DefRelationendruckregelung_Type,DefRelationendruckregelung>>
* <<DefRelationscodegruppentyp_Type,DefRelationscodegruppentyp>>
* <<DefSortenausgaberegelung_Type,DefSortenausgaberegelung>>
* <<DefSortendruckregelung_Type,DefSortendruckregelung>>
* <<DefSortengruppentyp_Type,DefSortengruppentyp>>
* <<DefSortentyp_Type,DefSortentyp>>
* <<DefStreckenart_Type,DefStreckenart>>
* <<DefStreckencodetyp_Type,DefStreckencodetyp>>
* <<DefTarifpunkttyp_Type,DefTarifpunkttyp>>
* <<DefVertriebswege_Type,DefVertriebswege>>
* <<DefWaehrung_Type,DefWaehrung>>
* <<DefZahlgrenzentyp_Type,DefZahlgrenzentyp>>
* <<DefZahlungsarten_Type,DefZahlungsarten>>
* <<DynAttributDef_Type,DynAttributDef>>
* <<DynAttributWert_Type,DynAttributWert>>
* <<Einsatzarten_Type,Einsatzarten>>
* <<Feiertage_Type,Feiertage>>
* <<Geraet_Type,Geraet>>
* <<GeraeteEinsatztypen_Type,GeraeteEinsatztypen>>
* <<Geraetetypen_Type,Geraetetypen>>
* <<GleichstellungTarifart_Type,GleichstellungTarifart>>
* <<Gleichstellung_Type,Gleichstellung>>
* <<Gleichstellungstyp_Type,Gleichstellungstyp>>
* <<GueltigkeitszeitRegeln_Type,GueltigkeitszeitRegeln>>
* <<Identobjekte_Type,Identobjekte>>
* <<Interpretationen_Type,Interpretationen>>
* <<Kalender_Type,Kalender>>
* <<Linien_Type,Linien>>
* <<Mwst_Type,Mwst>>
* <<Nachbarhaltestellen_Type,Nachbarhaltestellen>>
* <<OrtspunktStreckencode_Type,OrtspunktStreckencode>>
* <<OrtspunkteKA_Type,OrtspunkteKA>>
* <<OrtspunkteTG_Type,OrtspunkteTG>>
* <<Ortspunkte_Type,Ortspunkte>>
* <<PersonalIdentobjekte_Type,PersonalIdentobjekte>>
* <<Personal_Type,Personal>>
* <<Personaleinsatz_Type,Personaleinsatz>>
* <<Preise_Type,Preise>>
* <<Preisspalten_Type,Preisspalten>>
* <<PreisstufenErmittlungen_Type,PreisstufenErmittlungen>>
* <<Preisstufen_Type,Preisstufen>>
* <<Preisstufendirektwahl_Type,Preisstufendirektwahl>>
* <<RaeumlicheGueltigkeit_Type,RaeumlicheGueltigkeit>>
* <<Relationen_Type,Relationen>>
* <<Relationscodegruppen_Type,Relationscodegruppen>>
* <<Relationscodes_Type,Relationscodes>>
* <<Relationszuordnungen_Type,Relationszuordnungen>>
* <<SortenTarifarten_Type,SortenTarifarten>>
* <<Sorten_Type,Sorten>>
* <<SortengruppenElemente_Type,SortengruppenElemente>>
* <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>
* <<Sortengruppen_Type,Sortengruppen>>
* <<Strecke_Type,Strecke>>
* <<Streckencode_Type,Streckencode>>
* <<Streckenzuordnung_Type,Streckenzuordnung>>
* <<Tabelleninfo_Type,Tabelleninfo>>
* <<TagesartMerkmalElemente_Type,TagesartMerkmalElemente>>
* <<Tagesarten_Type,Tagesarten>>
* <<TagesmerkmalElemente_Type,TagesmerkmalElemente>>
* <<Tagesmerkmale_Type,Tagesmerkmale>>
* <<Tarifarten_Type,Tarifarten>>
* <<Tarifgebiete_Type,Tarifgebiete>>
* <<Tarifpunkte_Type,Tarifpunkte>>
* <<TarifpunktmengeElemente_Type,TarifpunktmengeElemente>>
* <<Tarifpunktmengen_Type,Tarifpunktmengen>>
* <<Tarifrelevantepunkte_Type,Tarifrelevantepunkte>>
* <<Teilrelationen_Type,Teilrelationen>>
* <<Unternehmen_Type,Unternehmen>>
* <<VersionStruktur_Type,VersionStruktur>>
* <<Vias_Type,Vias>>
* <<Wege_Type,Wege>>
* <<Wegpositionen_Type,Wegpositionen>>
* <<Zeitraeume_Type,Zeitraeume>>
* <<Zeitraumoptionen_Type,Zeitraumoptionen>>
* <<Zusatzsorten_Type,Zusatzsorten>>


[[INT8]]

==== INT8
IMPORTANT: [red]#_todo: Doku_#

[[Lang_Type]]

==== Lang

Für diese Datenlieferungen sind nur 2-Zeichen Iso-Codes nach ISO 639-1:2002 vorgesehen


Verwendet in:

* <<DynAttributWert_Type,DynAttributWert>>
* <<Sprachtexte_Type,Sprachtexte>>


[[String250]]

==== String250
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<TagesmerkmalElemente_Type,TagesmerkmalElemente>>
* <<Zeitraumoptionen_Type,Zeitraumoptionen>>


[[blobString]]

==== blobString
IMPORTANT: [red]#_todo: Doku_#


Verwendet in:

* <<DynAttributWert_Type,DynAttributWert>>
* <<RaeumlicheGueltigkeit_Type,RaeumlicheGueltigkeit>>
* <<Sorten_Type,Sorten>>



=== Basis Definitionsstand


HUSST Versorgungsdaten - Schema: Basis Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
