

=== TarifAngebot Rootelemente

[[OePVTarifDB_Type]]
==== OePVTarifDB

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |DefFahrgasttypen|
[red]#_todo: Doku_#


Datentyp: <<DefFahrgasttyp_Type,DefFahrgasttyp>>
| |DefKomfortklassen|
[red]#_todo: Doku_#


Datentyp: <<DefKomfortklasse_Type,DefKomfortklasse>>
| |DefNachbarhaltestellenbeziehungen|
[red]#_todo: Doku_#


Datentyp: <<DefNachbarhaltestellenbeziehung_Type,DefNachbarhaltestellenbeziehung>>
| |DefPreisfindungen|
[red]#_todo: Doku_#


Datentyp: <<DefPreisfindung_Type,DefPreisfindung>>
| |DefRabattklassen|
[red]#_todo: Doku_#


Datentyp: <<DefRabattklasse_Type,DefRabattklasse>>
| |DefReisetypen|
[red]#_todo: Doku_#


Datentyp: <<DefReisetyp_Type,DefReisetyp>>
| |DefSortenausgaberegelungen|
[red]#_todo: Doku_#


Datentyp: <<DefSortenausgaberegelung_Type,DefSortenausgaberegelung>>
| |DefSortendruckregelungen|
[red]#_todo: Doku_#


Datentyp: <<DefSortendruckregelung_Type,DefSortendruckregelung>>
| |DefVertriebswege|
[red]#_todo: Doku_#


Datentyp: <<DefVertriebswege_Type,DefVertriebswege>>
| |DefZahlungsarten|
[red]#_todo: Doku_#


Datentyp: <<DefZahlungsarten_Type,DefZahlungsarten>>
| |Relationszuordnungen|
[red]#_todo: Doku_#


Datentyp: <<Relationszuordnungen_Type,Relationszuordnungen>>
| |DefStreckenart|
[red]#_todo: Doku_#


Datentyp: <<DefStreckenart_Type,DefStreckenart>>
| |DefStreckencodetyp|
[red]#_todo: Doku_#


Datentyp: <<DefStreckencodetyp_Type,DefStreckencodetyp>>
| |Bearbeitung|
[red]#_todo: Doku_#


Datentyp: 
| |Bediengebiete|
[red]#_todo: Doku_#


Datentyp: <<Bediengebiete_Type,Bediengebiete>>
| |DefErmittlungseinheit|
[red]#_todo: Doku_#


Datentyp: <<DefErmittlungseinheit_Type,DefErmittlungseinheit>>
| |DefBundeslaender|
[red]#_todo: Doku_#


Datentyp: 
| |DefOTPTypen|
[red]#_todo: Doku_#


Datentyp: <<DefOTPTyp_Type,DefOTPTyp>>
| |DefOrtspunkttypen|
[red]#_todo: Doku_#


Datentyp: <<DefOrtspunkttyp_Type,DefOrtspunkttyp>>
| |DefPreisquellen|
[red]#_todo: Doku_#


Datentyp: <<DefPreisquelle_Type,DefPreisquelle>>
| |DefPreisspaltentypen|
[red]#_todo: Doku_#


Datentyp: <<DefPreisspaltentyp_Type,DefPreisspaltentyp>>
| |DefRelationenberechnungsregelungen|
[red]#_todo: Doku_#


Datentyp: <<DefRelationenberechnungsregelung_Type,DefRelationenberechnungsregelung>>
| |DefRelationendruckregelungen|
[red]#_todo: Doku_#


Datentyp: <<DefRelationendruckregelung_Type,DefRelationendruckregelung>>
| |DefRelationscodegruppentypen|
[red]#_todo: Doku_#


Datentyp: <<DefRelationscodegruppentyp_Type,DefRelationscodegruppentyp>>
| |DefSortengruppentypen|
[red]#_todo: Doku_#


Datentyp: <<DefSortengruppentyp_Type,DefSortengruppentyp>>
| |DefSortentypen|
[red]#_todo: Doku_#


Datentyp: <<DefSortentyp_Type,DefSortentyp>>
| |DefTarifpunkttypen|
[red]#_todo: Doku_#


Datentyp: <<DefTarifpunkttyp_Type,DefTarifpunkttyp>>
| |DefWaehrungen|
[red]#_todo: Doku_#


Datentyp: 
| |DefZahlgrenzentyp|
[red]#_todo: Doku_#


Datentyp: <<DefZahlgrenzentyp_Type,DefZahlgrenzentyp>>
| |Feiertage|
[red]#_todo: Doku_#


Datentyp: 
| |Gleichstellung|
[red]#_todo: Doku_#


Datentyp: <<Gleichstellung_Type,Gleichstellung>>
| |GleichstellungTarifart|
[red]#_todo: Doku_#


Datentyp: <<GleichstellungTarifart_Type,GleichstellungTarifart>>
| |Gleichstellungstyp|
[red]#_todo: Doku_#


Datentyp: <<Gleichstellungstyp_Type,Gleichstellungstyp>>
| |GueltigkeitszeitRegeln|
[red]#_todo: Doku_#


Datentyp: <<GueltigkeitszeitRegeln_Type,GueltigkeitszeitRegeln>>
| |Interpretationen|
[red]#_todo: Doku_#


Datentyp: 
| |Kalender|
[red]#_todo: Doku_#


Datentyp: 
| |Linien|
[red]#_todo: Doku_#


Datentyp: <<Linien_Type,Linien>>
| |Mwst|
[red]#_todo: Doku_#


Datentyp: <<Mwst_Type,Mwst>>
| |Nachbarhaltestellen|
[red]#_todo: Doku_#


Datentyp: <<Nachbarhaltestellen_Type,Nachbarhaltestellen>>
| |OrtspunktStreckencode|
[red]#_todo: Doku_#


Datentyp: <<OrtspunktStreckencode_Type,OrtspunktStreckencode>>
| |Ortspunkte|
[red]#_todo: Doku_#


Datentyp: <<Ortspunkte_Type,Ortspunkte>>
| |OrtspunkteKA|
[red]#_todo: Doku_#


Datentyp: <<OrtspunkteKA_Type,OrtspunkteKA>>
| |OrtspunkteTG|
[red]#_todo: Doku_#


Datentyp: <<OrtspunkteTG_Type,OrtspunkteTG>>
| |Preise|
[red]#_todo: Doku_#


Datentyp: <<Preise_Type,Preise>>
| |Preisspalten|
[red]#_todo: Doku_#


Datentyp: <<Preisspalten_Type,Preisspalten>>
| |Preisstufen|
[red]#_todo: Doku_#


Datentyp: <<Preisstufen_Type,Preisstufen>>
| |PreisstufenErmittlungen|
[red]#_todo: Doku_#


Datentyp: <<PreisstufenErmittlungen_Type,PreisstufenErmittlungen>>
| |Preisstufendirektwahl|
[red]#_todo: Doku_#


Datentyp: <<Preisstufendirektwahl_Type,Preisstufendirektwahl>>
| |RaeumlicheGueltigkeit|
[red]#_todo: Doku_#


Datentyp: <<RaeumlicheGueltigkeit_Type,RaeumlicheGueltigkeit>>
| |Relationen|
[red]#_todo: Doku_#


Datentyp: <<Relationen_Type,Relationen>>
| |Relationscodegruppen|
[red]#_todo: Doku_#


Datentyp: <<Relationscodegruppen_Type,Relationscodegruppen>>
| |Relationscodes|
[red]#_todo: Doku_#


Datentyp: <<Relationscodes_Type,Relationscodes>>
| |Sorten|
[red]#_todo: Doku_#


Datentyp: <<Sorten_Type,Sorten>>
| |SortenTarifarten|
[red]#_todo: Doku_#


Datentyp: <<SortenTarifarten_Type,SortenTarifarten>>
| |Sortengruppen|
[red]#_todo: Doku_#


Datentyp: <<Sortengruppen_Type,Sortengruppen>>
| |SortengruppenElemente|
[red]#_todo: Doku_#


Datentyp: <<SortengruppenElemente_Type,SortengruppenElemente>>
| |SortengruppenErmittlungen|
[red]#_todo: Doku_#


Datentyp: <<SortengruppenErmittlungen_Type,SortengruppenErmittlungen>>
| |Strecke|
[red]#_todo: Doku_#


Datentyp: <<Strecke_Type,Strecke>>
| |Streckencode|
[red]#_todo: Doku_#


Datentyp: <<Streckencode_Type,Streckencode>>
| |Streckenzuordnung|
[red]#_todo: Doku_#


Datentyp: <<Streckenzuordnung_Type,Streckenzuordnung>>
| |TagesartMerkmalElemente|
[red]#_todo: Doku_#


Datentyp: 
| |Tagesarten|
[red]#_todo: Doku_#


Datentyp: 
| |TagesmerkmalElemente|
[red]#_todo: Doku_#


Datentyp: 
| |Tagesmerkmale|
[red]#_todo: Doku_#


Datentyp: 
| |Tarifarten|
[red]#_todo: Doku_#


Datentyp: <<Tarifarten_Type,Tarifarten>>
| |Tarifgebiete|
[red]#_todo: Doku_#


Datentyp: <<Tarifgebiete_Type,Tarifgebiete>>
| |Tarifpunkte|
[red]#_todo: Doku_#


Datentyp: <<Tarifpunkte_Type,Tarifpunkte>>
| |TarifpunktmengeElemente|
[red]#_todo: Doku_#


Datentyp: <<TarifpunktmengeElemente_Type,TarifpunktmengeElemente>>
| |Tarifpunktmengen|
[red]#_todo: Doku_#


Datentyp: <<Tarifpunktmengen_Type,Tarifpunktmengen>>
| |Tarifrelevantepunkte|
[red]#_todo: Doku_#


Datentyp: <<Tarifrelevantepunkte_Type,Tarifrelevantepunkte>>
| |Teilrelationen|
[red]#_todo: Doku_#


Datentyp: <<Teilrelationen_Type,Teilrelationen>>
| |Unternehmen|
[red]#_todo: Doku_#


Datentyp: 
| |Updateinfo|
[red]#_todo: Doku_#


Datentyp: 
| |VersionInhalt|
[red]#_todo: Doku_#


Datentyp: 
| |VersionStruktur|
[red]#_todo: Doku_#


Datentyp: 
| |Vias|
[red]#_todo: Doku_#


Datentyp: <<Vias_Type,Vias>>
| |Wege|
[red]#_todo: Doku_#


Datentyp: <<Wege_Type,Wege>>
| |Wegpositionen|
[red]#_todo: Doku_#


Datentyp: <<Wegpositionen_Type,Wegpositionen>>
| |Zeitraeume|
[red]#_todo: Doku_#


Datentyp: 
| |Zeitraumoptionen|
[red]#_todo: Doku_#


Datentyp: 
| |Zusatzsorten|
[red]#_todo: Doku_#


Datentyp: <<Zusatzsorten_Type,Zusatzsorten>>
|=======================


=== TarifAngebot Elemente


[[Bediengebiete_Type]]
==== Bediengebiete


Bediengebiete erlauben die Defintion von Sichten auf Auswahlelemente (Tarifrelevante Punkte, Haltestellen, etc.). Damit ist die Möglichkeit zur Filterung von Start/Zielauswahlen in verschiedenen Umfeldern möglich.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefErmittlungseinheit_Type]]
==== DefErmittlungseinheit

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Ermittlungseinheit|
[red]#_todo: Doku_#


Datentyp: <<ID_Ermittlungseinheit_Type,ID_Ermittlungseinheit>>
| |Bezeichnung|
Bezeichnung der Ermittlungseinheit

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefFahrgasttyp_Type]]
==== DefFahrgasttypen

Der Fahrgasttyp bezeichnet die tarifrele-vante Kategorie eines Fahrgastes z.B. Kind, Erwachsener, Rentner usw.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Fahrgasttyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Fahrgasttyp_Type,ID_Fahrgasttyp>>
| |Bezeichnung|
Bezeichnung des Fahrgasttyps

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefKomfortklasse_Type]]
==== DefKomfortklassen

Definiert die Komfortklasse für deren Benutzung die Fahrscheinsorte berechtigt (z.B. 1 für 1. Klasse, 2 für 2. Klasse)
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Komfortklasse|
[red]#_todo: Doku_#


Datentyp: <<ID_Komfortklasse_Type,ID_Komfortklasse>>
| |Bezeichnung|
Bezeichnung der Komfortklasse.

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefNachbarhaltestellenbeziehung_Type]]
==== DefNachbarhaltestellenbeziehungen


Art einer Nachbarhaltestellenbeziehung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Nachbarhaltestellenbeziehung|

Art der Nachbarbeziehung.


Datentyp: <<ID_Nachbarhaltestellenbeziehung_Type,ID_Nachbarhaltestellenbeziehung>>
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Bezeichnung der Art der Nachbarbeziehung.


Datentyp: string
|=======================
  ★  Pflichtelemente

[[DefOTPTyp_Type]]
==== DefOTPTypen

Definiert den Verwendungszweck eines Typs von Tarifrelevantenpunkten (OTP steht für Orte und Tarifrelevante Punkte). Siehe auch ID_OTPTyp_Type bzw. ID_OTPTypHUSST_Type

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_OTPTyp|
[red]#_todo: Doku_#


Datentyp: <<ID_OTPTyp_Type,ID_OTPTyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefOrtspunkttyp_Type]]
==== DefOrtspunkttypen


Definiert die Bedeutung eines Ortspunktes.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkttyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Ortspunkttyp_Type,ID_Ortspunkttyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefPreisfindung_Type]]
==== DefPreisfindungen

Definiert die Art der Preisfindung für eine Sorte. Z.B. Festpreis, Relationbezogen, etc. Siehe auch ID_Preisfindung_Type bzw. ID_PreisfindungHUSST_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preisfindung|
[red]#_todo: Doku_#


Datentyp: <<ID_Preisfindung_Type,ID_Preisfindung>>
| |Bezeichnung|
Bezeichnung des Preisfindungs

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefPreisquelle_Type]]
==== DefPreisquellen

Definiert eine Quellenangabe die einer Teilrelation zugeordnet werden kann. Quellenangaben dienen im wesentlichen der späteren Ausgabezuscheidung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preisquelle|
[red]#_todo: Doku_#


Datentyp: <<ID_Preisquelle_Type,ID_Preisquelle>>
| |Bezeichnung|

Bezeichnung der Preisquelle z.B. NE-Blatt-Nummer


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefPreisspaltentyp_Type]]
==== DefPreisspaltentypen


Definiert den Verwendungszweck oder die Herkunft einer Preisspalte.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preisspaltentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Preisspaltentyp_Type,ID_Preisspaltentyp>>
| |Kennung|

Zur eindeutigen Identifikation des Preisspaltentyps.


Datentyp: string
| |Bezeichnung|

Zur Anzeige des Preispalten-Typs.


Datentyp: string
| |ReferenzExtern|

Zur externen Synchronisation des Preisspaltentyps.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefRabattklasse_Type]]
==== DefRabattklassen

Definiert die Rabattklasse, z.B. "BahnCard50 1.Kl.", auf die in Sorten verweisen wird.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Rabattklasse|
Eindeutige ID der Rabattklassse

Datentyp: <<ID_Rabattklasse_Type,ID_Rabattklasse>>
| |Bezeichnung|
Bezeichnung der Rabattklasse.

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefReisetyp_Type]]
==== DefReisetypen

Beschreibt den Typ der Reise (normale Fahrt, HinUndRück, Rundreise, ...), auf den in Sorten verwiesen wird.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Reisetyp|
Eindeutige ID des Reisetyps

Datentyp: <<ID_Reisetyp_Type,ID_Reisetyp>>
| |Bezeichnung|
Bezeichnung des Reisetyps

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefRelationenberechnungsregelung_Type]]
==== DefRelationenberechnungsregelungen


Die Berechnungsregelung bestimmt, wie die Teilrelationen zu einer Relation zu verarbeiten sind. Diese Regelung kann dabei Auswirkungen auf den Preis haben. Die Husst definierten Werte sind genau beschrieben, eigene Werte müssen gut abgestimmt sein.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relationenberechnungsregelung|
[red]#_todo: Doku_#


Datentyp: <<ID_Relationenberechnungsregelung_Type,ID_Relationenberechnungsregelung>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefRelationendruckregelung_Type]]
==== DefRelationendruckregelungen


Die Druckregelung bestimmt, wie die Werte der Teilrelationen zu drucken sind. Die Husst definierten Werte sind genau beschrieben, eigene Werte müssen gut abgestimmt sein.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relationendruckregelung|
[red]#_todo: Doku_#


Datentyp: <<ID_Relationendruckregelung_Type,ID_Relationendruckregelung>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefRelationscodegruppentyp_Type]]
==== DefRelationscodegruppentypen


bspw. als Magneten für Citytarif

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relcodegruppentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Relcodegruppentyp_Type,ID_Relcodegruppentyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefSortenausgaberegelung_Type]]
==== DefSortenausgaberegelungen


Die Sortenausgaberegelung bestimmt in welcher Art diese Sorte ausgegeben werden darf. Bsp. Papierfahrschein oder eTicket. Die Werte werden als Bitmaske behandelt, sodass an einer Sorte mehrere Ausgabemethoden erlaubt sein können.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortenausgaberegelung|
[red]#_todo: Doku_#


Datentyp: <<ID_Sortenausgaberegelung_Type,ID_Sortenausgaberegelung>>
| |Bezeichnung|
Bezeichnung des Sortenausgaberegelungs

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefSortendruckregelung_Type]]
==== DefSortendruckregelungen

Die Sortendruckregelung definiert die Art, in der ein Fahrschein gedruckt wird. Defaultmäßig wird das am Preise / an der Sorte definierte Layout verwendet (Vordefinierter Wert 1).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortendruckregelung|
[red]#_todo: Doku_#


Datentyp: <<ID_Sortendruckregelung_Type,ID_Sortendruckregelung>>
| |Bezeichnung|
Bezeichnung des Sortendruckregelungs

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefSortengruppentyp_Type]]
==== DefSortengruppentypen

Definiert den Verwendungszweck eines Typs von Sortengruppen. Siehe auch ID_Sortengruppentyp_Type bzw. ID_SortengruppentypHUSST_Type.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortengruppentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Sortengruppentyp_Type,ID_Sortengruppentyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefSortentyp_Type]]
==== DefSortentypen


Die vordefinierten Sortentypen stellen eine grobe Klassizifzierung der Sorte dar. Anhand des Sortentyps kann das Vorgehen des Vertriebssystems gesteuert werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Sortentyp_Type,ID_Sortentyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefStreckenart_Type]]
==== DefStreckenart

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Streckenart|
[red]#_todo: Doku_#


Datentyp: <<ID_Streckenart_Type,ID_Streckenart>>
| |Bezeichnung|
Bezeichnung der Streckenart

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefStreckencodetyp_Type]]
==== DefStreckencodetyp

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Streckencodetyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Streckencodetyp_Type,ID_Streckencodetyp>>
| |Bezeichnung|
Bezeichnung der Streckencodetyp

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefTarifpunkttyp_Type]]
==== DefTarifpunkttypen

Definiert die Art eines Tarifpunktes (Tarifhaltestelle, Zone/Wabe/Ring, Überzone/Wabentyp etc..) siehe ID_Tarifpunkttyp_Type bzw. ID_TarifpunkttypHusst_Type

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunkttyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Tarifpunkttyp_Type,ID_Tarifpunkttyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefVertriebswege_Type]]
==== DefVertriebswege


Die Vertriebswege kommen bei verschiedenen Typen als Attribut vor. In erster Linie werden sie dazu verwendet, die Datenmenge für verschiedene Verkaufsgeräte zu reduzieren, indem Elemente, die der entsprechenden Vertriebstechnik nicht zugeordnet sind, auch nicht mit den Herstellerunabhängige Standardschnittstelle "Datenaustausch in ÖPV-Vertriebssystemen" 2010-2012 Seite 37 von 178 Daten versorgt werden. Teilweise haben die Vertriebswege aber auch steuernden Charakter auf den Verkaufsgeräten. Z.B. kann mit den Vertriebswegen festgelegt sein, dass eine bestimmte Sorte als elektronischer Fahrschein verkauft werden darf, oder eben nicht.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Vertriebswege|
[red]#_todo: Doku_#


Datentyp: <<ID_Vertriebswege_Type,ID_Vertriebswege>>
| |Bezeichnung|
Bezeichnung der Vertriebswege.

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefZahlgrenzentyp_Type]]
==== DefZahlgrenzentyp

Zahlungsarten definieren ein Verfahren, mit dem eine Sorte bezahlt werden kann. Siehe auch ID_Zahlungsarten_Type bzw. ID_ZahlungsartenHUSST_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Zahlgrenzentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Zahlgrenzentyp_Type,ID_Zahlgrenzentyp>>
| |Bezeichnung|
Bezeichnung der Zahlgrenze.

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefZahlungsarten_Type]]
==== DefZahlungsarten

Zahlungsarten definieren ein Verfahren, mit dem eine Sorte bezahlt werden kann. Siehe auch ID_Zahlungsarten_Type bzw. ID_ZahlungsartenHUSST_Type.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Zahlungsarten|
[red]#_todo: Doku_#


Datentyp: <<ID_Zahlungsarten_Type,ID_Zahlungsarten>>
| |Bezeichnung|
Bezeichnung der Zahlungsarten.

Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Gleichstellung_Type]]
==== Gleichstellung


Tarifliche Gleichstellung eines Starts oder eines Ziels einer Strecke ab einer definierten Gesamtentfernung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Gleichstellung|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Streckencode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_StreckencodeGleichstellung|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Gleichstellungstyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |EntfernungAb|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Gleichstellung.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[GleichstellungTarifart_Type]]
==== GleichstellungTarifart


einen Gelichstellungstyp einer Tarifart zu.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Gleichstellungstyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Gleichstellungstyp-Tarifart Zuordnung.


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Gleichstellungstyp_Type]]
==== Gleichstellungstyp


Die Art der Gleichstellung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Gleichstellungstyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Schlüssel des Tarifgebers für diesen Gleichstellungstyp.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[GueltigkeitszeitRegeln_Type]]
==== GueltigkeitszeitRegeln


Definiert eine zeitliche Gültigkeit. Darin enthalten sein kann auch die Vorverkaufbarkeit (Regel zum möglichen Gültigkeitsbeginn) und die Umschaltung auf einen neuen Default-Gültigkeitsbeginn. Der Datentyp wird noch weiter ausgebaut und in einer eigenen HUSST-Definition konkretisiert.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_GueltigkeitszeitRegel|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |GueltigkeitszeitRegelNr|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Param|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Linien_Type]]
==== Linien

Abbildung von Linien mit Zuordnung zum Fahrtverlauf. Dabei kann für die Hin- und Rückrichtung ein gesonderter Fahrtverlauf angegeben werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Linie|
Liniennummer

Datentyp: <<INT4,INT4>>
| |ID_Weg_Hin|
Linienhauptweg

Datentyp: <<INT4,INT4>>
| |ID_Weg_Rueck|

Linienhauptweg Rückrichtung


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ID_Konzessionaer|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Mwst_Type]]
==== Mwst

Definition aller Mehrwertsteuersätze zur jeweiligen Referenzierung in Preisstufen, Sorten und Preisen
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Mwst|

Kennung des Mehrwertsteuersatzes


Datentyp: <<INT4,INT4>>
| |MwstSatz|

Prozentzahl des Mehrwertsteuersatzes


Datentyp: <<FLOAT1,FLOAT1>>
| |Bezeichnung|

Info zum MwSt.-Satz; bspw. ermäßigter Steuersatz etc.


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Mehrwertsteuerdatensätze über eine nicht numerische Referenz identifizieren zu können.


Datentyp: string
| |KA_Mwst|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Nachbarhaltestellen_Type]]
==== Nachbarhaltestellen

Zur Definition von Kurzstrecken o.ä..(s. ID_Nachbarhaltestellenbeziehung) Eine Nachbarhaltestellenbeziehung kann über ID_OrtspunktVon und ID_OrtspunktNach erfolgen oder über ID_OrtspunktVon und Zahlgrenze. Es muss entweder ID_OrtspunktNach oder Zahlgrenze gefüllt sein. Wenn beides gefüllt ist, gelten beide Bedingungen zeitgleich. (Es gilt auf der Strecke von ID_OrtspunktVon nach ID_OrtspunktNach, wenn die Zahlgrenze nicht überschritten ist.) Die Nachbarhaltestellen werden in der Verkaufslogik bei der Anzeige der Vias vor die Relationen sortiert.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Nachbarhaltestelle|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Bediengebiet|
Bediengebiet, in dessen Kontext die Nachbarbeziehung definiert ist .

Datentyp: <<INT4,INT4>>
| |ID_Nachbarhaltestellenbeziehung|
Art der Nachbarbeziehung.

Datentyp: <<ID_Nachbarhaltestellenbeziehung_Type,ID_Nachbarhaltestellenbeziehung>>
|★ |ID_OrtspunktVon|
ID_Ortspunkt, für die eine Nachbarbeziehung definiert wird (kleinere ID des Paares, bei Halbmatrix).


Datentyp: <<INT4,INT4>>
| |ID_OrtspunktNach|
ID_Ortspunkt, für die eine Nachbarbeziehung definiert wird (größere ID des Paares, bei Halbmatrix)


Datentyp: <<INT4,INT4>>
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Via|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Tarifart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Tarifgebiet|
Tarifgebiet, für das eine Nachbarhaltestelle definiert wird.

Datentyp: <<INT4,INT4>>
| |ID_Preisstufe|
Zuordnung Preisstufe

Datentyp: <<INT4,INT4>>
| |Zahlgrenzen|
Gibt den Wert an vom Typ des Zahlgrenzentyps.

Datentyp: <<INT4,INT4>>
| |ID_Zahlgrenzentyp|
Gibt den Typ an, der die Zahlgrenzen definiert.

Datentyp: <<ID_Zahlgrenzentyp_Type,ID_Zahlgrenzentyp>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[OrtspunktStreckencode_Type]]
==== OrtspunktStreckencode


Ordnet einen Ortspunkt einem Streckencode in einem Tarifgebiet zu.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Streckencode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Streckencodetyp|

Typ dieses Streckencodes (dieses Haltepunktes).


Datentyp: <<ID_Streckencodetyp_Type,ID_Streckencodetyp>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Ortspunkt-Streckencode Zuordnung.


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Ortspunkte_Type]]
==== Ortspunkte


Haltestellen mit Zonen/Relationscode Zuordnung

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkt|

Eindeutige Datensatz-ID innerhalb der ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkttyp|
Bspw. Betriebshof

Datentyp: <<ID_Ortspunkttyp_Type,ID_Ortspunkttyp>>
|★ |Ortsnummer|

Bundeseinheitliche HST Nummer


Datentyp: <<INT4,INT4>>
| |ID_Relcode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |IBISnr|
[red]#_todo: Doku_#


Datentyp: string
| |ID_Bundesland|
[red]#_todo: Doku_#


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
| |Gemeindekennziffer|
[red]#_todo: Doku_#


Datentyp: string
| |Bezeichnung|

Bezeichnung des Ortspunktes (z.B. für die Anzeige)


Datentyp: string
| |BezeichnungKurz|

Kurzbezeichnung des Ortspunktes (z.B. für zusammengesetzte Via-Information, wenn das Attribut leer ist, wird Bezeichnung verwendet)


Datentyp: string
| |BezeichnungDruck|

Bezeichnung des Ortspunktes für den Ausdruck (wenn das Attribut leer ist, wird Bezeichnung verwendet)


Datentyp: string
| |ReferenzExtern|

Tarifgeberspez. Nr., bspw. für Aufdruck


Datentyp: string
| |ID_Bediengebiet|

Bestimmt das Bediengebiet, das einzustellen ist, wenn dieser Ortspunkt als Standort ermittelt wird.


Datentyp: <<INT4,INT4>>
| |ID_OrtspunktReferenz|

Referenziert einen übergeordneten Ortspunkt


Datentyp: <<INT4,INT4>>
| |XKoordWgs84|
[red]#_todo: Doku_#


Datentyp: <<KoordWgs84_Type,KoordWgs84>>
| |YKoordWgs84|
[red]#_todo: Doku_#


Datentyp: <<KoordWgs84_Type,KoordWgs84>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[OrtspunkteKA_Type]]
==== OrtspunkteKA


KA-Attribute der Ortspunkte

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_OrtspunktKA|

Eindeutige Datensatz-ID innerhalb der ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkt|

Referenz zum Ortspunkt, den der OrtspunktKA um VDV KA Eigenschaften ergänzt.


Datentyp: <<INT4,INT4>>
| |KA_OrtOrgID|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |KA_OrtTyp|
KA Ortstyp

Datentyp: <<INT4,INT4>>
| |KA_OrtNummer|
KA Ortnummer

Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[OrtspunkteTG_Type]]
==== OrtspunkteTG


tarifgebietspezifische-Attribute der Ortspunkte

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_OrtspunktTG|

Eindeutige Datensatz-ID innerhalb der ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_Ortspunkt|

Referenz zum Ortspunkt, den der OrtspunktTG tarifgebietspezifisch ergänzt oder überschreibt.


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Ortsbezeichnung


Datentyp: string
| |BezeichnungKurz|

Kurzbezeichnung des Orts


Datentyp: string
| |BezeichnungDruck|

Bezeichnung des Orts für den Ausdruck


Datentyp: string
| |ReferenzExtern|

Tarifgeberspez. Nr., bspw. für Aufdruck


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Preise_Type]]
==== Preise

Preise aller Sorten, abhängig von Zeitraum und Tarifgebiet, ggf. auch von Preisstufe, und Preisspalte
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preis|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sorte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|

Die ID_Tarifgebiet bleibt als retundante Information erhalten. Sie muss aber mit der ID_Tarifgebiet der Preisstufe übereinstimmen.


Datentyp: <<INT4,INT4>>
|★ |ID_Preisstufe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Preisspalte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

bisher: TarifgeberProduktNr Schlüssel des Tarifgebers


Datentyp: string
| |Preis|

Preis in kleinster Währungseinheit (z.b. Cent)


Datentyp: <<INT4,INT4>>
| |PreisstufenbezeichnungKurz|

optional: abweichende Preisstufenkurzbezeichnung für Anzeige und Druck


Datentyp: string
| |Preisstufenbezeichnung|

optional: abweichende Preisstufenbezeichnung für Anzeige und Druck


Datentyp: string
| |ID_Mwst|

optional: abweichende Mehrwertsteuerkennung


Datentyp: <<INT4,INT4>>
| |ID_PreisstufeReferenz|

optional Referenz auf die tatsächlich zu verwendende Preisstufe für Druck Anzeige Registrierung Gültigkeitsberechnung

Verwendung: Wenn eine Tarifverbindung eine ID_Preisstufe x liefert, und die Tarifbestimmungen definieren, dass für dieses Sorte statt der ID_Preisstufe x ein Fahrschein mit der Preisstufe y verkauft werden soll, wird in ID_PreisstufeReferenz ein Verweis auf Preisstufe y eingetragen.


Datentyp: <<INT4,INT4>>
| |ID_GueltigkeitszeitRegel|

Definiert die zeitliche Gültigkeit des Produktes.


Datentyp: <<INT4,INT4>>
| |ID_RaeumlicheGueltigkeit|

Verweis auf eine Definition für die räumliche Gültigkeit.


Datentyp: <<INT4,INT4>>
| |KA_ProdOrgID|

KA Produkt Organisationsnummer


Datentyp: <<INT2,INT2>>
| |KA_ProdNr|
KA Produkt

Datentyp: <<INT2,INT2>>
| |KA_Rabatttyp|
KA Rabatttyp

Datentyp: <<KA_RabattParameter_CODE_Type,KA_RabattParameter_CODE>>
| |KA_Mitnahme1Typ|
[red]#_todo: Doku_#


Datentyp: <<KA_Profil_CODE_Type,KA_Profil_CODE>>
| |KA_Mitnahme1MinAnzahl|
[red]#_todo: Doku_#


Datentyp: <<INT1,INT1>>
| |KA_Mitnahme1MaxAnzahl|
[red]#_todo: Doku_#


Datentyp: <<INT1,INT1>>
| |KA_Mitnahme2Typ|
[red]#_todo: Doku_#


Datentyp: <<KA_Profil_CODE_Type,KA_Profil_CODE>>
| |KA_Mitnahme2MinAnzahl|
[red]#_todo: Doku_#


Datentyp: <<INT1,INT1>>
| |KA_Mitnahme2MaxAnzahl|
[red]#_todo: Doku_#


Datentyp: <<INT1,INT1>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Preisspalten_Type]]
==== Preisspalten


Die Preisspalte definiert die Währung der zugeordneten Preise und ermöglicht Preisvarianten. Verschiedene Preisspalten für die gleiche Sorte, Währung und Preisstufe ermöglichen die Bereitstellung alternativer Preise (z.B. Barzahlung vs. Bezahlung mit Kundenkarte) oder den Ausweis von spezifischen Preisanteilen (z.B. Preisanteil Aufgabenträger).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preisspalte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Waehrung|

ISO-Kennung (dezimal) der Währung - außer EUR=999


Datentyp: <<ID_Waehrung_Type,ID_Waehrung>>
| |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Preisspaltentyp|

Definiert den Verwendungszweck oder die Herkunft einer Preisspalte. HUSST Standard=1


Datentyp: <<ID_Preisspaltentyp_Type,ID_Preisspaltentyp>>
| |Bezeichnung|

Spaltenüberschrift


Datentyp: string
| |BezeichnungKurz|
[red]#_todo: Doku_#


Datentyp: string
| |Hinweis|
Info zur Preisspalte

Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Preisstufen_Type]]
==== Preisstufen

Definition der Preisstufen pro Tarifgebiet und Zeitraum
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Preisstufe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Preisstufennummer|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |BezeichnungKurz|
[red]#_todo: Doku_#


Datentyp: string
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |WegstreckeInMetern|

durschnittliche Wegstrecke in Meter für PKM (Personen-Kilometer) Berechnung


Datentyp: <<INT4,INT4>>
| |ID_Mwst|

Nummer des Mehrwertsteuersatzes


Datentyp: <<INT4,INT4>>
| |UpgradeStopp|

Ein Preisupgrade kann bis zu einschließlich dieser Preisstufe erfolgen. Es können mehrere Stopps eingebaut sein.


Datentyp: boolean
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |KA_Preisstufe|
[red]#_todo: Doku_#


Datentyp: <<INT1,INT1>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[PreisstufenErmittlungen_Type]]
==== PreisstufenErmittlungen


Die PreisstufenErmittlungen dienen dazu, die zu berechenden Preisstufen für eine Sorte zu ermitteln. Dabei orientiert sich die PreisstufenErmittlung an einer variablen Ermittlungseinheit (z.B. Minuten / Kilometer). Die PreisstufenErmittlung ist eine alternative zur Ermittlung der Preisstufe über eine Teilrelation. Die PreisstufenErmittlung hat hauptsächlich im Zusammenhang mit der SortengruppenErmittlung im MaaS-Bereich eine Relevanz. Die ermittelte Preisstufe muss ggf. mehrfach berechnet werden.

Wenn die Menge an Ermittlungseinheiten in dem Rahmen von "Von" und "Bis" liegt, wird die Anzahl der Schritte aufgerundet auf ganze Werte mal den Preis gerechnet.

Bsp.: Einheit Minuten, Von 0, Bis 90, Schritt 5, ID_Preisstufe 1 => Wenn 32 Minuten berechnet werden sollen, wird der Preis der ID_Preisstufe 1 7x berechnet.

Bsp. 2: Einheit Minuten, Von 90, Bis 180, Schritt 10, ID_Preisstufe 2 => Wenn 117 Minuten berechnet werden sollen, wird der Preis der ID_Preisstufe 2 3x berechnet. Zusätzlich sind für den Zeitraum von 0 bis 90 Minuten weitere Preisstufen zu ermitteln. (z.B. aus Beispiel 1 die ID_Preisstufe 1 18x)

Bsp. 3: Einheit Kilometer, Von 0, Bis 100, Schritt 100, ID_Preisstufe 3 => Wenn 5 Kilometer berechnet werden sollen, wird der Preis der ID_Preisstufe 3 1x berechnet. So kann ID_Preisstufe 3 allgemein nur 1x berechnet werden, da Schritt = Bis - Von ist.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_PreisstufenErmittlung|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Preisstufe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Ermittlungseinheit|
[red]#_todo: Doku_#


Datentyp: <<ID_Ermittlungseinheit_Type,ID_Ermittlungseinheit>>
|★ |Von|
Incl.

Datentyp: <<INT4,INT4>>
| |Bis|
Excl.

Datentyp: <<INT4,INT4>>
|★ |Schritt|

Schritt darf nicht größer als Bis - Von sein. Schritt muss ein Teiler von Bis - Von sein => (Bis - Von) Modulo Schritt = 0.


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Kann eine textuelle Beschreibung dieser Regel beinhalten. Diese ist nicht zur Verwendung von Vertriebsendgeräten vorgesehen.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Preisstufendirektwahl_Type]]
==== Preisstufendirektwahl


Definition von Haltestellengruppen für Kurzstrecken/Zahlgrenzen

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Preisstufendirektwahl|

Datensatz-Schlüssel - eindeutig innheralb der ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |Direktwahlschluessel|

Schlüsselwert, über den die Pst-Direktwahl gefunden wird. Projektspezifisch definiert.


Datentyp: string
|★ |ID_Tarifart|

Tarifart (0=Allgemein, 1=Bartarif, 2=Zeittarif)


Datentyp: <<INT4,INT4>>
|★ |ID_Preisstufe|
Zuordnung Preisstufe

Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Text zur Anzeige der Preisstufendirektwahl


Datentyp: string
| |BezeichnungDruck|

Drucktext


Datentyp: string
| |ID_Relation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Vertriebswege|

Schränkt die Verwendung des Elements auf die angegebenen Vertriebswege ein.


Datentyp: <<ID_Vertriebswege_Type,ID_Vertriebswege>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[RaeumlicheGueltigkeit_Type]]
==== RaeumlicheGueltigkeit


Definition der räumlichen Gültigkeit

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_RaeumlicheGueltigkeit|

Eindeutige Datensatz-ID innerhalb eines Zeitraumes


Datentyp: <<INT4,INT4>>
| |ID_Tarifpunktmenge|

Referenz auf eine Tarifpunktmenge.


Datentyp: <<INT4,INT4>>
| |KA_GueltigkeitsraumOriginaer|

Die originäre räumliche Gültigkeit auf einem KA Ticket. Wird als ganzes TLV abgebildet, beginnend mit dem TAG 'DC'


Datentyp: <<blobString,blobString>>
| |KA_GueltigkeitsraumAlternativ|

Die alternative räumliche Gültigkeit auf einem KA Ticket. Wird als ganzes TLV abgebildet, beginnend mit dem TAG 'D9'


Datentyp: <<blobString,blobString>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Relationen_Type]]
==== Relationen


Relation auf Relationscode Ebene

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_RelcodeStart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_RelcodeZiel|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |SortOrder|

Variantenzählung - Bestimmt die Reihenfolge der Vias in der Auswahl


Datentyp: <<INT4,INT4>>
| |GegenrichtungLiegtVor|
[red]#_todo: Doku_#


Datentyp: boolean
| |ID_Vertriebswege|

Schränkt die Verwendung des Elements auf die angegebenen Vertriebswege ein.


Datentyp: <<ID_Vertriebswege_Type,ID_Vertriebswege>>
| |ID_Via|

Nummer der Viatexte für diese Verbindung. Verweis auf Vias.


Datentyp: <<INT4,INT4>>
| |ID_Berechnungsregelung|

Regelt die Verwendung konkurrierender Teilrelationen (gleiche ID_Tarifgebiet, ID_Tarifart) zur Preisberechnung und Registrierung.


Datentyp: <<ID_Relationenberechnungsregelung_Type,ID_Relationenberechnungsregelung>>
| |ID_Druckregelung|

Regelt die Verwendung konkurrierender Teilrelationen für den Ausdruck von Tickets.


Datentyp: <<ID_Relationendruckregelung_Type,ID_Relationendruckregelung>>
| |ID_TarifartStrecke|

Die ID_TarifartStrecke ermöglicht oder verhindert eine parallele Suche in den Streckentarifen.

* das Vertriebsgerät muss parallel in der Streckenlogik suchen, wenn ID_TarifartStrecke gesetzt ist,

* das Vertriebsgerät darf nicht in der Streckenlogik suchen, wenn ID_TarifartStrecke leer bzw. nicht angegeben ist, unabhängig davon, ob die Relation mit Teilrelationen verknüpft ist, oder nicht.            


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Relationscodegruppen_Type]]
==== Relationscodegruppen


Zusammenfassung von Relationscodes bspw. für City Option unter einer Gruppennummer innerhalb eines ID_Relcodegruppentyps

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relcodegruppentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Relcodegruppentyp_Type,ID_Relcodegruppentyp>>
|★ |ID_Relcodegruppe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |Gruppennummer|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Relcode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Relationscodes_Type]]
==== Relationscodes


Relationscodes fassen Tarifpunkte mehrerer Tarifgeber zusammen. Damit können einzelnen Orten/Haltestellen unterschiedlich viele Tarifpunkte unterschiedlicher Tarifgeber zugeordnet werden

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relcode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|=======================
  ★  Pflichtelemente

[[Relationszuordnungen_Type]]
==== Relationszuordnungen


Verknüpft Relationen und Teilrelationen

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Relationszuordung|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Relation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Teilrelation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Sorten_Type]]
==== Sorten


Artikel/Produkte/Fahrscheintypen

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sorte|

Nummer der Sorte, eindeutig über alle Tarifgebiete und Tarifversionen


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sortentyp|

Typ der Sorte


Datentyp: <<ID_Sortentyp_Type,ID_Sortentyp>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Sorte


Datentyp: string
| |BezeichnungKurz|

Verwendung: Identifikation / optional Druck


Datentyp: string
| |Bezeichnung|

Verwendung: Identifikation / optional Druck


Datentyp: string
| |ID_Ausgaberegelung|

Hinweis zur Ausgabe der Sorte (Papierfahrschein / Elektronischer Fahrausweis etc.)


Datentyp: <<ID_Sortenausgaberegelung_Type,ID_Sortenausgaberegelung>>
| |ID_Druckregelung|

Steuert die Fahrscheinausgabe auf verschiedene Medien.


Datentyp: <<ID_Sortendruckregelung_Type,ID_Sortendruckregelung>>
| |Layout|

Layoutdefinition für den Ausdruck des Produktes


Datentyp: <<blobString,blobString>>
| |ID_Vertriebswege|

Schränkt die Verwendung der Sorte auf die angegebenen Vertriebswege ein.


Datentyp: <<ID_Vertriebswege_Type,ID_Vertriebswege>>
| |ID_Mwst|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Zahlungsarten|

Schränkt die Verwendung der Sorte auf die angegebenen Zahlungsarten ein.


Datentyp: <<ID_Zahlungsarten_Type,ID_Zahlungsarten>>
| |ID_Komfortklasse|

Hinweis zur Komfortklasse (1.Klasse/2.Klasse etc).


Datentyp: <<ID_Komfortklasse_Type,ID_Komfortklasse>>
| |ID_Rabattklasse|

Hinweis zur Rabattklasse (BC25/BC50 ect.).


Datentyp: <<ID_Rabattklasse_Type,ID_Rabattklasse>>
| |ID_Fahrgasttyp|

Hinweis zum Fahrgasttyp (Erwachsener/Kind etc.).


Datentyp: <<ID_Fahrgasttyp_Type,ID_Fahrgasttyp>>
| |Mindestpersonenanzahl|

Ab wievielen Personen darf der Fahrschein verkauft werden


Datentyp: <<INT4,INT4>>
| |Hoechstpersonenanzahl|

Bis zu wievielen Personen darf der Fahrschein maximal verkauft werden


Datentyp: <<INT4,INT4>>
| |ID_GueltigkeitszeitRegel|

Definiert die zeitliche Gültigkeit des Produktes.


Datentyp: <<INT4,INT4>>
| |ID_Preisfindung|

Hinweis zur Preisfindung.


Datentyp: <<ID_Preisfindung_Type,ID_Preisfindung>>
| |ID_Reisetyp|
Beschreibt den Typ der Reise (normale Fahrt, HinUndRück, Rundreise, ...)

Datentyp: <<ID_Reisetyp_Type,ID_Reisetyp>>
| |BezeichnungDruck|

Drucktext Verwendung ist abhängig von der Layoutdefinition


Datentyp: string
| |KA_ProdOrgID|

KA Produkt Organisationsnummer


Datentyp: <<INT2,INT2>>
| |KA_ProdNr|
KA Produkt

Datentyp: <<INT2,INT2>>
| |KA_Infotext|
[red]#_todo: Doku_#


Datentyp: string
| |KA_Fahrgasttyp|
KA Fahrgasttyp

Datentyp: <<KA_Kundentyp_CODE_Type,KA_Kundentyp_CODE>>
| |KA_Verkehrsmittel|

KA Verkehrsmittel


Datentyp: <<KA_TransportmittelKategorie_CODE_Type,KA_TransportmittelKategorie_CODE>>
| |KA_Serviceklasse|

KA Serviceklasse


Datentyp: <<KA_ServiceKlasse_CODE_Type,KA_ServiceKlasse_CODE>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[SortenTarifarten_Type]]
==== SortenTarifarten


N:M Zuordnung - Sorte / Tarifart

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sorte|

Nummer der Sorte, eindeutig über alle Tarifgebiete innerhalb des ID_Zeitraum bzw. des Haupt-ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifart|

Tarifart (siehe Hilfstabelle Tarifart)


Datentyp: <<INT4,INT4>>
|=======================
  ★  Pflichtelemente

[[Sortengruppen_Type]]
==== Sortengruppen


Sortengruppen können Sorten für unterschiedliche Anwendungsfälle gruppieren. Der Anwendungsfall wird über den Sortengruppentyp unterschieden werden. Seine Bedeutung ist projektspezifisch zu konkretisiern. Den zugeordneten Sorten können auch Preisstufen zugeordnet sein.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortengruppe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sortengruppentyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Sortengruppentyp_Type,ID_Sortengruppentyp>>
|★ |ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
Info

Datentyp: string
| |ReferenzExtern|

Externer Schlüssel für die Sortengruppe.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[SortengruppenElemente_Type]]
==== SortengruppenElemente

Sorten/Preisstufen Einträge einer Sortengruppe.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_SortengruppenElement|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Sortengruppe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sorte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Preisstufe|

ID_Preisstufe ist optional. Wenn die Preisstufe angegeben ist, wird der Produkt als Festpreis verkauft. Ansonsten muss die Preisstufe aufgrund weiterer Einschränkungen (z.b. Auswahl einer Relation) ermittelt bzw. festgelegt werden.


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[SortengruppenErmittlungen_Type]]
==== SortengruppenErmittlungen


Die SortengruppenErmittlungen definieren Regeln zur Stukturierung von Tarifen in beliebig kleine Zeitperioden innerhalb eines Zeitraums. Eine Zeitperiode wird dabei durch StartVon und -Bis Uhrzeit und der Tagesart definiert. DauerMax und der Überhang verfeinern diese Definition.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_SortengruppenErmittlung|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sortengruppe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Tarifpunktmenge|

Wenn gesetzt, definiert die Tarifpunktmenge zusätzlich zur zeitlichen eine räumliche Einschränkung.


Datentyp: <<INT4,INT4>>
| |ID_TagesartVon|

Wenn gesetzt, gilt diese Regel nur an den bestimmten Tagen. Die gesetzte Tagesart gilt für die Uhrzeit StartVon. Wenn nicht gesetzt gilt die Regel an allen Tagen.


Datentyp: <<INT4,INT4>>
|★ |StartVon|

Gibt eine Uhrzeit von dem an diese Zeitperiode gilt. Diese ist inklusiv zu betrachten. Wenn StartVon und StartBis irrelevant sind, kann hier 00:00 Uhr eingetragen werden.


Datentyp: <<UhrzeitMinuten,UhrzeitMinuten>>
|★ |StartBis|

Gibt eine Uhrzeit an der an diese Zeitperiode endet. Diese ist exklusiv zu betrachten. Wenn StartBis kleiner ist als StartVon, dann ist StartBis am darauffolgenden Tag von StartVon. Wenn StartVon und StartBis irrelevant sind, kann hier 24:00 Uhr eingetragen werden.


Datentyp: <<UhrzeitMinuten,UhrzeitMinuten>>
|★ |DauerMax|

DauerMax definiert die maximale Nutzungsdauer für die diese Zeitperiode gewählt werden kann. Diese Dauer bezieht sich auf die Gesamtnutzung, auch wenn diese sich durch mehrere Zeitperioden zieht. Diese Dauer ist inklusiv zu betrachten.

Bsp. Daten für Bsp. 1 und 2

* StartVon = 07:00 Uhr, StartBis = 17:00 Uhr, DauerMax = 48h, SortOrder = 1, ID_Sortengruppe = 1

* StartVon = 17:00 Uhr, StartBis = 07:00 Uhr, DauerMax = 48h, SortOrder = 2, ID_Sortengruppe = 2

* StartVon = 00:00 Uhr, StartBis = 24:00 Uhr, DauerMax = 144h, SortOrder = 3, ID_Sortengruppe = 3

Bsp 1: Nutzung von 01.01. 15:00 Uhr bis 03.01. 06:00 Uhr, Nutzungsdauer 39h => ID_Sortengruppe 1 und 2 treten abwechselnd in Kraft, da diese Beiden durch die Sortorder bevorzugt werden und den gesamten Nutzungszeitraum abdecken wird der 3. Datensatz nicht betrachtet.

Bsp 2: Nutzung von 01.01. 15:00 Uhr bis 05.01. 06:00 Uhr, Nutzungsdauer 63h => ID_Sortengruppe 1 und 2 sind durch DauerMax ausgeschlossen -> ID_Sortengruppe 3 tritt in Kraft


Datentyp: <<DauerMinuten,DauerMinuten>>
| |Ueberhang|

Der Überhang definiert eine Toleranz-Zeitspanne für die die Nutzung der Zeitperiode überschritten werden darf ohne in eine neue Zeitperiode zu kommen.

Bsp. Daten für Bsp. 1 und 2

* StartVon = 07:00 Uhr, StartBis = 17:00 Uhr, Ueberhang = 2h, SortOrder = 1, ID_Sortengruppe = 1

* StartVon = 17:00 Uhr, StartBis = 07:00 Uhr, Ueberhang = 2h, SortOrder = 2, ID_Sortengruppe = 2

Bsp 1: Nutzung von 01.01. 05:00 Uhr bis 01.01. 08:00 Uhr => ID_Sortengruppe 2 tritt in Kraft, da die 2h nach 07:00 Uhr nicht überschritten wurden.

Bsp 2: Nutzung von 01.01. 05:00 Uhr bis 01.01. 10:00 Uhr => ID_Sortengruppe 2 tritt bis 07:00 Uhr in Kraft, da die 2h überschritten wurden. Ab 07:00 Uhr gilt ID_Sortengruppe 1.


Datentyp: <<DauerMinuten,DauerMinuten>>
| |SortOrder|

Definiert aufsteigend die Reihenfolge, in der die Regeln ausgewertet werden. Es gelten immer die Regeln, die als Erstes die komplette Nutzungsperiode abdecken.


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Kann eine textuelle Beschreibung dieser Regel beinhalten. Diese ist nicht zur Verwendung von Vertriebsendgeräten vorgesehen.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Strecke_Type]]
==== Strecke


Strecke eines Streckentarifs.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Strecke|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_StreckencodeStart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_StreckencodeZiel|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |Entfernung|

Entfernungswert der Strecke zur Tarifberechnung.


Datentyp: <<INT4,INT4>>
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Via|

Nummer der Viatexte für diese Strecke. Verweis auf Vias.


Datentyp: <<INT4,INT4>>
| |ID_Streckenart|

Definiert Verkaufbarkeitseinschränkungen dieser Strecke.


Datentyp: <<ID_Streckenart_Type,ID_Streckenart>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Strecke


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Streckencode_Type]]
==== Streckencode


Analog zum Relationscode kombiniert ein ID_Streckencode zu einem oder mehreren ID_Tarifpunkten. Anders als Relationscodes sind Streckencodes aber Tarifgebiethomogen.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Streckencode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Streckencodetyp|

Typ dieses Streckencodes (dieses Haltepunktes).


Datentyp: <<ID_Streckencodetyp_Type,ID_Streckencodetyp>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diesen Streckencode.


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Streckenzuordnung_Type]]
==== Streckenzuordnung


Ordnet eine Strecke einem oder mehreren Teilrelationen zu.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Strecke|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Teilrelation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Schlüssel des Tarifgebers für diese Strecke-Teilrelations Zuordnung.


Datentyp: string
|=======================
  ★  Pflichtelemente

[[Tarifarten_Type]]
==== Tarifarten


Gruppierungs- (Sorten via SortenTarifarten) und Differenzierungsattribut (Teilrelationen, Preisstufendirektwahlen). Damit lassen sich z.B. eigene Relationen für ganze Gruppen von Fahrscheinensorten vom allgemeinen Fall abtrennen (Bartarif/Zeittarif).

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Zum Beispiel: 0=Allgemein, 1=Bartarif, 2=Zeittarif


Datentyp: string
| |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Tarifgebiete_Type]]
==== Tarifgebiete


Tarifgebiet ist eine logische Einheit, die alle Tarifelemente eines Tarifgebers zusammenfasst

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |BezeichnungKurz|
[red]#_todo: Doku_#


Datentyp: string
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |Erstellungsdatum|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |Version|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Tarifpunkte_Type]]
==== Tarifpunkte

Ein Tarifpunkt dient der Zusammenfassung (ein oder) mehrerer Haltestellen aus Tarifsicht (weil Fahrten zu diesen bzw. von diesen Haltestellen immer zum gleichen Preis führen). Ein Tarifpunkt hat eine Nummer und ggf. auch einen Namen. Außerdem ist ein Tarifpunkt genau einem Tarifgebiet zugeordnet. Tarifpunkte werden zum Aufdruck auf Fahrscheinen benötigt um eine Kontrolle der räumlichen Gültigkeit zu ermöglichen. In vielen Tarifsystemen haben Tarifpunkte Namen wie: Zone oder Ring. Tarifpunkte bilden Endpunkte in der Tarifmatrix: Von-Tarifpunk -> Nach-Tarifpunkt -> Preisstufe

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifgebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Tarifpunkttyp|

1=Zone/Wabe/Ring/Tarifpunkt 2=Wabentyp (Zusammenfassung mehrere Elemente von Typ 1) 3=Tarifhaltestelle 4=Ortsteil (in seiner Funktion als Tarifpunkt) 5=Ort (Zusammenfassung mehrere Ortsteile)


Datentyp: <<ID_Tarifpunkttyp_Type,ID_Tarifpunkttyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |BezeichnungDruck|
[red]#_todo: Doku_#


Datentyp: string
| |ID_TarifpunktReferenz|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[TarifpunktmengeElemente_Type]]
==== TarifpunktmengeElemente


Eintrag in einer geordneten Menge von Tarifpunkten.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_TarifpunktmengeElement|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunktmenge|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|=======================
  ★  Pflichtelemente

[[Tarifpunktmengen_Type]]
==== Tarifpunktmengen

Eine Tarifpunktmenge umfasst die Menge der ihr zugeordneten Tarifpunkte in Form von TarifpunktmengeElementen. Über eine Tarifpunktmenge können somit bspw. alle Zonen eines Fahrtverlaufs oder alle erlaubten Zonen zu einer ausgewählten Verbindung abgebildet werden.

RaeumlicheGueltigkeits-Elemente und SortengruppenErmittlungen können auf Tarifpunktmengen verweisen.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifpunktmenge|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Tarifrelevantepunkte_Type]]
==== Tarifrelevantepunkte


OTP - Orte und tarifrelevante Punkte. Unabhhänig von konkreten Haltestellen bieten tarifrelevante Punkte die Möglichkeit, dem Bediener Reiseziele anzubieten, zu denen einen Verkauf erfolgen soll. Jedem OTP ist genau ein Relationscode zugeordnet, über den Relationen gesucht werden.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifrelevanterpunkt|

Eindeutiger DS-Index innerhalb der ID_Zeitraum


Datentyp: <<INT4,INT4>>
|★ |ID_OTPTyp|
[red]#_todo: Doku_#


Datentyp: <<ID_OTPTyp_Type,ID_OTPTyp>>
|★ |ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
|★ |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Relcode|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Bundesland|
[red]#_todo: Doku_#


Datentyp: <<ID_Bundesland_Type,ID_Bundesland>>
| |ID_Ortspunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Sortengruppe|

Verweist auf eine Sortengruppe, die mit dieser Zielauswahl direkt verkauft wird (Festpreis, keine Relation)


Datentyp: <<INT4,INT4>>
| |Standortwahl_ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_TarifrelevanterpunktReferenz|

Über ID_TarifrelevanterpunktReferenz kann eine baumartige Auswahlstruktur definiert werden. Blätter und Knoten referenzieren über ID_TarifrelevanterpunktReferenz einen Elternknoten im selben Zeitraum. Die Bildung von Referenzbäumen ist optional. SortOrder definiert die Sortierung aller Kindknoten eines Elternknotens. Innerhalb der gleichen SortOrder werden die Knoten alphabetisch sortiert.


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Teilrelationen_Type]]
==== Teilrelationen


Relation (und Teilrelation) auf Tarifpunkt Ebene

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Teilrelation|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Tarifart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_TarifpunktStart|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |TarifpunktbezeichnungStart|
[red]#_todo: Doku_#


Datentyp: string
|★ |ID_TarifpunktZiel|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |TarifpunktbezeichnungZiel|
[red]#_todo: Doku_#


Datentyp: string
|★ |ID_Tarifgebiet|

Die ID_Tarifgebiet bleibt als retundante Information erhalten. Sie muss aber mit der ID_Tarifgebiet der Preisstufe übereinstimmen.


Datentyp: <<INT4,INT4>>
|★ |ID_Preisstufe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Preisquelle|
[red]#_todo: Doku_#


Datentyp: <<ID_Preisquelle_Type,ID_Preisquelle>>
| |ID_Komfortklasse|

Hinweis zur Komfortklasse (1.Klasse/2.Klasse etc).


Datentyp: <<ID_Komfortklasse_Type,ID_Komfortklasse>>
| |AlternativePreisGruppe|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |EinnahmeAufteilung|
[red]#_todo: Doku_#


Datentyp: string
| |ViabezeichnungDruck|

alternativer Via-Drucktext, hat Vorrang vor dem Drucktext des Via-Datensatzes


Datentyp: string
| |ViabezeichnungRueckDruck|

alternativer Via-Drucktext für den umgekehrte Streckenverlauf, hat Vorrang vor dem Drucktext_Rueck des Via-Datensatzes. Wenn ViaDrucktext_Rueck leer ist, aber ViaDrucktext gefüllt hat ViaDrucktext Vorrang vor Drucktext_Rueck bzw. Drucktext des Via-Datensatzes.


Datentyp: string
| |ID_RaeumlicheGueltigkeit|

Verweis auf eine Definition für die räumliche Gültigkeit.


Datentyp: <<INT4,INT4>>
| |ID_RaeumlicheGueltigkeit_Rueck|

Optionale Referenz auf eine Tarifpunktmenge für den Rückweg.


Datentyp: <<INT4,INT4>>
| |ID_Linie|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Referenz der zugrunde liegenden Information zu einer Datenmenge des Tarifgebers.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Vias_Type]]
==== Vias


Gesamt Relationsinformation

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Via|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|

Text zur Auswahl der Variante, Teilstrecken mit '*' getrennt


Datentyp: string
| |BezeichnungDruck|

Drucktext, Teilstrecken mit '*' getrennt


Datentyp: string
| |BezeichnungRueck|

Text zur Auswahl der Variante in der Rückrichtung, Teilstrecken mit '*' getrennt


Datentyp: string
| |BezeichnungRueckDruck|

Drucktext in der Rückrichtung, Teilstrecken mit '*' getrennt


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Wege_Type]]
==== Wege


Fahrtnummer, Kursnummer

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Weg|
Eindeutige Nummer des Weges.

Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Wegpositionen_Type]]
==== Wegpositionen


Ortsposition innerhalb der Fahrt

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Wegposition|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Weg|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |SortOrder|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Ortspunkt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Bediengebiet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Entfernung|

Entfernung vom vorhergehenden Ortspunkt in Metern


Datentyp: <<INT4,INT4>>
| |Fangbereich|

optionaler Fangbereich der Wegposition in Metern für eine GPS Ortung - überschreibt eine entsprechende Angabe bei der Ortspunktdefinition


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Zusatzsorten_Type]]
==== Zusatzsorten

Zusatzsorten sind Anschluss- und Anstossprodukte, die in Abhängigkeit von Preisstufe, bereits gewählter Sorte und Relation angeboten werden

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Zusatzsorte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Sorte|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ZuordnungRelCodeGrp|
[red]#_todo: Doku_#


Datentyp: <<ZuordnungRelCodeGrp_Type,ZuordnungRelCodeGrp>>
| |Anbindung|
[red]#_todo: Doku_#


Datentyp: <<ZusSorteAnbindung_Type,ZusSorteAnbindung>>
| |Zusatzsortentyp|

(Bedeutung projektspezifisch. MENT:1=Flächenanstoß, 2=Zusatzanstoß, 3=Streckenanstoß)


Datentyp: <<INT4,INT4>>
| |ID_Preisstufe|

Fremdschlüssel zur Produktbildung - wenn angegeben, wird diese Preisstufe fest zur Preisbestimmung verwendet. Die Angabe hat Vorrang vor ID_PreisstufenGrenze.


Datentyp: <<INT4,INT4>>
| |ID_PreisstufeGrenze|

wenn nicht vorhanden (und ID_Preisstufe nicht vorhanden) - alle Preisstufen möglich sonst alle Preisstufen mit ID_Preisstufe kleiner gleich ID_PreisstufeGrenze


Datentyp: <<INT4,INT4>>
| |Hinweistext|

z.B. für Zusatzinfo auf Quittungsausdruck – nicht bei Direktverkauf!


Datentyp: string
| |ID_SortengruppeHauptsorten|

Verweis auf SortenGruppe mit erlaubten Hauptsorten


Datentyp: <<INT4,INT4>>
| |ID_RelcodegruppeStart|

Verweis auf RelCodeGruppe die erlaubte RelCode_Start der Hauptrelation gruppiert = Vorlauf


Datentyp: <<INT4,INT4>>
| |ID_RelcodegruppeZiel|

Verweis auf RelCodeGruppe die erlaubte RelCode_Ziel der Hauptrelation gruppiert = Nachlauf


Datentyp: <<INT4,INT4>>
| |Direktverkauf|

False="immer mit Hauptsorte", True="Direktverkauf ohne Hauptsorte, falls Verkaufsort in Gruppierung durch VerkaufsRelCode enthalten"


Datentyp: boolean
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

=== TarifAngebot Enumerationen 


[[ID_ErmittlungseinheitHUSST_Type]]

[[ID_Ermittlungseinheit_Type]]

==== ID_Ermittlungseinheit

Die HUSST definiert ID_Ermittlungseinheit kleiner 1000 

Die ID_Ermittlungseinheit ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Minuten

|2|

Kilometer

|=======================


Verwendet in:

* <<DefErmittlungseinheit_Type,DefErmittlungseinheit>>
* <<PreisstufenErmittlungen_Type,PreisstufenErmittlungen>>


[[ID_FahrgasttypHUSST_Type]]

[[ID_Fahrgasttyp_Type]]

==== ID_Fahrgasttyp

Die HUSST definiert ID_Fahrgasttyp kleiner 1000 angelehnt an VDV-KA Kundentyp 

Die ID_Fahrgasttyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Erwachsener
|2|
Kind
|3|
Student
|5|
Behinderter
|6|
Sehbehinderter
|7|
Hörgeschädigter
|8|
Arbeitsloser/Sozialhilfeempfänger
|9|
Personal
|10|
Militärangehöriger
|19|
Schüler
|20|
Azubi
|25|
Senior
|64|
ermäßigt
|65|
Fahrrad
|66|
Hund
|=======================


Verwendet in:

* <<DefFahrgasttyp_Type,DefFahrgasttyp>>
* <<Sorten_Type,Sorten>>


[[ID_KomfortklasseHUSST_Type]]

[[ID_Komfortklasse_Type]]

==== ID_Komfortklasse

Die HUSST definiert ID_Komfortklasse kleiner 1000 angelehnt an VDV-KA ServiceKlasse (reserviert: 0-255) 

Die ID_Komfortklasse ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
1. Klasse
|2|
2. Klasse
|300|
Übergang von der 2. zur 1. Klasse
|=======================


Verwendet in:

* <<DefKomfortklasse_Type,DefKomfortklasse>>
* <<Sorten_Type,Sorten>>
* <<Teilrelationen_Type,Teilrelationen>>


[[ID_NachbarhaltestellenbeziehungHUSST_Type]]

[[ID_Nachbarhaltestellenbeziehung_Type]]

==== ID_Nachbarhaltestellenbeziehung

Die HUSST definiert ID_Nachbarhaltestellenbeziehung kleiner 1000 

Die ID_Nachbarhaltestellenbeziehung ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|

nicht spezifiziert/unbestimmt

|1|

Kurzstrecke

|=======================


Verwendet in:

* <<DefNachbarhaltestellenbeziehung_Type,DefNachbarhaltestellenbeziehung>>
* <<Nachbarhaltestellen_Type,Nachbarhaltestellen>>


[[ID_OTPTypHUSST_Type]]

[[ID_OTPTyp_Type]]

==== ID_OTPTyp

Die HUSST definiert OTPTypen kleiner 1000 

Die ID_OTPTyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Standort

Zu jedem Tarifrelevantenpunkt vom OTPTyp Standort muss es einen eindeutigen Ortspunkt geben. (Über ID_Ortspunkt verwiesen) => Es darf kein Ortspunkt mit 2 oder mehr verwiesenden Tarifrelevantenpunkten vom OTPTyp Standort geben.

Über diesen Ortspunkt ist der Standort eines Vertriebsgerätes synchronisierbar. Z.B. über seine IBISnr oder ReferenzExtern

|2|
Startpunkt
|3|
Zielpunkt
|4|
Viapunkt
|=======================


Verwendet in:

* <<DefOTPTyp_Type,DefOTPTyp>>
* <<Tarifrelevantepunkte_Type,Tarifrelevantepunkte>>


[[ID_OrtspunkttypHUSST_Type]]

[[ID_Ortspunkttyp_Type]]

==== ID_Ortspunkttyp
Die HUSST definiert Ortspunkttypen kleiner 1000

Die ID_Ortspunkttyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Haltestelle
|2|
Betriebshof
|3|
Zone/Wabe/Ring
|5|
Gemeinde
|=======================


Verwendet in:

* <<DefOrtspunkttyp_Type,DefOrtspunkttyp>>
* <<Ortspunkte_Type,Ortspunkte>>


[[ID_PreisfindungHUSST_Type]]

[[ID_Preisfindung_Type]]

==== ID_Preisfindung

Die HUSST definiert ID_Preisfindung kleiner 1000 Bit 0=Festpreis Bit 1=Relationsbezogen (nicht mit Bit 0 kombinierbar) Bit 2=Preisstufenupgrade (nur mit Bit 1 kombinierbar) Bit 8=Freie Preiseingabe (mit allen kombinierbar) 

Die ID_Preisfindung ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Festpreis
|2|
Relationsbezogen
|6|

Relationsbezogen mit Preisstufenupgrade

|257|

Festpreis mit freier Preiseingabe

|258|

Relationsbezogen mit freier Preiseingabe

|262|

Relationsbezogen mit Preisstufenupgrade und freier Preiseingabe

|=======================


Verwendet in:

* <<DefPreisfindung_Type,DefPreisfindung>>
* <<Sorten_Type,Sorten>>


[[ID_PreisspaltentypHUSST_Type]]

[[ID_Preisspaltentyp_Type]]

==== ID_Preisspaltentyp
Die HUSST definiert ID_Preisspaltentyp kleiner 1000

Die ID_Preisspaltentyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Standard / Standardpreisspalte für den allgemeinen Verkauf
|=======================


Verwendet in:

* <<DefPreisspaltentyp_Type,DefPreisspaltentyp>>
* <<Preisspalten_Type,Preisspalten>>


[[ID_RabattklasseHUSST_Type]]

[[ID_Rabattklasse_Type]]

==== ID_Rabattklasse

Die HUSST definiert ID_Rabattklasse kleiner 1000 angelehnt an VDV-KA RabattParameter 

Die ID_Rabattklasse ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
Keine Ermäßigung
|1|

prozentuale Ermäßigung Level-1 (z.B. Bahncard 25)

|2|

prozentuale Ermäßigung18 Level-2 (z.B. Bahncard 50)

|3|

prozentuale Ermäßigung Level-3

|4|

prozentuale Ermäßigung Level-4

|5|

prozentuale Ermäßigung Level-5

|6|

Ermäßigung auf Basis gefahrener Kilometer

|46|

Ermäßigung des Ticketkaufs mit KA-Bezahlberechtigung um 25%

|=======================


Verwendet in:

* <<DefRabattklasse_Type,DefRabattklasse>>
* <<Sorten_Type,Sorten>>


[[ID_ReisetypHUSST_Type]]

[[ID_Reisetyp_Type]]

==== ID_Reisetyp

Die HUSST definiert ID_Reisetyp kleiner 1000 

Die ID_Reisetyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Standard (passend zum Sortentyp)
|2|
Hin- und Rückfahrt
|3|
Rundreise
|=======================


Verwendet in:

* <<DefReisetyp_Type,DefReisetyp>>
* <<Sorten_Type,Sorten>>


[[ID_RelationenberechnungsregelungHUSST_Type]]

[[ID_Relationenberechnungsregelung_Type]]

==== ID_Relationenberechnungsregelung

Die HUSST definiert ID_Relationenberechnungsregelung kleiner 1000 

Die ID_Relationenberechnungsregelung ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Standard. Alle Teilrelationen sind gleichwertig und haben verschiedene Tarifarten und oder Tarifgebiete. Die gewählte Sorte entscheidet, welche Teilrelation genutzt wird.

|2|

Sortorder1 Die Teilrelation mit Sortorder 1 muss bepreist werden, die anderen Teilrelationen werden zusätzlich registriert. Die Teilrelationen können aus verschiedenen Tarifgebieten sein und / oder verschiedene Tarifarten aufweisen.

|3|

AdditionPreise Die Preise aller Teilrelationen werden addiert, es werden alle Teilrelationen registriert. Die Teilrelationen können aus verschiedenen Tarifgebieten sein und / oder verschiedene Tarifarten aufweisen. Für die Bepreisung muss eine Sortengruppe zur Verfügung stehen, in der jeweils eine Sorte zu mindestens einer Teilrelation passt.

|4|

AdditionPreisstufen Die gewählte Sorte entscheidet über ihre Tarifart(en), welche Teilrelation(en) für die Preisfindung und die Registrierung verwendet werden. Nicht passende Teilrelationen werden ignoriert. Damit ist sichergestellt, dass alle verwendeten Teilrelationen aus einem Tarifgebiet stammen. Die Preisstufen der Teilrelationen werden addiert und dazu der Preis der Sorte ermittelt, alle diese Teilrelationen werden registriert.

|=======================


Verwendet in:

* <<DefRelationenberechnungsregelung_Type,DefRelationenberechnungsregelung>>
* <<Relationen_Type,Relationen>>


[[ID_RelationendruckregelungHUSST_Type]]

[[ID_Relationendruckregelung_Type]]

==== ID_Relationendruckregelung

Die HUSST definiert ID_Relationendruckregelung kleiner 1000 

Die ID_Relationendruckregelung ist entweder eine von HUSST vordefinierte Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Ein. Es wird ein Ticket gedruckt.

|2|

Alle Es wird ein Ticket pro Telrelation gedruckt.

|3|

Tarifgebiet. Alle Teilrelationen eines Tarifgebietes werden mit je einem Ticket gedruckt.

|=======================


Verwendet in:

* <<DefRelationendruckregelung_Type,DefRelationendruckregelung>>
* <<Relationen_Type,Relationen>>


[[ID_RelcodegruppentypHUSST_Type]]

[[ID_Relcodegruppentyp_Type]]

==== ID_Relcodegruppentyp
Die HUSST definiert ID_Relcodegruppentyp kleiner 1000

Die ID_Relcodegruppentyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Magnet
|2|
Startort
|=======================


Verwendet in:

* <<DefRelationscodegruppentyp_Type,DefRelationscodegruppentyp>>
* <<Relationscodegruppen_Type,Relationscodegruppen>>


[[ID_SortenausgaberegelungHUSST_Type]]

[[ID_Sortenausgaberegelung_Type]]

==== ID_Sortenausgaberegelung

Die HUSST definiert ID_Sortenausgaberegelung kleiner 1024 Die Werte ergeben sich aus allen 32 möglichen Bitkombinationen der ersten 5 Bit.

Bit 0=Papierfahrschein Bit 1=EFS (z.B. Chipkarte) Bit 2=Handy Ticket Bit 3=Papierfahrschein mit Barcode Bit 4=EFS und Papierfahrschein [mit Barcode] 

Die ID_Sortenausgaberegelung ist entweder eine von HUSST vordefinierter Zahl kleiner 1024 oder eine im Projekt vereinbarte Zahl größer gleich 1024.

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Papierfahrschein
|2|
EFS (z.B. Chipkarte)
|4|
Handy Ticket
|8|
Papierfahrschein mit Barcode
|16|

EFS und Papierfahrschein [mit Barcode]

|3|

Papierfahrschein / EFS (z.B. Chipkarte)

|5|

Papierfahrschein / Handy Ticket

|9|

Papierfahrschein / Papierfahrschein mit Barcode

|17|

Papierfahrschein / EFS und Papierfahrschein [mit Barcode]

|6|

EFS (z.B. Chipkarte) / Handy Ticket

|10|

EFS (z.B. Chipkarte) / Papierfahrschein mit Barcode

|18|

EFS (z.B. Chipkarte) / EFS und Papierfahrschein [mit Barcode]

|12|

Handy Ticket / Papierfahrschein mit Barcode

|20|

Handy Ticket / EFS und Papierfahrschein [mit Barcode]

|24|

Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|7|

Papierfahrschein / EFS (z.B. Chipkarte) / Handy Ticket

|11|

Papierfahrschein / EFS (z.B. Chipkarte) / Papierfahrschein mit Barcode

|19|

Papierfahrschein / EFS (z.B. Chipkarte) / EFS und Papierfahrschein [mit Barcode]

|13|

Papierfahrschein / Handy Ticket / Papierfahrschein mit Barcode

|21|

Papierfahrschein / Handy Ticket / EFS und Papierfahrschein [mit Barcode]

|25|

Papierfahrschein / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|14|

EFS (z.B. Chipkarte) / Handy Ticket / Papierfahrschein mit Barcode

|22|

EFS (z.B. Chipkarte) / Handy Ticket / EFS und Papierfahrschein [mit Barcode]

|26|

EFS (z.B. Chipkarte) / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|28|

Handy Ticket / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|15|

Papierfahrschein / EFS (z.B. Chipkarte) / Handy Ticket / Papierfahrschein mit Barcode

|23|

Papierfahrschein / EFS (z.B. Chipkarte) / Handy Ticket / EFS und Papierfahrschein [mit Barcode]

|27|

Papierfahrschein / EFS (z.B. Chipkarte) / Papierfahrschein mit Barcode /

|30|

EFS (z.B. Chipkarte) / Handy Ticket / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|29|

Papierfahrschein / Handy Ticket / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|31|

Papierfahrschein / EFS (z.B. Chipkarte) / Handy Ticket / Papierfahrschein mit Barcode / EFS und Papierfahrschein [mit Barcode]

|=======================


Verwendet in:

* <<DefSortenausgaberegelung_Type,DefSortenausgaberegelung>>
* <<Sorten_Type,Sorten>>


[[ID_SortendruckregelungHUSST_Type]]

[[ID_Sortendruckregelung_Type]]

==== ID_Sortendruckregelung

Die HUSST definiert ID_Sortendruckregelung kleiner 1000 

Die ID_Sortendruckregelung ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Druck über Layout
|2|
Vorrangiger Druck über ein zum Verkaufszeitpunkt zugeordnetes Hauptprodukt, sonst über Layout.
|3|

Druck eines 2. Fahrscheins mit einer Druckinformation "2. Druck" die im Layout ausgewertet werden kann.

|=======================


Verwendet in:

* <<DefSortendruckregelung_Type,DefSortendruckregelung>>
* <<Sorten_Type,Sorten>>


[[ID_SortengruppentypHUSST_Type]]

[[ID_Sortengruppentyp_Type]]

==== ID_Sortengruppentyp

Die HUSST definiert ID_Sortengruppentyp sind in verschiedene Bereicht geklustert: 1-10 Verkaufssortengruppe 11-20 Zusatzsortengruppen 21-30 Gruppenfahrschein 31-40 SortengruppenErmittlung-Gruppen 

Die ID_Sortengruppentyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Verkaufssortengruppe Relation Mit der "Verkaufssortengruppe Relation" werden alle Sorten zusammengefasst, die aufgrund von Serviceklasse, Rabattklasse und Fahrgasttyp untereinander austauschbar sind und deren Preisstufe über eine Reisewegauswahl  (i.d.R. Relation) ermittelt wird. 

|2|

Verkaufssortengruppe Festpreis Diese Sortengruppen werden beim Verkauf ohne Relationsauswahl angeboten.

|3|

Verkaufssortengruppe Kombi Diese Sortengruppen fassen Sorten zusammen, die in Kombination angeboten werden können. Die Auswahlsorte soll SortOrder 1 haben. Beispiel: Einfache Fahrt 2. Klasse + Hundeticket + Fahrrad bzw. Hin- und Rückfahrt 2. Klasse + Hundeticket Hin-/Rück + Fahrrad

|11|

Hauptsorten zu Zusatzsorten Unter dem Sortengruppentyp werden Sorten zusammengefasst, die als Hauptsorte zu einem oder mehreren Zusatzsorten definiert sind. In den Zusatzsorten wird im Attribut "ID_SortengruppeHauptsorten" auf die Sortengruppe von diesem Typ verwiesen.

|21|

Gruppenfahrschein Ist für Gruppenfahrscheine, bei denen zusammen unterschiedlich Ausprägungen auf ein Ticket gedruckt werden. Bsp.: Ein Fahrschein mit x Erwachsenen und y Kindern. Es werden die Auswahlsorte und die Ausprägungen in eine Gruppe zusammengefasst. Die Auswahlsorte soll Sortorder 1 haben.

|31|

SortengruppenErmittlung Ist für Referenzen vom SortengruppenErmittlungen_Type. (s. SortengruppenErmittlungen_Type)

|=======================


Verwendet in:

* <<DefSortengruppentyp_Type,DefSortengruppentyp>>
* <<Sortengruppen_Type,Sortengruppen>>


[[ID_SortentypHUSST_Type]]

[[ID_Sortentyp_Type]]

==== ID_Sortentyp

Die HUSST vordefinierten Sortentypen sind in verschiedene Bereiche geklustert: 1- 10 Bar 11- 20 Zeit 21- 30 Artikel 31- 40 Einzahlungen 41- 50 Leihgeld 991-999 Spezial 

Die ID_Sortentyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Einzelkarte
|2|
Mehrfahrten
|3|
Zähler
|11|
Tageskarte
|12|
Wochenkarte
|13|
Monatskarte
|14|
Halbjahreskarte
|15|
Jahreskarte
|21|
Artikel
|22|
Gutschein (Verkauf)
|23|
Gutschein (Annahme)
|24|
Gutschein (Restwert)
|31|
Verkäufer Einzahlung
|32|
Abo Einzahlung
|33|
EBE Einzahlung
|39|
Sonstige Einzahlung
|41|
Pfand (z.B. für Kundendatenträger)
|42|
Kaution
|991|
Fehleinnahme
|992|
Bargutschrift (Überzahlung / Restgeldquittung etc.)
|999|
Sonstige
|=======================


Verwendet in:

* <<DefSortentyp_Type,DefSortentyp>>
* <<Sorten_Type,Sorten>>


[[ID_StreckenartHUSST_Type]]

[[ID_Streckenart_Type]]

==== ID_Streckenart

Die HUSST definiert ID_Streckenart kleiner 1000. 

Die ID_Streckenart ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

keine Sonderverkaufslogik

|2|

Strecke nur kombiniert mit ID_Streckenart=1 verkaufbar

|3|

nur als Einzelstrecke verkaufbar

|=======================


Verwendet in:

* <<DefStreckenart_Type,DefStreckenart>>
* <<Strecke_Type,Strecke>>


[[ID_StreckencodetypHUSST_Type]]

[[ID_Streckencodetyp_Type]]

==== ID_Streckencodetyp

Die HUSST definiert ID_Streckencodetyp kleiner 1000. 

Die ID_Streckencodetyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

AST Anstoßbahnhof

|2|

NAST Nichtanstoßbahnhof

|3|

NE-Haltepunkt

|=======================


Verwendet in:

* <<DefStreckencodetyp_Type,DefStreckencodetyp>>
* <<OrtspunktStreckencode_Type,OrtspunktStreckencode>>
* <<Streckencode_Type,Streckencode>>


[[ID_TarifpunkttypHUSST_Type]]

[[ID_Tarifpunkttyp_Type]]

==== ID_Tarifpunkttyp
Die HUSST definiert Tarifpunkttypen kleiner 1000

Die ID_Tarifpunkttyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Tarifhaltestelle (falls jede Hst ein eigener Tarifpunkt bildet)
|2|
Zone / Wabe / Ring (unmittelbar einer Tarifhaltestelle zugeordnet)
|3|
Überzone / Wabentyp (faßt Tarifpunkte vom Typ 2 oder 1 zusammen)
|4|
Region (faßt Überzonen zu Regionen zusammen)
|5|
Ortsteil (in seiner Funktion als Tarifpunkt)
|6|
Ort (faßt Ortsteile zusammen)
|=======================


Verwendet in:

* <<DefTarifpunkttyp_Type,DefTarifpunkttyp>>
* <<Tarifpunkte_Type,Tarifpunkte>>


[[ID_VertriebswegeHUSST_Type]]

[[ID_Vertriebswege_Type]]

==== ID_Vertriebswege

Die HUSST definiert ID_Vertriebswege kleiner 1024 

Die ID_Vertriebswege ist entweder eine von HUSST vordefinierter Zahl kleiner 1024 oder eine im Projekt vereinbarte Zahl größer gleich 1024.

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|=======================


Verwendet in:

* <<DefVertriebswege_Type,DefVertriebswege>>
* <<Preisstufendirektwahl_Type,Preisstufendirektwahl>>
* <<Relationen_Type,Relationen>>
* <<Sorten_Type,Sorten>>


[[ID_ZahlgrenzentypHUSST_Type]]

[[ID_Zahlgrenzentyp_Type]]

==== ID_Zahlgrenzentyp
Die ID_Zahlgrenzentyp ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. 
Die HUSST definiert ID_Zahlgrenzentyp kleiner 1000
[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Anzahl Haltestellen
|2|
Tarifkilometer
|3|
Radius (Luftlinie)
|=======================


Verwendet in:

* <<DefZahlgrenzentyp_Type,DefZahlgrenzentyp>>
* <<Nachbarhaltestellen_Type,Nachbarhaltestellen>>


[[ID_ZahlungsartenHUSST_Type]]

[[ID_Zahlungsarten_Type]]

==== ID_Zahlungsarten
Die ID_Zahlungsarten ist entweder eine von HUSST vordefinierter Zahl kleiner 1024 oder eine im Projekt vereinbarte Zahl größer gleich 1024. 

Die HUSST definiert ID_Zahlungsart kleiner 1024

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|

Barzahlung

|2|

Kartenzahlung (Schließt alle Arten der Kartenzahlung ein, die das System unterstützt)

|4|

KA-Zahlung (POB, PEB und WEB)

|8|

Rechnung

|0|

Keine

|3|

Barzahlung / Kartenzahlung

|5|

Barzahlung / KA-Zahlung

|6|

Kartenzahlung / KA-Zahlung

|7|

Barzahlung / Kartenzahlung / KA-Zahlung

|9|

Barzahlung / Rechnung

|10|

Kartenzahlung / Rechnung

|11|

Barzahlung / Kartenzahlung / Rechnung

|12|

KA-Zahlung / Rechnung

|13|

Barzahlung / KA-Zahlung / Rechnung

|14|

Kartenzahlung / KA-Zahlung / Rechnung

|15|

Barzahlung / Kartenzahlung / KA-Zahlung / Rechnung

|=======================


Verwendet in:

* <<DefZahlungsarten_Type,DefZahlungsarten>>
* <<Sorten_Type,Sorten>>


[[KA_Kundentyp_CODE_Type]]


==== KA_Kundentyp_CODE

Aus der KA (XML-Schema_KVP_DL_PV.xsd): Der Kundentyp_CODE klassifiziert Kunden bzgl. typischer tarifrelevanter Kundengruppen des OePV. BOM 6-38

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Erwachsener
|2|
Kind
|3|
Student
|5|
Behinderter
|6|
Sehbehinderter
|7|
Hörgeschädigter
|8|
Arbeitsloser/Sozialhilfeempfänger
|9|
Personal
|10|
Militärangehöriger
|19|
Schüler
|20|
Azubi
|25|
Senior
|=======================


Verwendet in:

* <<Sorten_Type,Sorten>>


[[KA_Profil_CODE_Type]]


==== KA_Profil_CODE

Aus der KA (XML-Schema_KVP_DL_PV.xsd): Typ: klassifiziert Kunden, Objekte, etc. bzgl. tarifrelevanter Gruppen des OePV BOM 6_45

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Erwachsener
|2|
Kind
|3|
Student
|5|
Behinderter
|6|
Sehbehinderter
|7|
Hörgeschädigter
|8|
Arbeitsloser/Sozialhilfeempfänger
|9|
Personal
|10|
Militärangehöriger
|19|
Schüler
|20|
Azubi
|25|
Senior
|=======================


Verwendet in:

* <<Preise_Type,Preise>>


[[KA_RabattParameter_CODE_Type]]


==== KA_RabattParameter_CODE

Aus der KA: Der RabattParameter_CODE kennzeichnet einen Rabbatierungstyp bzw. Ermäßigungstyp. BOM 6-71

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
Keine Ermäßigung
|1|

prozentuale Ermäßigung Level-1 (z.B. Bahncard 25)

|2|

prozentuale Ermäßigung18 Level-2 (z.B. Bahncard 50)

|3|

prozentuale Ermäßigung Level-3

|4|

prozentuale Ermäßigung Level-4

|5|

prozentuale Ermäßigung Level-5

|6|

Ermäßigung auf Basis gefahrener Kilometer

|46|

Ermäßigung des Ticketkaufs mit KA-Bezahlberechtigung um 25%

|=======================


Verwendet in:

* <<Preise_Type,Preise>>


[[KA_ServiceKlasse_CODE_Type]]


==== KA_ServiceKlasse_CODE

Aus der KA (XML-Schema_KVP_DL_PV.xsd): Der ServiceKlasse_CODE klassifiziert Servicequalitaeten der Transportdienstleistung. Haeufigstes Beispiel ist die Unterscheidung in 1. und 2. Klasse. BOM 6-49

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
1. Klasse
|2|
2. Klasse
|=======================


Verwendet in:

* <<Sorten_Type,Sorten>>


[[KA_TransportmittelKategorie_CODE_Type]]


==== KA_TransportmittelKategorie_CODE

Aus der KA (XML-Schema_KVP_DL_PV.xsd): Der TransportmittelKategorie_CODE klassifiziert Arten von Transportdienstleistungen im Sinne einer Qualitaetsklasse, z.B. "IC/EC", "ICE" bei der Deutschen Bahn. Diese Kategorien sind "marketinggetrieben" mit Auswirkungen auf den Preis und daher produktspezifisch. BOM 6-60

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Linienbus im Stadtverkehr
|3|
Metro/U-Bahn/S-Bahn
|4|
Straßenbahn/TRAM
|10|
ICE
|11|
Überlandbus/Regionalbus
|20|
IC
|29|
Regionalexpress
|30|
Expressbus
|31|
Flughafenzubringer
|32|
Verbundnahverkehr
|33|
Verbundnahverkehr ohne Kurzstrecke
|34|
SPNV
|=======================


Verwendet in:

* <<Sorten_Type,Sorten>>


[[Sammelbeleg_Type]]


==== Sammelbeleg
IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|true|
ein Fahrschein für n Personen
|false|
n Fahrscheine für n Personen
|auswahl|

Bediener entscheidet, ob ein oder n Fahrscheine gedruckt werden, bei n>1 Personen

|=======================

[[ZuordnungRelCodeGrp_Type]]


==== ZuordnungRelCodeGrp
teste diese Verwendung {nbsp}s. Verwendung in den ZusatzSorten_Type {nbsp}s. weiter Verwendungen

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|S|
StartRelCode
|Z|
ZielRelCode
|R|
StartZielRelCode
|=======================


Verwendet in:

* <<Zusatzsorten_Type,Zusatzsorten>>


[[ZusSorteAnbindung_Type]]


==== ZusSorteAnbindung
{nbsp}s. Verwendung in den ZusatzSorten_Type
[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|V|
Vorlauf
|N|
Nachlauf
|H|
Hauptlauf
|U|
Richtungsungebunden
|=======================


Verwendet in:

* <<Zusatzsorten_Type,Zusatzsorten>>



=== TarifAngebot Datentypen 


[[ID_PreisquelleHUSST_Type]]

[[ID_Preisquelle_Type]]

==== ID_Preisquelle

Die HUSST reserviert ID_Preisquelle kleiner 1000, aktuell werden keine Standard-Preisquellen definiert. 

Die ID_Preisquelle ist entweder eine von HUSST vordefinierter Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0


Verwendet in:

* <<DefPreisquelle_Type,DefPreisquelle>>
* <<Teilrelationen_Type,Teilrelationen>>


[[Umschalttag_Type]]


==== Umschalttag

Definiert den Zeitraum, in dem der Fahrschein im Voraus verkaufbar ist. Die Syntax der Formel wird in einer eigenen HUSST-Definition konkretisiert. todo: Olaf definiert, Horst formuliert reguläre Ausdrücke

[[Vorverkauf_Type]]


==== Vorverkauf

Definiert den Zeitraum, in dem der Fahrschein im Voraus verkaufbar ist. Die Syntax der Formel wird in einer eigenen HUSST-Definition konkretisiert. todo: Olaf definiert, Horst formuliert reguläre Ausdrücke


=== TarifAngebot Definitionsstand


HUSST Versorgungsdaten - Schemata: Tarif, Angebot (verwendet Basisversorgungsdaten) Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
