

===  Rootelement

[[husstPersonal_Type]]
==== husstPersonal

IMPORTANT: _todo: Doku_
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Bearbeitung|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Bearbeitung_Type,Bearbeitung>>
| |Interpretationen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Interpretationen_Type,Interpretationen>>
| |Unternehmen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Unternehmen_Type,Unternehmen>>
| |Updateinfo|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Updateinfo_Type,Updateinfo>>
| |VersionInhalt|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<VersionInhalt_Type,VersionInhalt>>
| |VersionStruktur|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<VersionStruktur_Type,VersionStruktur>>
| |Zeitraeume|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zeitraeume_Type,Zeitraeume>>
| |Zeitraumoptionen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zeitraumoptionen_Type,Zeitraumoptionen>>
| |DefIdentobjekttyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DefIdentobjekttyp_TypehusstDV:DefIdentobjekttyp_Type,DefIdentobjekttyp>>
| |DefPasswortHashtyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DefPasswortHashtyp_TypehusstDV:DefPasswortHashtyp_Type,DefPasswortHashtyp>>
| |Einsatzarten|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Einsatzarten_TypehusstDV:Einsatzarten_Type,Einsatzarten>>
| |Geraetetypen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Geraetetypen_TypehusstDV:Geraetetypen_Type,Geraetetypen>>
| |Geraet|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Geraet_TypehusstDV:Geraet_Type,Geraet>>
| |GeraeteEinsatztypen|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<GeraeteEinsatztypen_TypehusstDV:GeraeteEinsatztypen_Type,GeraeteEinsatztypen>>
| |Identobjekte|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Identobjekte_TypehusstDV:Identobjekte_Type,Identobjekte>>
| |PersonalIdentobjekte|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<PersonalIdentobjekte_TypehusstDV:PersonalIdentobjekte_Type,PersonalIdentobjekte>>
| |Personal|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Personal_TypehusstDV:Personal_Type,Personal>>
| |Personaleinsatz|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Personaleinsatz_TypehusstDV:Personaleinsatz_Type,Personaleinsatz>>
|=======================


Verwendet in: ohne Verwendung



===  Elemente


[[DefIdentobjekttyp_Type]]
==== DefIdentobjekttyp

Definiert einen Identifikationstyp zur Anmeldung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Identobjekttyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ID_Identobjekttyp_Type,ID_Identobjekttyp>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[DefPasswortHashtyp_Type]]
==== DefPasswortHashtyp

Definiert einen Hashtyp mit dem übergebene Passwörter gehasht wurden. Wird zum vergleichen von Passwörtern beötigt.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_PasswortHashtyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ID_PasswortHashtyp_Type,ID_PasswortHashtyp>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Einsatzarten_Type]]
==== Einsatzarten

Die Beschreibung für einen Personaleinsatz. Zum Beispiel: Verkäufer, Kontrolleur, Zugbegleiter, ...
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_EinsatzArt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ReferenzExtern|

Referenz zu einem extern definierten Element.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ID_Geraetetyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Geraet_Type]]
==== Geraet

Die Stammdaten zu einem Gerät mit Zuweisung zu einem Unternehmen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Geraet|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |KA_KvpOrgID|
KA KVP Nr

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_Unternehmen|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[GeraeteEinsatztypen_Type]]
==== GeraeteEinsatztypen

Einsatzart eines Gerätes, zur Differenzierung der Datenverteilung
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_GeraeteEinsatztyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Geraetetypen_Type]]
==== Geraetetypen


Der Gerätetyp ist Teil des Primärschlüssels eines Gerätes.  Er dient der Unterscheidung, um was für ein Gerät es sich handelt. Zum Beispiel: Verkaufstablett, Kontrollgerät, ...

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |Bezeichnung|
Name des Elements zur Verwendung in UI-Komponenten oder zum Ausdruck.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ReferenzExtern|

Referenz zu einem extern definierten Element.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Identobjekte_Type]]
==== Identobjekte


Ident Objekte zur Identifizierung einer Person. Die ID des Identobjektes ist über alle Objekttypen und Mandanten eindeutig zu halten.

Idealerweise sollten alle Identobjekte eines Objekttyps über alle Mandanten im System eindeutig sein.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Identobjekt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Identobjekttyp|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ID_Identobjekttyp_Type,ID_Identobjekttyp>>
| |Bezeichnung|

Freier Text, der z.B. zur Anzeige verwendet werden kann.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |ID_Unternehmen|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExtern|

Systemweit eindeutige Nummer/Kennung des Ident-Objektes z.B. zusammengesetzt aus ID_Identobjekttyp und Identobjekt_Schluessel ggf. mit ID_Unternehmen


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Personal_Type]]
==== Personal

Dient zur Übergabe von Personaldaten und Zuordnung zu dem Unternehmen.
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_Unternehmen|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_AbrUnternehmen|
Abrechnungs-Unternehmen, bei dem Einnahmen abgeliefert werden müssen

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_PasswortHashtyp|
Gibt den Hashtyp an mit dem das Passwort gehasht wurde.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ID_PasswortHashtyp_Type,ID_PasswortHashtyp>>
| |Passwort|

Gehashtes Passwort.  Wenn angegeben, ist ID_PasswortHashtyp zwingen anzugeben


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Vorname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Nachname|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |GueltigAb|

Da Personal zu jeder Zeit einem Unternehmen ein- und austreten kann, gibt es  zusätzlich zum Zeitraum die Möglichkeit ein Einstiegsdatum anzugeben. Dies dient dazu nicht für jeden Beschäftigungsbeginn einen Zeitraum anlegen zu müssen.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DateTimeCompact,DateTimeCompact>>
| |GueltigBis|

Da Personal zu jeder Zeit einem Unternehmen ein- und austreten kann, gibt es  zusätzlich zum Zeitraum die Möglichkeit ein Ausstiegsdatum anzugeben. Dies dient dazu nicht für jeden Beschäftigungsende einen Zeitraum anlegen zu müssen.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DateTimeCompact,DateTimeCompact>>
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[PersonalIdentobjekte_Type]]
==== PersonalIdentobjekte


PersonalIdentobjekte weist einer Person kein, ein oder mehrere Identobjekte zu. Hinweis: Es handelt sich um eine n:m Beziehung. Auf einen künstlichen Schlüssel wird verzichtet. Die Struktur hat deshalb keinen PrimeKey!

Einer Person kann ein Identobjekt auch mehrfach zugeordnet sein, mit unterschiedlichen GueltigAb, GueltigBis Intervallen. Ein Identobjekt darf immer dann zur Identifikation verwendet werden, wenn bei mindestens einem Zuordnungsobjekt der aktuelle Systemzeitpunkt im GueltigAb,GueltigBis Intervall liegt. Ist GueltigAb nicht angegeben, gilt die Zuordnung ab "schon immer", ist GueltigBis nicht angegeben gilt die Zuordnung "bis ewig".

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_PersonalIdentobjekt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Identobjekt|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |GueltigAb|

Wenn angegeben, definiert GueltigAb den Beginn der Verwendbarkeit des Ident-Objektes. Vor diesem Zeitpunkt darf sich der Bediener mit diesem Objekt nicht erfolgreich am System anmelden können.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DateTimeCompact,DateTimeCompact>>
| |GueltigBis|

Wenn angegeben, definiert GueltigBis das Ende der Verwendbarkeit des Ident-Objektes. Nach diesem Zeitpunkt darf sich der Bediener mit diesem Objekt nicht erfolgreich am System anmelden können.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DateTimeCompact,DateTimeCompact>>
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

[[Personaleinsatz_Type]]
==== Personaleinsatz


Dient zur Festlegung, welche Geräte und Einsatztypen dem  Persinal zugeordnet werden können.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Personaleinsatz|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
|★ |ID_GeraeteEinsatztyp|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_EinsatzArt|

Rolle, die er auf dem Gerätetyp einnimmt


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ReferenzExtern|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in:
 <<husstPersonal_Type,husstPersonal>>

=== technische Enumerationen 


[[ID_IdentobjekttypHUSST_Type]]

==== ID_Identobjekttyp

Die HUSST definiert ID_Identobjekttypen kleiner 1000


Verwendet in: ohne Verwendung


[[ID_PasswortHashtypHUSST_Type]]

==== ID_PasswortHashtyp

Die HUSST definiert PasswortHashTypen kleiner 1000

Die Verfahren 1 bis 4 entsprechen der Empfehlung https://en.wikipedia.org/wiki/Key_derivation_function


Verwendet in: ohne Verwendung



===  Definitionsstand


HUSST Versorgungsdaten - Schema: Personal (verwendet Basisversorgungsdaten) Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
