

=== Vertrieb Rootelemente

[[husstPersonal_Type]]
==== husstPersonal

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Bearbeitung|
[red]#_todo: Doku_#


Datentyp: 
| |Interpretationen|
[red]#_todo: Doku_#


Datentyp: 
| |Unternehmen|
[red]#_todo: Doku_#


Datentyp: 
| |Updateinfo|
[red]#_todo: Doku_#


Datentyp: 
| |VersionInhalt|
[red]#_todo: Doku_#


Datentyp: 
| |VersionStruktur|
[red]#_todo: Doku_#


Datentyp: 
| |Zeitraeume|
[red]#_todo: Doku_#


Datentyp: 
| |Zeitraumoptionen|
[red]#_todo: Doku_#


Datentyp: 
| |DefIdentobjekttyp|
[red]#_todo: Doku_#


Datentyp: <<DefIdentobjekttyp_Type,DefIdentobjekttyp>>
| |DefPasswortHashtyp|
[red]#_todo: Doku_#


Datentyp: <<DefPasswortHashtyp_Type,DefPasswortHashtyp>>
| |Einsatzarten|
[red]#_todo: Doku_#


Datentyp: <<Einsatzarten_Type,Einsatzarten>>
| |Geraetetypen|
[red]#_todo: Doku_#


Datentyp: <<Geraetetypen_Type,Geraetetypen>>
| |Geraet|
[red]#_todo: Doku_#


Datentyp: <<Geraet_Type,Geraet>>
| |GeraeteEinsatztypen|
[red]#_todo: Doku_#


Datentyp: <<GeraeteEinsatztypen_Type,GeraeteEinsatztypen>>
| |Identobjekte|
[red]#_todo: Doku_#


Datentyp: <<Identobjekte_Type,Identobjekte>>
| |PersonalIdentobjekte|
[red]#_todo: Doku_#


Datentyp: <<PersonalIdentobjekte_Type,PersonalIdentobjekte>>
| |Personal|
[red]#_todo: Doku_#


Datentyp: <<Personal_Type,Personal>>
| |Personaleinsatz|
[red]#_todo: Doku_#


Datentyp: <<Personaleinsatz_Type,Personaleinsatz>>
|=======================


=== Vertrieb Elemente


[[DefIdentobjekttyp_Type]]
==== DefIdentobjekttyp

Definiert einen Identifikationstyp zur Anmeldung.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Identobjekttyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Identobjekttyp_Type,ID_Identobjekttyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[DefPasswortHashtyp_Type]]
==== DefPasswortHashtyp

Definiert einen Hashtyp zum vergleichen von Passwörtern.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_PasswortHashtyp|
[red]#_todo: Doku_#


Datentyp: <<ID_PasswortHashtyp_Type,ID_PasswortHashtyp>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Einsatzarten_Type]]
==== Einsatzarten

Personaleinsatz Beschreibung

* Verkäufer

* Kontrolleur

* Zugbegleiter
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_EinsatzArt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Referenz zu einem extern definierten Element.


Datentyp: string
| |ID_Geraetetyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Geraet_Type]]
==== Geraet

Geräteverwaltung
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Geraet|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |KA_KvpOrgID|
KA KVP Nr

Datentyp: <<INT4,INT4>>
| |ID_Unternehmen|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Dient als Referenz um extern definierte Elemente über einen ggf. auch nicht numerischen Schlüssel identifizieren zu können.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[GeraeteEinsatztypen_Type]]
==== GeraeteEinsatztypen

Zur Differenzierung der Datenverteilung
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_GeraeteEinsatztyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Geraetetypen_Type]]
==== Geraetetypen

IMPORTANT: [red]#_todo: Doku_#

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |Bezeichnung|
[red]#_todo: Doku_#


Datentyp: string
| |ReferenzExtern|

Referenz zu einem extern definierten Element.


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Identobjekte_Type]]
==== Identobjekte


Ident Objekte zur Identifizierung einer Person. Die ID des Identobjektes ist über alle Objekttypen und Mandanten eindeutig zu halten.

Idealerweise sollten alle Identobjekte eines Objekttyps über alle Mandanten im System eindeutig sein.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Identobjekt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Identobjekttyp|
[red]#_todo: Doku_#


Datentyp: <<ID_Identobjekttyp_Type,ID_Identobjekttyp>>
| |Bezeichnung|

Freier Text, der z.B. zur Anzeige verwendet werden kann.


Datentyp: string
| |ID_Unternehmen|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|

Systemweit eindeutige Nummer/Kennung des Ident-Objektes z.B. zusammengesetzt aus ID_Identobjekttyp und Identobjekt_Schluessel ggf. mit ID_Unternehmen


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Personal_Type]]
==== Personal

Personalstammdaten
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_Unternehmen|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |ID_AbrUnternehmen|
Abrechnungs-Unternehmen, bei dem Einnahmen abgeliefert werden müssen

Datentyp: <<INT4,INT4>>
| |ID_PasswortHashtyp|
Definiert die Art des Passworthashes

Datentyp: <<ID_PasswortHashtyp_Type,ID_PasswortHashtyp>>
| |Passwort|

Gehashtes Passwort.  Wenn angegeben, ist ID_PasswortHashtyp zwingen anzugeben


Datentyp: string
| |Vorname|
[red]#_todo: Doku_#


Datentyp: string
| |Nachname|
[red]#_todo: Doku_#


Datentyp: string
| |GueltigAb|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |GueltigBis|
[red]#_todo: Doku_#


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[PersonalIdentobjekte_Type]]
==== PersonalIdentobjekte


PersonalIdentobjekte weist einer Person kein, ein oder mehrere Identobjekte zu. Hinweis: Es handelt sich um eine n:m Beziehung. Auf einen künstlichen Schlüssel wird verzichtet. Die Struktur hat deshalb keinen PrimeKey!

Einer Person kann ein Identobjekt auch mehrfach zugeordnet sein, mit unterschiedlichen GueltigAb, GueltigBis Intervallen. Ein Identobjekt darf immer dann zur Identifikation verwendet werden, wenn bei mindestens einem Zuordnungsobjekt der aktuelle Systemzeitpunkt im GueltigAb,GueltigBis Intervall liegt. Ist GueltigAb nicht angegeben, gilt die Zuordnung ab "schon immer", ist GueltigBis nicht angegeben gilt die Zuordnung "bis ewig".

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_PersonalIdentobjekt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Identobjekt|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
| |GueltigAb|

Wenn angegeben, definiert GueltigAb den Beginn der Verwendbarkeit des Ident-Objektes. Vor diesem Zeitpunkt darf sich der Bediener mit diesem Objekt nicht erfolgreich am System anmelden können.


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |GueltigBis|

Wenn angegeben, definiert GueltigBis das Ende der Verwendbarkeit des Ident-Objektes. Nach diesem Zeitpunkt darf sich der Bediener mit diesem Objekt nicht erfolgreich am System anmelden können.


Datentyp: <<DateTimeCompact,DateTimeCompact>>
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

[[Personaleinsatz_Type]]
==== Personaleinsatz

Geräte- und Rollenzuordnung zu Personal
[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|


Datentyp: boolean
|★ |ID_Zeitraum|


Datentyp: <<INT4,INT4>>
|★ |ID_Personaleinsatz|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Personal|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_Geraetetyp|
[red]#_todo: Doku_#


Datentyp: string
|★ |ID_GeraeteEinsatztyp|
[red]#_todo: Doku_#


Datentyp: <<INT4,INT4>>
|★ |ID_EinsatzArt|

Rolle, die er auf dem Gerätetyp einnimmt


Datentyp: <<INT4,INT4>>
| |ReferenzExtern|
[red]#_todo: Doku_#


Datentyp: string
| |DynAttribut|
[red]#_todo: Doku_#


Datentyp: <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente

=== Vertrieb Enumerationen 


[[ID_IdentobjekttypHUSST_Type]]

[[ID_Identobjekttyp_Type]]

==== ID_Identobjekttyp

Die ID_Identobjekttyp ist entweder eine von HUSST vordefinierte Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0 

Die HUSST definiert ID_Identobjekttypen kleiner 1000

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
nicht spezifiziert/unbestimmt
|1|
Fahrermodul
|2|
Chipkarte
|3|
Schlüssel
|4|
Anmeldecode
|=======================


Verwendet in:

* <<DefIdentobjekttyp_Type,DefIdentobjekttyp>>
* <<Identobjekte_Type,Identobjekte>>


[[ID_PasswortHashtypHUSST_Type]]

[[ID_PasswortHashtyp_Type]]

==== ID_PasswortHashtyp

Die ID_PasswortHashtyp ist entweder eine von HUSST vordefinierte Zahl kleiner 1000 oder eine im Projekt vereinbarte Zahl größer gleich 1000. Im freidefinierbaren Bereich gibt es herstellerspezifische Wertebereiche. s. https://github.com/HUSST-de/HUSST/tree/master/Version%203/3.0 

Die HUSST definiert PasswortHashTypen kleiner 1000

Die Verfahren 1 bis 4 entsprechen der Empfehlung https://en.wikipedia.org/wiki/Key_derivation_function

[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|0|
Klartext
|1|
argon2id
|2|
scrypt
|3|
bcrypt
|4|
PBKDF2
|=======================


Verwendet in:

* <<DefPasswortHashtyp_Type,DefPasswortHashtyp>>
* <<Personal_Type,Personal>>



=== Vertrieb Definitionsstand


HUSST Versorgungsdaten - Schema: Personal (verwendet Basisversorgungsdaten) Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
