

=== TarifAngebot Rootelemente

[[OePVTarifDB_Type]]
==== OePVTarifDB


Enthält die vollständige Tarif- und Angebotsdatenbank für den öffentlichen Personennahverkehr (ÖPNV) gemäß HUSST-Standard. Diese Struktur bildet die zentrale Wurzel für alle tarifrelevanten Definitionen, Relationen, Sorten und Preisstufen.


[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Husst-String|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Husst-Complex|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Husst-Complex_Type,Husst-Complex>>
| |Husst-2|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Husst-3|
[red]#_todo: Doku_#

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |Zeitraeume|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<Zeitraeume_Type,Zeitraeume>>
|=======================


Verwendet in: ohne Verwendung

[[Husst-Complex_Type]]
==== Husst-Complex


Bediengebiete erlauben die Defintion von Sichten auf Auswahlelemente (Tarifrelevante Punkte, Haltestellen, etc.). Damit ist die Möglichkeit zur Filterung von Start/Zielauswahlen in verschiedenen Umfeldern möglich.

[options="header" cols="2%,20%,78%"]
|=======================
| |Eigenschaft|Beschreibung
| |Deaktiviert|
Deaktiviert den Datensatz mit dem gleichen Primary-Key aus Lieferungen mit der gleichen Haupt- aber kleineren Subzeitraumnummern.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] boolean
|★ |ID_Zeitraum|
Referenz auf den Zeitraum, zu dem das Element gehört.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_Tarifgebiet|
Referenz auf das Tarifgebiet, dem das Element zugeordnet ist.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
|★ |ID_Bediengebiet|
Eindeutige ID des Bediengebiets.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<INT4,INT4>>
| |ID_Enum|


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<ID_Enum_Type,ID_Enum>>
| |Bezeichnung|

Bezeichnung des Bediengebiets z.B. Automaten oder Kassen.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] string
| |DynAttribut|

Optionaler Erweiterungsmechanismus für zusätzliche, projektspezifische Eigenschaften. Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.


image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
| |DynAttribut|
Defaulttext: Optionaler Erweiterungsmechanismus für zusätzliche,  projektspezifische Eigenschaften.   Unbekannte Attribute sind von empfangenden Systemen zu ignorieren.

image:t-angle-brackets-v2.svg[<T>,35,35,opts=inline] <<DynAttribut_Subtype,DynAttribut_Subtype>>
|=======================
  ★  Pflichtelemente



Verwendet in: ohne Verwendung



=== TarifAngebot Elemente


=== TarifAngebot Enumerationen 


[[ID_EnumHUSST_Type]]

[[ID_Enum_Type]]

==== ID_Enum
Die HUSST definiert ID_Enum kleiner 1000

.Note
====
z.B. PT60M - 60 Minuten

====


[options="header" cols="20%,80%"]
|=======================
|Wert|Beschreibung
|1|
Standard Enum für den allgemeinen Verkauf


Verwendet in: ohne Verwendung

|=======================


Verwendet in: ohne Verwendung



=== TarifAngebot Definitionsstand


HUSST Versorgungsdaten - Schemata: Tarif, Angebot (verwendet Basisversorgungsdaten) Version: 3.7.0

Mehr Informationen:

* https://husst.de/

* https://github.com/HUSST-de/HUSST

Lizensiert unter CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
