name: Build V3.7.0 Docs with Gradle

on:
  push:
    branches:
      - TechnischeDoku
    paths:
      - 'Version 3/docs/**'
      - 'Version 3/3.7.0/**'
  pull_request:
    branches:
      - TechnischeDoku
    paths:
      - 'Version 3/docs/**'
      - 'Version 3/3.7.0/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Docs
        working-directory: Version 3/docs
        run: ./gradlew build
